apiVersion: 1

datasources:
  - name: SNAD Prometheus
    uid: snad-prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    editable: false
    jsonData:
      httpMethod: POST
      manageAlerts: true
