package com.sanad.platform.tenant.domain;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.EntityListeners;
import jakarta.persistence.EnumType;
import jakarta.persistence.Enumerated;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.Table;
import jakarta.persistence.UniqueConstraint;
import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.NotNull;
import jakarta.validation.constraints.Pattern;
import jakarta.validation.constraints.Size;

import org.springframework.data.annotation.CreatedDate;
import org.springframework.data.annotation.LastModifiedDate;
import org.springframework.data.jpa.domain.support.AuditingEntityListener;

import java.time.Instant;
import java.util.Objects;
import java.util.UUID;

/**
 * JPA entity representing a tenant in the SANAD multi-tenant platform.
 *
 * <p>A tenant is the top-level isolation boundary. Every other domain entity
 * in the platform belongs to exactly one tenant. The {@code subdomain} is the
 * user-facing identifier used to route requests to the correct tenant (e.g.
 * {@code acme.sanad.example} resolves to the tenant with subdomain "acme").</p>
 *
 * <p>Stage 0 (this class) intentionally contains no business methods beyond
 * equals/hashCode/toString. Behaviour will be added in subsequent stages
 * alongside the application service layer.</p>
 */
@Entity
@Table(
        name = "tenants",
        uniqueConstraints = @UniqueConstraint(
                name = "uk_tenants_subdomain",
                columnNames = "subdomain"
        )
)
@EntityListeners(AuditingEntityListener.class)
public class Tenant {

    /** Surrogate primary key. UUID v4 generated by the application. */
    @Id
    @GeneratedValue(strategy = GenerationType.UUID)
    @Column(name = "id", nullable = false, updatable = false, columnDefinition = "uuid")
    private UUID id;

    /** Human-readable tenant name (e.g. "Acme Corporation"). */
    @NotBlank
    @Size(max = 200)
    @Column(name = "name", nullable = false, length = 200)
    private String name;

    /**
     * URL-safe subdomain used for tenant routing. Lowercase letters,
     * digits, and hyphens only; must start and end with a letter or digit.
     */
    @NotBlank
    @Size(max = 63)
    @Pattern(
            regexp = "^[a-z0-9](?:[a-z0-9-]{1,61}[a-z0-9])?$",
            message = "subdomain must be 1-63 chars, lowercase alphanumeric with optional internal hyphens"
    )
    @Column(name = "subdomain", nullable = false, length = 63)
    private String subdomain;

    /** Current lifecycle status of the tenant. */
    @NotNull
    @Enumerated(EnumType.STRING)
    @Column(name = "status", nullable = false, length = 20)
    private TenantStatus status;

    /** Audit: when the row was first persisted. Set by JPA auditing. */
    @CreatedDate
    @Column(name = "created_at", nullable = false, updatable = false)
    private Instant createdAt;

    /** Audit: when the row was last modified. Set by JPA auditing. */
    @LastModifiedDate
    @Column(name = "updated_at", nullable = false)
    private Instant updatedAt;

    // ------------------------------------------------------------
    // Constructors
    // ------------------------------------------------------------

    /** No-arg constructor required by JPA. */
    protected Tenant() {
    }

    public Tenant(String name, String subdomain, TenantStatus status) {
        this.name = name;
        this.subdomain = subdomain;
        this.status = status;
    }

    // ------------------------------------------------------------
    // Getters / Setters
    // ------------------------------------------------------------

    public UUID getId() {
        return id;
    }

    public void setId(UUID id) {
        this.id = id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getSubdomain() {
        return subdomain;
    }

    public void setSubdomain(String subdomain) {
        this.subdomain = subdomain;
    }

    public TenantStatus getStatus() {
        return status;
    }

    public void setStatus(TenantStatus status) {
        this.status = status;
    }

    public Instant getCreatedAt() {
        return createdAt;
    }

    public void setCreatedAt(Instant createdAt) {
        this.createdAt = createdAt;
    }

    public Instant getUpdatedAt() {
        return updatedAt;
    }

    public void setUpdatedAt(Instant updatedAt) {
        this.updatedAt = updatedAt;
    }

    // ------------------------------------------------------------
    // equals / hashCode / toString (based on natural key: subdomain)
    // ------------------------------------------------------------

    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (!(o instanceof Tenant tenant)) {
            return false;
        }
        // If both have IDs, compare by ID; otherwise compare by subdomain.
        // This avoids false equality for transient (un-persisted) entities.
        if (id != null && tenant.id != null) {
            return Objects.equals(id, tenant.id);
        }
        return Objects.equals(subdomain, tenant.subdomain);
    }

    @Override
    public int hashCode() {
        // Hash by subdomain (natural key) so hash is stable pre- and post-persist
        return Objects.hash(subdomain);
    }

    @Override
    public String toString() {
        return "Tenant{" +
                "id=" + id +
                ", name='" + name + '\'' +
                ", subdomain='" + subdomain + '\'' +
                ", status=" + status +
                ", createdAt=" + createdAt +
                ", updatedAt=" + updatedAt +
                '}';
    }
}
