import { describe, expect, it } from "vitest";
import { HRM_CAPABILITIES } from "./capabilities";

describe("HRM G2 canonical capability registry", () => {
  it("pins the 13 canonical G2 capability codes exactly", () => {
    const g2 = [
      HRM_CAPABILITIES.ATTENDANCE_SELF_RECORD,
      HRM_CAPABILITIES.ATTENDANCE_SELF_VIEW,
      HRM_CAPABILITIES.ATTENDANCE_TEAM_VIEW,
      HRM_CAPABILITIES.ATTENDANCE_ADMIN,
      HRM_CAPABILITIES.ATTENDANCE_CORRECT,
      HRM_CAPABILITIES.LEAVE_SELF_REQUEST,
      HRM_CAPABILITIES.LEAVE_SELF_VIEW,
      HRM_CAPABILITIES.LEAVE_TEAM_APPROVE,
      HRM_CAPABILITIES.LEAVE_HR_APPROVE,
      HRM_CAPABILITIES.LEAVE_POLICY_ADMIN,
      HRM_CAPABILITIES.TIMESHEET_SELF_VIEW,
      HRM_CAPABILITIES.TIMESHEET_SELF_SUBMIT,
      HRM_CAPABILITIES.TIMESHEET_TEAM_APPROVE,
    ];

    expect(g2).toEqual([
      "HRM.ATTENDANCE.SELF_RECORD",
      "HRM.ATTENDANCE.SELF_VIEW",
      "HRM.ATTENDANCE.TEAM_VIEW",
      "HRM.ATTENDANCE.ADMIN",
      "HRM.ATTENDANCE.CORRECT",
      "HRM.LEAVE.SELF_REQUEST",
      "HRM.LEAVE.SELF_VIEW",
      "HRM.LEAVE.TEAM_APPROVE",
      "HRM.LEAVE.HR_APPROVE",
      "HRM.LEAVE.POLICY_ADMIN",
      "HRM.TIMESHEET.SELF_VIEW",
      "HRM.TIMESHEET.SELF_SUBMIT",
      "HRM.TIMESHEET.TEAM_APPROVE",
    ]);
    expect(new Set(g2).size).toBe(13);
  });
});
