import { MeResponse } from "../api/auth";

/**
 * Capability-based access control utilities for the frontend.
 *
 * The backend is always authoritative for RBAC enforcement.
 * These checks are "best-effort" UX guards to hide/disable UI elements
 * the user cannot use, reducing confusing 403 errors.
 */

/**
 * Check if the user has a specific capability.
 * Capabilities are populated by the /me endpoint.
 */
export function hasCapability(me: MeResponse | null, capability: string): boolean {
  if (!me?.capabilities) return false;
  return me.capabilities.includes(capability);
}

/**
 * Check if the user has any of the specified capabilities.
 */
export function hasAnyCapability(me: MeResponse | null, capabilities: string[]): boolean {
  if (!me?.capabilities) return false;
  return capabilities.some((cap) => me.capabilities.includes(cap));
}

/**
 * Check if the user has all of the specified capabilities.
 */
export function hasAllCapabilities(me: MeResponse | null, capabilities: string[]): boolean {
  if (!me?.capabilities) return false;
  return capabilities.every((cap) => me.capabilities.includes(cap));
}

// ============================================================
// CRM-specific capability constants
// ============================================================

export const CRM_CAPABILITIES = {
  ACCOUNT_READ: "CRM.ACCOUNT.READ",
  ACCOUNT_WRITE: "CRM.ACCOUNT.WRITE",
  ACCOUNT_ARCHIVE: "CRM.ACCOUNT.ARCHIVE",
  CONTACT_READ: "CRM.CONTACT.READ",
  CONTACT_WRITE: "CRM.CONTACT.WRITE",
  CONTACT_ARCHIVE: "CRM.CONTACT.ARCHIVE",
  LEAD_READ: "CRM.LEAD.READ",
  LEAD_WRITE: "CRM.LEAD.WRITE",
  LEAD_CONVERT: "CRM.LEAD.CONVERT",
  OPPORTUNITY_READ: "CRM.OPPORTUNITY.READ",
  OPPORTUNITY_WRITE: "CRM.OPPORTUNITY.WRITE",
  ACTIVITY_READ: "CRM.ACTIVITY.READ",
  ACTIVITY_WRITE: "CRM.ACTIVITY.WRITE",
  TAG_READ: "CRM.TAG.READ",
  TAG_WRITE: "CRM.TAG.WRITE",
  TASK_READ: "CRM.TASK.READ",
  TASK_WRITE: "CRM.TASK.WRITE",
  NOTE_READ: "CRM.NOTE.READ",
  NOTE_WRITE: "CRM.NOTE.WRITE",
  CASE_READ: "CRM.CASE.READ",
  CASE_WRITE: "CRM.CASE.WRITE",
  EMAIL_READ: "CRM.EMAIL.READ",
  EMAIL_WRITE: "CRM.EMAIL.WRITE",
  REPORTS_READ: "CRM.REPORTS.READ",
  INTELLIGENCE_READ: "CRM.CUSTOMER_INTELLIGENCE.READ",
  ADMIN: "CRM.ADMIN",
  CUSTOM_FIELD_READ: "CRM.CUSTOM_FIELD.READ",
  CUSTOM_FIELD_WRITE: "CRM.CUSTOM_FIELD.WRITE",
  IMPORT_READ: "CRM.IMPORT.READ",
  IMPORT_WRITE: "CRM.IMPORT.WRITE",
  PORTAL_READ: "CRM.PORTAL.READ",
  PORTAL_WRITE: "CRM.PORTAL.WRITE",
} as const;

/**
 * Canonical HRM capabilities used by the frontend as UX-only guards.
 * Backend authorization remains authoritative.
 */
export const HRM_CAPABILITIES = {
  EMPLOYEE_VIEW: "HRM.EMPLOYEE.VIEW",
  EMPLOYEE_CREATE: "HRM.EMPLOYEE.CREATE",
  EMPLOYEE_UPDATE: "HRM.EMPLOYEE.UPDATE",
  EMPLOYEE_TERMINATE: "HRM.EMPLOYEE.TERMINATE",
  ORG_STRUCTURE_VIEW: "HRM.ORG_STRUCTURE.VIEW",
  ORG_STRUCTURE_MANAGE: "HRM.ORG_STRUCTURE.MANAGE",
  ASSIGNMENT_VIEW: "HRM.ASSIGNMENT.VIEW",
  ASSIGNMENT_MANAGE: "HRM.ASSIGNMENT.MANAGE",
  CONTRACT_VIEW: "HRM.CONTRACT.VIEW",
  CONTRACT_MANAGE: "HRM.CONTRACT.MANAGE",
  COMPENSATION_VIEW: "HRM.COMPENSATION.VIEW",
  COMPENSATION_MANAGE: "HRM.COMPENSATION.MANAGE",
  PII_VIEW: "HRM.PII.VIEW",
  PII_MANAGE: "HRM.PII.MANAGE",
  USER_LINK_MANAGE: "HRM.USER_LINK.MANAGE",
  AUDIT_VIEW: "HRM.AUDIT.VIEW",
  COMPLIANCE_OVERRIDE_REQUEST: "HRM.COMPLIANCE_OVERRIDE.REQUEST",
  COMPLIANCE_OVERRIDE_APPROVE: "HRM.COMPLIANCE_OVERRIDE.APPROVE",
  ADMIN: "HRM.ADMIN",

  // === G1 Recruitment & Onboarding ===
  RECRUITMENT_OPENING_VIEW: "HRM.RECRUITMENT.OPENING.VIEW",
  RECRUITMENT_OPENING_MANAGE: "HRM.RECRUITMENT.OPENING.MANAGE",
  RECRUITMENT_OPENING_PUBLISH: "HRM.RECRUITMENT.OPENING.PUBLISH",
  RECRUITMENT_CANDIDATE_VIEW: "HRM.RECRUITMENT.CANDIDATE.VIEW",
  RECRUITMENT_CANDIDATE_MANAGE: "HRM.RECRUITMENT.CANDIDATE.MANAGE",
  RECRUITMENT_APPLICATION_SUBMIT: "HRM.RECRUITMENT.APPLICATION.SUBMIT",
  RECRUITMENT_APPLICATION_MANAGE: "HRM.RECRUITMENT.APPLICATION.MANAGE",
  RECRUITMENT_APPLICATION_ADVANCE: "HRM.RECRUITMENT.APPLICATION.ADVANCE",
  RECRUITMENT_APPLICATION_REJECT: "HRM.RECRUITMENT.APPLICATION.REJECT",
  RECRUITMENT_APPLICATION_WITHDRAW: "HRM.RECRUITMENT.APPLICATION.WITHDRAW",
  RECRUITMENT_INTERVIEW_SCHEDULE: "HRM.RECRUITMENT.INTERVIEW.SCHEDULE",
  RECRUITMENT_INTERVIEW_MANAGE: "HRM.RECRUITMENT.INTERVIEW.MANAGE",
  RECRUITMENT_INTERVIEW_RECORD_OUTCOME: "HRM.RECRUITMENT.INTERVIEW.RECORD_OUTCOME",
  RECRUITMENT_OFFER_MANAGE: "HRM.RECRUITMENT.OFFER.MANAGE",
  RECRUITMENT_OFFER_EXTEND: "HRM.RECRUITMENT.OFFER.EXTEND",
  RECRUITMENT_OFFER_APPROVE: "HRM.RECRUITMENT.OFFER.APPROVE",
  RECRUITMENT_OFFER_ACCEPT: "HRM.RECRUITMENT.OFFER.ACCEPT",
  RECRUITMENT_OFFER_DECLINE: "HRM.RECRUITMENT.OFFER.DECLINE",
  RECRUITMENT_HIRE_CONVERT: "HRM.RECRUITMENT.HIRE.CONVERT",
  ONBOARDING_PLAN_MANAGE: "HRM.ONBOARDING.PLAN.MANAGE",
  ONBOARDING_TASK_COMPLETE: "HRM.ONBOARDING.TASK.COMPLETE",
  ONBOARDING_TASK_WAIVE: "HRM.ONBOARDING.TASK.WAIVE",

  // === G2 Time, Attendance, Timesheets & Leave ===
  ATTENDANCE_SELF_RECORD: "HRM.ATTENDANCE.SELF_RECORD",
  ATTENDANCE_SELF_VIEW: "HRM.ATTENDANCE.SELF_VIEW",
  ATTENDANCE_TEAM_VIEW: "HRM.ATTENDANCE.TEAM_VIEW",
  ATTENDANCE_ADMIN: "HRM.ATTENDANCE.ADMIN",
  ATTENDANCE_CORRECT: "HRM.ATTENDANCE.CORRECT",
  LEAVE_SELF_REQUEST: "HRM.LEAVE.SELF_REQUEST",
  LEAVE_SELF_VIEW: "HRM.LEAVE.SELF_VIEW",
  LEAVE_TEAM_APPROVE: "HRM.LEAVE.TEAM_APPROVE",
  LEAVE_HR_APPROVE: "HRM.LEAVE.HR_APPROVE",
  LEAVE_POLICY_ADMIN: "HRM.LEAVE.POLICY_ADMIN",
  TIMESHEET_SELF_VIEW: "HRM.TIMESHEET.SELF_VIEW",
  TIMESHEET_SELF_SUBMIT: "HRM.TIMESHEET.SELF_SUBMIT",
  TIMESHEET_TEAM_APPROVE: "HRM.TIMESHEET.TEAM_APPROVE",
} as const;
