-- ============================================================
-- SNAD Platform — G3 Authenticated Acceptance Seed
-- ------------------------------------------------------------
-- Idempotent seed data for the G3 authenticated acceptance
-- workflow (.github/workflows/g3-authenticated-acceptance.yml).
--
-- Run order:
--   1. Flyway migrations (V1 ... V20261003_3) — schema + base
--      capability catalog + G3 performance capabilities
--      (HRM.PERFORMANCE.GOAL.SELF_VIEW, SELF_UPDATE, TEAM_MANAGE,
--       HRM.PERFORMANCE.REVIEW.SELF_VIEW, SELF_SUBMIT, TEAM_MANAGE,
--       HRM.PERFORMANCE.ADMIN)
--   2. This file (g3-acceptance-seed.sql) — G3 test tenant, plan,
--      subscription, 3 users (Employee, Manager, Unauthorized),
--      canonical Person -> Employment -> PRIMARY Assignment identity
--      graph, RBAC roles with G3 capabilities, role assignments,
--      and a deterministic seeded performance goal.
--
-- Tenant created:
--   • G3 Tenant — "G3 Acceptance Tenant" — subdomain g3-acceptance
--     ID: 44444444-4444-4444-8444-444444444441
--
-- Users created (3 total):
--   • g3-employee@g3-acceptance.example    — Employee (self goals + self reviews)
--   • g3-manager@g3-acceptance.example    — Manager (team goals + team reviews)
--   • g3-unauthorized@g3-acceptance.example — Unauthorized (no G3 capabilities)
--
-- Canonical reporting line:
--   Employee Person -> ACTIVE Employment -> PRIMARY Assignment
--   Employee PRIMARY Assignment.reports_to_assignment_id -> Manager PRIMARY Assignment
--
-- Capabilities per role:
--   G3_EMPLOYEE: HRM.PERFORMANCE.GOAL.SELF_VIEW, HRM.PERFORMANCE.GOAL.SELF_UPDATE,
--                HRM.PERFORMANCE.REVIEW.SELF_VIEW, HRM.PERFORMANCE.REVIEW.SELF_SUBMIT
--   G3_MANAGER:  HRM.PERFORMANCE.GOAL.TEAM_MANAGE, HRM.PERFORMANCE.REVIEW.TEAM_MANAGE
--   G3_UNAUTHORIZED: (none — no G3 performance capabilities)
--
-- Password hashing:
--   The bcrypt hash is computed at runtime via psql variable binding:
--     psql -v g3_e2e_password="$G3_E2E_PASSWORD" -f g3-acceptance-seed.sql
--   The cleartext password is generated by the CI workflow at runtime
--   (cryptographically random per run), masked via ::add-mask::,
--   written to GITHUB_ENV, and NEVER committed to the repository.
--   The seed SQL uses crypt(:'g3_e2e_password', gen_salt('bf', 10))
--   so the cleartext never appears in SQL text either.
--
-- The seed is safe to re-run: every INSERT uses ON CONFLICT DO NOTHING
-- or WHERE NOT EXISTS guards.
-- ============================================================

CREATE EXTENSION IF NOT EXISTS pgcrypto;

-- ----------------------------------------------------------------------------
-- 1. Tenant
-- ----------------------------------------------------------------------------
INSERT INTO tenants (id, name, subdomain, status, created_at, updated_at)
VALUES (
    '44444444-4444-4444-8444-444444444441',
    'G3 Acceptance Tenant',
    'g3-acceptance',
    'ACTIVE',
    NOW(),
    NOW()
)
ON CONFLICT (id) DO NOTHING;

-- ----------------------------------------------------------------------------
-- 2. Plan + plan_version + tenant_subscription
-- ----------------------------------------------------------------------------
INSERT INTO saas_plans (
    id, code, name, status, currency_code,
    monthly_price_minor, annual_price_minor, trial_days,
    max_users, max_organizations, storage_mb,
    created_at, updated_at
)
VALUES (
    '44444444-4444-4444-8444-444444444442',
    'G3-ACCEPTANCE-PLAN',
    'G3 Acceptance Plan',
    'ACTIVE',
    'SAR',
    30000,
    300000,
    0,
    10,
    5,
    1024,
    NOW(),
    NOW()
)
ON CONFLICT (id) DO NOTHING;

INSERT INTO plan_versions (
    id, plan_id, version_number, status,
    effective_from, currency_code, monthly_price_minor,
    annual_price_minor, trial_days, max_users,
    max_organizations, storage_mb, created_at, updated_at
)
VALUES (
    '44444444-4444-4444-8444-444444444443',
    '44444444-4444-4444-8444-444444444442',
    1,
    'ACTIVE',
    NOW() - INTERVAL '1 day',
    'SAR',
    30000,
    300000,
    0,
    10,
    5,
    1024,
    NOW(),
    NOW()
)
ON CONFLICT (id) DO NOTHING;

INSERT INTO tenant_subscriptions (
    id, tenant_id, plan_id, plan_version_id, status,
    billing_cycle, seat_quantity, credit_balance_minor,
    started_at, current_period_start, current_period_end,
    cancel_at_period_end, created_at, updated_at
)
VALUES (
    '44444444-4444-4444-8444-444444444444',
    '44444444-4444-4444-8444-444444444441',
    '44444444-4444-4444-8444-444444444442',
    '44444444-4444-4444-8444-444444444443',
    'ACTIVE',
    'MONTHLY',
    3,
    0,
    NOW() - INTERVAL '1 day',
    NOW() - INTERVAL '1 day',
    NOW() + INTERVAL '29 days',
    FALSE,
    NOW(),
    NOW()
)
ON CONFLICT (id) DO NOTHING;

-- Enable HRM module
INSERT INTO plan_module_entitlements (
    id, plan_id, module_id, module_enabled,
    capability_code, capability_value, limit_value, quota_value, quota_period,
    effective_at, created_at, updated_at
)
SELECT
    gen_random_uuid(),
    '44444444-4444-4444-8444-444444444442',
    m.id,
    true,
    'HRM.ENABLED',
    'true',
    NULL,
    NULL,
    NULL,
    NOW(),
    NOW(),
    NOW()
FROM modules m
WHERE m.code = 'HRM'
  AND NOT EXISTS (
      SELECT 1 FROM plan_module_entitlements pme
      WHERE pme.plan_id = '44444444-4444-4444-8444-444444444442'
        AND pme.module_id = m.id
        AND pme.capability_code = 'HRM.ENABLED'
  );

-- ----------------------------------------------------------------------------
-- 3. Organization
-- ----------------------------------------------------------------------------
INSERT INTO organizations (id, tenant_id, name, description, status, created_at, updated_at)
VALUES (
    '44444444-4444-4444-8444-444444444445',
    '44444444-4444-4444-8444-444444444441',
    'G3 Acceptance Org',
    'G3 acceptance testing organization',
    'ACTIVE',
    NOW(),
    NOW()
)
ON CONFLICT (id) DO NOTHING;

-- ----------------------------------------------------------------------------
-- 4. Users (3 total)
-- ----------------------------------------------------------------------------
INSERT INTO users (id, tenant_id, email, display_name, status, password_hash, created_at, updated_at)
VALUES (
    '44444444-4444-4444-8444-444444444451',
    '44444444-4444-4444-8444-444444444441',
    'g3-employee@g3-acceptance.example',
    'G3 Employee',
    'ACTIVE',
    crypt(:'g3_e2e_password', gen_salt('bf', 10)),
    NOW(),
    NOW()
)
ON CONFLICT (id) DO NOTHING;

INSERT INTO users (id, tenant_id, email, display_name, status, password_hash, created_at, updated_at)
VALUES (
    '44444444-4444-4444-8444-444444444452',
    '44444444-4444-4444-8444-444444444441',
    'g3-manager@g3-acceptance.example',
    'G3 Manager',
    'ACTIVE',
    crypt(:'g3_e2e_password', gen_salt('bf', 10)),
    NOW(),
    NOW()
)
ON CONFLICT (id) DO NOTHING;

INSERT INTO users (id, tenant_id, email, display_name, status, password_hash, created_at, updated_at)
VALUES (
    '44444444-4444-4444-8444-444444444453',
    '44444444-4444-4444-8444-444444444441',
    'g3-unauthorized@g3-acceptance.example',
    'G3 Unauthorized',
    'ACTIVE',
    crypt(:'g3_e2e_password', gen_salt('bf', 10)),
    NOW(),
    NOW()
)
ON CONFLICT (id) DO NOTHING;

-- ----------------------------------------------------------------------------
-- 5. Organization memberships
-- ----------------------------------------------------------------------------
INSERT INTO organization_memberships (id, tenant_id, organization_id, user_id, email, display_name, status, created_at, updated_at)
VALUES
    ('44444444-4444-4444-8444-444444444461', '44444444-4444-4444-8444-444444444441', '44444444-4444-4444-8444-444444444445', '44444444-4444-4444-8444-444444444451', 'g3-employee@g3-acceptance.example', 'G3 Employee', 'ACTIVE', NOW(), NOW()),
    ('44444444-4444-4444-8444-444444444462', '44444444-4444-4444-8444-444444444441', '44444444-4444-4444-8444-444444444445', '44444444-4444-4444-8444-444444444452', 'g3-manager@g3-acceptance.example', 'G3 Manager', 'ACTIVE', NOW(), NOW()),
    ('44444444-4444-4444-8444-444444444463', '44444444-4444-4444-8444-444444444441', '44444444-4444-4444-8444-444444444445', '44444444-4444-4444-8444-444444444453', 'g3-unauthorized@g3-acceptance.example', 'G3 Unauthorized', 'ACTIVE', NOW(), NOW())
ON CONFLICT (id) DO NOTHING;

-- ----------------------------------------------------------------------------
-- 6. Canonical HR identity graph
-- ----------------------------------------------------------------------------
SELECT set_config('app.tenant_id', '44444444-4444-4444-8444-444444444441', false);

-- Legal entity
INSERT INTO legal_entities (
    id, tenant_id, code, name, registered_country_code,
    statutory_country_code, status, created_at, updated_at
)
VALUES (
    '44444444-4444-4444-8444-444444444446',
    '44444444-4444-4444-8444-444444444441',
    'G3-ACCEPTANCE-LE',
    'G3 Acceptance Legal Entity',
    'SA',
    'SA',
    'ACTIVE',
    NOW(),
    NOW()
)
ON CONFLICT (id) DO NOTHING;

INSERT INTO organization_legal_entities (
    id, tenant_id, organization_id, legal_entity_id,
    effective_from, effective_to, status, created_at
)
VALUES (
    '44444444-4444-4444-8444-444444444447',
    '44444444-4444-4444-8444-444444444441',
    '44444444-4444-4444-8444-444444444445',
    '44444444-4444-4444-8444-444444444446',
    CURRENT_DATE - 1,
    NULL,
    'ACTIVE',
    NOW()
)
ON CONFLICT (id) DO NOTHING;

-- People linked 1:1 to governed G3 users
INSERT INTO hr_people (
    id, tenant_id, user_id, first_name, middle_name, last_name,
    display_name, version, created_at, updated_at
)
VALUES
    ('44444444-4444-4444-8444-444444444471',
     '44444444-4444-4444-8444-444444444441',
     '44444444-4444-4444-8444-444444444451',
     'G3', NULL, 'Employee', 'G3 Employee', 0, NOW(), NOW()),
    ('44444444-4444-4444-8444-444444444472',
     '44444444-4444-4444-8444-444444444441',
     '44444444-4444-4444-8444-444444444452',
     'G3', NULL, 'Manager', 'G3 Manager', 0, NOW(), NOW()),
    ('44444444-4444-4444-8444-444444444473',
     '44444444-4444-4444-8444-444444444441',
     '44444444-4444-4444-8444-444444444453',
     'G3', NULL, 'Unauthorized', 'G3 Unauthorized', 0, NOW(), NOW())
ON CONFLICT (id) DO NOTHING;

-- Active canonical employments. Keep the legacy required identity columns populated
-- while authority is resolved exclusively through Person -> Employment.
INSERT INTO hr_employees (
    id, tenant_id, person_id, legal_entity_id, worker_classification_code,
    employee_number, first_name, last_name, display_name, email,
    employment_type, status, hire_date, version, created_at, updated_at
)
VALUES
    ('44444444-4444-4444-8444-444444444481',
     '44444444-4444-4444-8444-444444444441',
     '44444444-4444-4444-8444-444444444471',
     '44444444-4444-4444-8444-444444444446',
     'GENERIC_EMPLOYEE',
     'G3-EMP-001', 'G3', 'Employee', 'G3 Employee', 'g3-employee@g3-acceptance.example',
     'FULL_TIME', 'ACTIVE', CURRENT_DATE - 365, 0, NOW(), NOW()),
    ('44444444-4444-4444-8444-444444444482',
     '44444444-4444-4444-8444-444444444441',
     '44444444-4444-4444-8444-444444444472',
     '44444444-4444-4444-8444-444444444446',
     'GENERIC_EMPLOYEE',
     'G3-MGR-001', 'G3', 'Manager', 'G3 Manager', 'g3-manager@g3-acceptance.example',
     'FULL_TIME', 'ACTIVE', CURRENT_DATE - 730, 0, NOW(), NOW()),
    ('44444444-4444-4444-8444-444444444483',
     '44444444-4444-4444-8444-444444444441',
     '44444444-4444-4444-8444-444444444473',
     '44444444-4444-4444-8444-444444444446',
     'GENERIC_EMPLOYEE',
     'G3-UNAUTH-001', 'G3', 'Unauthorized', 'G3 Unauthorized', 'g3-unauthorized@g3-acceptance.example',
     'FULL_TIME', 'ACTIVE', CURRENT_DATE - 90, 0, NOW(), NOW())
ON CONFLICT (id) DO NOTHING;

-- PRIMARY Assignments — canonical table consumed by HrEmploymentScopeResolver.
-- Insert Manager first so the Employee reporting edge can reference it.
INSERT INTO hr_employee_assignments (
    id, tenant_id, employment_id, organization_id,
    reports_to_assignment_id, assignment_type, occupancy_mode,
    allocation_percent, effective_from, effective_to, status,
    version, created_at, updated_at
)
VALUES (
    '44444444-4444-4444-8444-444444444492',
    '44444444-4444-4444-8444-444444444441',
    '44444444-4444-4444-8444-444444444482',
    '44444444-4444-4444-8444-444444444445',
    NULL,
    'PRIMARY', 'NON_OCCUPYING', 100,
    CURRENT_DATE - 730, NULL, 'ACTIVE',
    0, NOW(), NOW()
)
ON CONFLICT (id) DO NOTHING;

INSERT INTO hr_employee_assignments (
    id, tenant_id, employment_id, organization_id,
    reports_to_assignment_id, assignment_type, occupancy_mode,
    allocation_percent, effective_from, effective_to, status,
    version, created_at, updated_at
)
VALUES (
    '44444444-4444-4444-8444-444444444491',
    '44444444-4444-4444-8444-444444444441',
    '44444444-4444-4444-8444-444444444481',
    '44444444-4444-4444-8444-444444444445',
    '44444444-4444-4444-8444-444444444492',
    'PRIMARY', 'NON_OCCUPYING', 100,
    CURRENT_DATE - 365, NULL, 'ACTIVE',
    0, NOW(), NOW()
)
ON CONFLICT (id) DO NOTHING;

INSERT INTO hr_employee_assignments (
    id, tenant_id, employment_id, organization_id,
    reports_to_assignment_id, assignment_type, occupancy_mode,
    allocation_percent, effective_from, effective_to, status,
    version, created_at, updated_at
)
VALUES (
    '44444444-4444-4444-8444-444444444493',
    '44444444-4444-4444-8444-444444444441',
    '44444444-4444-4444-8444-444444444483',
    '44444444-4444-4444-8444-444444444445',
    NULL,
    'PRIMARY', 'NON_OCCUPYING', 100,
    CURRENT_DATE - 90, NULL, 'ACTIVE',
    0, NOW(), NOW()
)
ON CONFLICT (id) DO NOTHING;

-- ----------------------------------------------------------------------------
-- 7. RBAC roles with G3 capabilities
-- ----------------------------------------------------------------------------
-- G3_EMPLOYEE role
INSERT INTO roles (id, tenant_id, code, name, description, status, is_system_managed, created_at, updated_at)
VALUES ('44444444-4444-4444-8444-444444444501', '44444444-4444-4444-8444-444444444441', 'G3_EMPLOYEE', 'G3 Employee', 'G3 self-service performance role', 'ACTIVE', FALSE, NOW(), NOW())
ON CONFLICT (id) DO NOTHING;

-- G3_MANAGER role
INSERT INTO roles (id, tenant_id, code, name, description, status, is_system_managed, created_at, updated_at)
VALUES ('44444444-4444-4444-8444-444444444502', '44444444-4444-4444-8444-444444444441', 'G3_MANAGER', 'G3 Manager', 'G3 team management performance role', 'ACTIVE', FALSE, NOW(), NOW())
ON CONFLICT (id) DO NOTHING;

-- G3_UNAUTHORIZED role (no G3 capabilities)
INSERT INTO roles (id, tenant_id, code, name, description, status, is_system_managed, created_at, updated_at)
VALUES ('44444444-4444-4444-8444-444444444503', '44444444-4444-4444-8444-444444444441', 'G3_UNAUTHORIZED', 'G3 Unauthorized', 'G3 role without performance capabilities', 'ACTIVE', FALSE, NOW(), NOW())
ON CONFLICT (id) DO NOTHING;

-- G3_EMPLOYEE capabilities
INSERT INTO role_capabilities (id, tenant_id, role_id, capability_id, created_at)
SELECT gen_random_uuid(), r.tenant_id, r.id, cap.id, NOW()
FROM roles r
CROSS JOIN access_capabilities cap
WHERE r.tenant_id = '44444444-4444-4444-8444-444444444441'
  AND r.code = 'G3_EMPLOYEE'
  AND cap.code IN (
      'HRM.PERFORMANCE.GOAL.SELF_VIEW',
      'HRM.PERFORMANCE.GOAL.SELF_UPDATE',
      'HRM.PERFORMANCE.REVIEW.SELF_VIEW',
      'HRM.PERFORMANCE.REVIEW.SELF_SUBMIT'
  )
  AND NOT EXISTS (
      SELECT 1 FROM role_capabilities rc
      WHERE rc.tenant_id = r.tenant_id AND rc.role_id = r.id AND rc.capability_id = cap.id
  );

-- G3_MANAGER capabilities
INSERT INTO role_capabilities (id, tenant_id, role_id, capability_id, created_at)
SELECT gen_random_uuid(), r.tenant_id, r.id, cap.id, NOW()
FROM roles r
CROSS JOIN access_capabilities cap
WHERE r.tenant_id = '44444444-4444-4444-8444-444444444441'
  AND r.code = 'G3_MANAGER'
  AND cap.code IN (
      'HRM.PERFORMANCE.GOAL.TEAM_MANAGE',
      'HRM.PERFORMANCE.REVIEW.TEAM_MANAGE'
  )
  AND NOT EXISTS (
      SELECT 1 FROM role_capabilities rc
      WHERE rc.tenant_id = r.tenant_id AND rc.role_id = r.id AND rc.capability_id = cap.id
  );

-- Access scope grants for G3_EMPLOYEE
INSERT INTO access_scope_grants (id, tenant_id, role_id, capability_id, scope_type, is_direct_exception, reason, status, created_at)
SELECT gen_random_uuid(), r.tenant_id, r.id, cap.id, 'TENANT', FALSE, 'G3 acceptance employee scope', 'ACTIVE', NOW()
FROM roles r
CROSS JOIN access_capabilities cap
WHERE r.tenant_id = '44444444-4444-4444-8444-444444444441'
  AND r.code = 'G3_EMPLOYEE'
  AND cap.code IN (
      'HRM.PERFORMANCE.GOAL.SELF_VIEW',
      'HRM.PERFORMANCE.GOAL.SELF_UPDATE',
      'HRM.PERFORMANCE.REVIEW.SELF_VIEW',
      'HRM.PERFORMANCE.REVIEW.SELF_SUBMIT'
  )
  AND NOT EXISTS (
      SELECT 1 FROM access_scope_grants g
      WHERE g.tenant_id = r.tenant_id AND g.role_id = r.id AND g.capability_id = cap.id
        AND g.scope_type = 'TENANT' AND g.status = 'ACTIVE'
  );

-- Access scope grants for G3_MANAGER
INSERT INTO access_scope_grants (id, tenant_id, role_id, capability_id, scope_type, is_direct_exception, reason, status, created_at)
SELECT gen_random_uuid(), r.tenant_id, r.id, cap.id, 'TENANT', FALSE, 'G3 acceptance manager scope', 'ACTIVE', NOW()
FROM roles r
CROSS JOIN access_capabilities cap
WHERE r.tenant_id = '44444444-4444-4444-8444-444444444441'
  AND r.code = 'G3_MANAGER'
  AND cap.code IN (
      'HRM.PERFORMANCE.GOAL.TEAM_MANAGE',
      'HRM.PERFORMANCE.REVIEW.TEAM_MANAGE'
  )
  AND NOT EXISTS (
      SELECT 1 FROM access_scope_grants g
      WHERE g.tenant_id = r.tenant_id AND g.role_id = r.id AND g.capability_id = cap.id
        AND g.scope_type = 'TENANT' AND g.status = 'ACTIVE'
  );

-- ----------------------------------------------------------------------------
-- 8. User-role assignments
-- ----------------------------------------------------------------------------
INSERT INTO user_role_assignments (id, tenant_id, user_id, role_id, status, created_at, updated_at)
VALUES
    ('44444444-4444-4444-8444-444444444511', '44444444-4444-4444-8444-444444444441', '44444444-4444-4444-8444-444444444451', '44444444-4444-4444-8444-444444444501', 'ACTIVE', NOW(), NOW()),
    ('44444444-4444-4444-8444-444444444512', '44444444-4444-4444-8444-444444444441', '44444444-4444-4444-8444-444444444452', '44444444-4444-4444-8444-444444444502', 'ACTIVE', NOW(), NOW()),
    ('44444444-4444-4444-8444-444444444513', '44444444-4444-4444-8444-444444444441', '44444444-4444-4444-8444-444444444453', '44444444-4444-4444-8444-444444444503', 'ACTIVE', NOW(), NOW())
ON CONFLICT (id) DO NOTHING;

-- ----------------------------------------------------------------------------
-- 9. Deterministic seeded performance goal for Employee
-- ----------------------------------------------------------------------------
INSERT INTO hr_performance_goals (
    id, tenant_id, person_id, employment_id,
    title, metric, target_value, progress, status,
    starts_on, ends_on, created_at, updated_at
)
VALUES (
    '44444444-4444-4444-8444-444444444521',
    '44444444-4444-4444-8444-444444444441',
    '44444444-4444-4444-8444-444444444471',
    '44444444-4444-4444-8444-444444444481',
    'G3 Acceptance Goal: Q4 Sales Target',
    'Quarterly Revenue (SAR)',
    '500000',
    25,
    'DRAFT',
    CURRENT_DATE,
    CURRENT_DATE + INTERVAL '90 days',
    NOW(),
    NOW()
)
ON CONFLICT (id) DO NOTHING;

-- Clear tenant context
SELECT set_config('app.tenant_id', '', false);
