/**
 * Finance Execution Data
 * ----------------------
 * Business data for Finance execution groups and tasks.
 *
 * IMPORTANT: This file contains ONLY business data.
 * All execution logic (types, calculators, validators, constants)
 * MUST be imported from the shared framework: @/lib/execution
 */

import type {
  GroupStatus,
  TaskType,
  TaskPriority,
  TaskStatus,
} from "../../lib/execution";

// ── Finance-Specific Task Type ──────────────────────────────────────────────

/**
 * Finance Task — Business data for a finance task.
 *
 * NOTE: This is NOT an ExecutionTask. The FinanceExecutionProvider
 * converts this to ExecutionTask when providing data to the framework.
 */
export interface FinanceTask {
  id: string;
  number: string;
  nameAr: string;
  nameEn: string;
  groupCode: string;
  descriptionAr: string;
  descriptionEn: string;
  type: TaskType;
  priority: TaskPriority;
  status: TaskStatus;
  dependencies: string[];
  acceptanceCriteriaAr: string;
  implementationNotesAr: string;
}

// ── Finance Execution Groups ────────────────────────────────────────────────

/**
 * Finance Execution Groups — Business data for group definitions.
 *
 * NOTE: This is NOT an ExecutionGroup[]. The FinanceExecutionProvider
 * converts this to ExecutionGroup[] when providing data to the framework.
 */
export const FINANCE_GROUP_DATA = [
  {
    code: "G0",
    titleAr: "الأساس المالي والهيكل التنظيمي",
    titleEn: "Financial Foundation & Structure",
    purposeAr: "تأسيس دليل الحسابات والفترات المالية وقواعد العمل.",
    purposeEn: "Establish chart of accounts, fiscal periods, and business rules.",
    status: "NOT_STARTED" as GroupStatus,
    dependencies: [],
    canParallelizeWith: [],
    stageReport: null,
  },
  {
    code: "G1",
    titleAr: "المحاسبة الأساسية والقيود اليومية",
    titleEn: "Core Accounting & Journal Entries",
    purposeAr: "تنفيذ القيود اليومية والترحيل وقواعد المحاسبة المزدوجة.",
    purposeEn: "Implement journal entries, posting, and double-entry accounting rules.",
    status: "NOT_STARTED" as GroupStatus,
    dependencies: ["G0"],
    canParallelizeWith: ["G2", "G3"],
    stageReport: null,
  },
  {
    code: "G2",
    titleAr: "حسابات الموردين والمدفوعات",
    titleEn: "Accounts Payable & Payments",
    purposeAr: "تنفيذ فواتير الموردين وأوامر الدفع وجدول الدفعات.",
    purposeEn: "Implement vendor invoices, payment orders, and payment schedules.",
    status: "NOT_STARTED" as GroupStatus,
    dependencies: ["G1"],
    canParallelizeWith: ["G3"],
    stageReport: null,
  },
  {
    code: "G3",
    titleAr: "حسابات العملاء والتحصيل",
    titleEn: "Accounts Receivable & Collections",
    purposeAr: "تنفيذ فواتير العملاء وتحصيل المبالغ وإدارة الائتمان.",
    purposeEn: "Implement customer invoices, collections, and credit management.",
    status: "NOT_STARTED" as GroupStatus,
    dependencies: ["G1"],
    canParallelizeWith: ["G2"],
    stageReport: null,
  },
  {
    code: "G4",
    titleAr: "إدارة الخزينة والبنوك",
    titleEn: "Treasury & Bank Management",
    purposeAr: "تنفيذ إدارة النقدية والتسوية البنكية وتدفقات الأموال.",
    purposeEn: "Implement cash management, bank reconciliation, and fund flows.",
    status: "NOT_STARTED" as GroupStatus,
    dependencies: ["G2", "G3"],
    canParallelizeWith: [],
    stageReport: null,
  },
  {
    code: "G5",
    titleAr: "الأصول الثابتة والإهلاك",
    titleEn: "Fixed Assets & Depreciation",
    purposeAr: "تنفيذ سجل الأصول الثابتة وحساب الإهلاك والأرصدة.",
    purposeEn: "Implement fixed asset register, depreciation calculation, and balances.",
    status: "NOT_STARTED" as GroupStatus,
    dependencies: ["G1"],
    canParallelizeWith: ["G4", "G6"],
    stageReport: null,
  },
  {
    code: "G6",
    titleAr: "الموازنة والتخطيط المالي",
    titleEn: "Budgeting & Financial Planning",
    purposeAr: "تنفيذ خطط الموازنة وتحليل الانحرافات والتقارير.",
    purposeEn: "Implement budget planning, variance analysis, and reporting.",
    status: "NOT_STARTED" as GroupStatus,
    dependencies: ["G1"],
    canParallelizeWith: ["G5"],
    stageReport: null,
  },
  {
    code: "G7",
    titleAr: "التقارير المالية والإغلاق",
    titleEn: "Financial Reporting & Close",
    purposeAr: "تنفيذ الدخل والمصروفات والميزانية العمومية وتدفقات النقدية.",
    purposeEn: "Implement P&L, balance sheet, cash flow statements, and period close.",
    status: "NOT_STARTED" as GroupStatus,
    dependencies: ["G1", "G4", "G5", "G6"],
    canParallelizeWith: [],
    stageReport: null,
  },
];

// ── Finance Tasks ──────────────────────────────────────────────────────────

export const FINANCE_TASKS: FinanceTask[] = [
  // ── G0: Financial Foundation & Structure ──────────────────────────────────
  {
    id: "G0-T01",
    number: "G0-01",
    nameAr: "إنشاء دليل الحسابات الشجري",
    nameEn: "Create hierarchical chart of accounts",
    groupCode: "G0",
    descriptionAr: "تصميم وتنفيذ جدول دليل الحسابات مع دعم التسلسل الهرمي",
    descriptionEn: "Design and implement chart of accounts table with hierarchical support",
    type: "Database",
    priority: "Critical",
    status: "NOT_STARTED",
    dependencies: [],
    acceptanceCriteriaAr: "دليل الحسابات يدعم 7 مستويات هرمية مع كود واسم ثنائي اللغة",
    implementationNotesAr: "جدول finance_accounts مع parent_id وaccount_code فريد",
  },
  {
    id: "G0-T02",
    number: "G0-02",
    nameAr: "إنشاء جدول الفترات المالية",
    nameEn: "Create fiscal periods table",
    groupCode: "G0",
    descriptionAr: "تصميم جدول الفترات المالية مع دعم السنة المالية المخصصة",
    descriptionEn: "Design fiscal periods table with custom fiscal year support",
    type: "Database",
    priority: "Critical",
    status: "NOT_STARTED",
    dependencies: [],
    acceptanceCriteriaAr: "الفترات المالية تدعم أشهر غير متساوية وسنة مالية تبدأ في أي شهر",
    implementationNotesAr: "جدول finance_fiscal_periods مع start_date وend_date وstatus",
  },
  {
    id: "G0-T03",
    number: "G0-03",
    nameAr: "تطبيق قواعد المحاسبة المزدوجة",
    nameEn: "Implement double-entry accounting rules",
    groupCode: "G0",
    descriptionAr: "إنشاء محرك القواعد لضمان توازن القيود اليومية",
    descriptionEn: "Create rules engine to ensure journal entry balance",
    type: "Backend",
    priority: "Critical",
    status: "NOT_STARTED",
    dependencies: ["G0-T01"],
    acceptanceCriteriaAr: "أي قيد غير متوازن يُرفض مع رسالة خطأ واضحة",
    implementationNotesAr: "محرك قواعد في خدمة المحاسبة يتحقق من توازن مدين/دائن",
  },
  {
    id: "G0-T04",
    number: "G0-04",
    nameAr: "إنشاء عملة الشركة والعملات الأجنبية",
    nameEn: "Create company currency and foreign currencies",
    groupCode: "G0",
    descriptionAr: "تنفيذ جدول العملات وأسعار الصرف وقاعدة العملة الأساسية",
    descriptionEn: "Implement currencies table, exchange rates, and base currency rule",
    type: "Database",
    priority: "High",
    status: "NOT_STARTED",
    dependencies: [],
    acceptanceCriteriaAr: "الشركة لها عملة أساسية واحدة وعملات متعددة مع أسعار صرف تاريخية",
    implementationNotesAr: "جداول finance_currencies وfinance_exchange_rates",
  },
  {
    id: "G0-T05",
    number: "G0-05",
    nameAr: "إنشاء تكوين الشركة المالية",
    nameEn: "Create financial company configuration",
    groupCode: "G0",
    descriptionAr: "تنفيذ إعدادات الشركة المالية: عملة أساسية، سنة مالية، قيود تلقائية",
    descriptionEn: "Implement company financial settings: base currency, fiscal year, auto-posting rules",
    type: "Backend",
    priority: "High",
    status: "NOT_STARTED",
    dependencies: ["G0-T01", "G0-T02", "G0-T04"],
    acceptanceCriteriaAr: "تكوين واحد لكل شركة مع جميع الإعدادات المالية الأساسية",
    implementationNotesAr: "جدول finance_company_config مع علاقات للعملة والفترة المالية",
  },

  // ── G1: Core Accounting & Journal Entries ─────────────────────────────────
  {
    id: "G1-T01",
    number: "G1-01",
    nameAr: "إنشاء جدول القيود اليومية",
    nameEn: "Create journal entries table",
    groupCode: "G1",
    descriptionAr: "تنفيذ جدول القيود اليومية مع دعم القيود المجمعة والقيود المرجعية",
    descriptionEn: "Implement journal entries table with batch and reference support",
    type: "Database",
    priority: "Critical",
    status: "NOT_STARTED",
    dependencies: ["G0-T01"],
    acceptanceCriteriaAr: "جدول القيود يدعم القيود العادية والمجمعة والمرجعية",
    implementationNotesAr: "جدول finance_journal_entries مع journal_type وbatch_id",
  },
  {
    id: "G1-T02",
    number: "G1-02",
    nameAr: "تنفيذ خدمة القيود اليومية",
    nameEn: "Implement journal entries service",
    groupCode: "G1",
    descriptionAr: "إنشاء خدمة لإنشاء وتعديل وترحيل القيود اليومية",
    descriptionEn: "Create service for creating, editing, and posting journal entries",
    type: "Backend",
    priority: "Critical",
    status: "NOT_STARTED",
    dependencies: ["G1-T01"],
    acceptanceCriteriaAr: "الخدمة تدعم CRUD الكامل مع التحقق من توازن القيد",
    implementationNotesAr: "JournalEntryService مع createEntry, postEntry, reverseEntry",
  },
  {
    id: "G1-T03",
    number: "G1-03",
    nameAr: "تنفيذ آليات الترحيل الآلي",
    nameEn: "Implement auto-posting mechanisms",
    groupCode: "G1",
    descriptionAr: "تنفيذ آليات الترحيل التلقائي للفواتير والمدفوعات",
    descriptionEn: "Implement auto-posting for invoices and payments",
    type: "Backend",
    priority: "High",
    status: "NOT_STARTED",
    dependencies: ["G1-T02"],
    acceptanceCriteriaAr: "الفواتير والمدفوعات تُرحل تلقائياً عند الإنشاء",
    implementationNotesAr: "AutoPostingService مع قواعد ترحيل لكل نوع معاملة",
  },
  {
    id: "G1-T04",
    number: "G1-04",
    nameAr: "إنشاء دفتر الأستاذ العام",
    nameEn: "Create general ledger",
    groupCode: "G1",
    descriptionAr: "تنفيذ جدول دفتر الأستاذ العام مع أرصدة الحسابات",
    descriptionEn: "Implement general ledger table with account balances",
    type: "Database",
    priority: "Critical",
    status: "NOT_STARTED",
    dependencies: ["G1-T01"],
    acceptanceCriteriaAr: "دفتر الأستاذ يعرض أرصدة الحسابات في الوقت الحقيقي",
    implementationNotesAr: "جدول finance_general_ledger مع Running balance calculation",
  },

  // ── G2: Accounts Payable & Payments ───────────────────────────────────────
  {
    id: "G2-T01",
    number: "G2-01",
    nameAr: "إنشاء جدول فواتير الموردين",
    nameEn: "Create vendor invoices table",
    groupCode: "G2",
    descriptionAr: "تنفيذ جدول فواتير الموردين مع دعم الأقساط والخصومات",
    descriptionEn: "Implement vendor invoices table with installment and discount support",
    type: "Database",
    priority: "Critical",
    status: "NOT_STARTED",
    dependencies: ["G0-T01"],
    acceptanceCriteriaAr: "الفواتير تدعم الأقساط المتعددة والخصومات والعملات الأجنبية",
    implementationNotesAr: "جدول finance_ap_invoices مع payment_terms وdiscount_type",
  },
  {
    id: "G2-T02",
    number: "G2-02",
    nameAr: "تنفيذ خدمة أوامر الدفع",
    nameEn: "Implement payment orders service",
    groupCode: "G2",
    descriptionAr: "إنشاء خدمة لإنشاء وإدارة أوامر الدفع للموردين",
    descriptionEn: "Create service for creating and managing vendor payment orders",
    type: "Backend",
    priority: "Critical",
    status: "NOT_STARTED",
    dependencies: ["G2-T01"],
    acceptanceCriteriaAr: "أوامر الدفع تربط بالفواتير وتُرحل تلقائياً",
    implementationNotesAr: "PaymentOrderService مع createOrder, approveOrder, executeOrder",
  },
  {
    id: "G2-T03",
    number: "G2-03",
    nameAr: "تنفيذ جدول الدفعات",
    nameEn: "Implement payments table",
    groupCode: "G2",
    descriptionAr: "تنفيذ جدول المدفوعات الفعلية مع تتبع طريقة الدفع",
    descriptionEn: "Implement actual payments table with payment method tracking",
    type: "Database",
    priority: "High",
    status: "NOT_STARTED",
    dependencies: ["G2-T02"],
    acceptanceCriteriaAr: "المدفوعات تدعم النقد والتحويل البنكي والشيكات",
    implementationNotesAr: "جدول finance_ap_payments مع payment_method وreference_number",
  },
  {
    id: "G2-T04",
    number: "G2-04",
    nameAr: "تنفيذ تقرير أعمار الذمم للموردين",
    nameEn: "Implement vendor aging report",
    groupCode: "G2",
    descriptionAr: "إنشاء تقرير أعمار الذمم لحسابات الموردين",
    descriptionEn: "Create aging report for accounts payable",
    type: "Report",
    priority: "Medium",
    status: "NOT_STARTED",
    dependencies: ["G2-T01", "G2-T03"],
    acceptanceCriteriaAr: "التقرير يعرض أعمار الذمم في فئات 30/60/90/120 يوم",
    implementationNotesAr: "AgingReportService مع generateAgingReport",
  },

  // ── G3: Accounts Receivable & Collections ─────────────────────────────────
  {
    id: "G3-T01",
    number: "G3-01",
    nameAr: "إنشاء جدول فواتير العملاء",
    nameEn: "Create customer invoices table",
    groupCode: "G3",
    descriptionAr: "تنفيذ جدول فواتير العملاء مع دعم الضرائب والخصومات",
    descriptionEn: "Implement customer invoices table with tax and discount support",
    type: "Database",
    priority: "Critical",
    status: "NOT_STARTED",
    dependencies: ["G0-T01"],
    acceptanceCriteriaAr: "الفواتير تدعم الضرائب المتعددة والخصومات وأقساط الدفع",
    implementationNotesAr: "جدول finance_ar_invoices مع tax_amount وdiscount_amount",
  },
  {
    id: "G3-T02",
    number: "G3-02",
    nameAr: "تنفيذ خدمة التحصيل",
    nameEn: "Implement collections service",
    groupCode: "G3",
    descriptionAr: "إنشاء خدمة لإدارة تحصيل المبالغ من العملاء",
    descriptionEn: "Create service for managing customer payment collections",
    type: "Backend",
    priority: "Critical",
    status: "NOT_STARTED",
    dependencies: ["G3-T01"],
    acceptanceCriteriaAr: "الخدمة تدعم تسجيل المقبوضات وربطها بالفواتير",
    implementationNotesAr: "CollectionsService مع recordPayment, allocatePayment, generateReceipt",
  },
  {
    id: "G3-T03",
    number: "G3-03",
    nameAr: "تنفيذ إدارة الائتمان",
    nameEn: "Implement credit management",
    groupCode: "G3",
    descriptionAr: "تنفيذ حدود الائتمان وتنبيهات انتهاء الائتمان",
    descriptionEn: "Implement credit limits and expiry alerts",
    type: "Backend",
    priority: "High",
    status: "NOT_STARTED",
    dependencies: ["G3-T01"],
    acceptanceCriteriaAr: "الفواتير تُرفض إذا تجاوزت حد الائتمان",
    implementationNotesAr: "CreditService مع checkCreditLimit, suspendCredit, releaseCredit",
  },
  {
    id: "G3-T04",
    number: "G3-04",
    nameAr: "تنفيذ تقرير أعمار الذمم للعملاء",
    nameEn: "Implement customer aging report",
    groupCode: "G3",
    descriptionAr: "إنشاء تقرير أعمار الذمم لحسابات العملاء",
    descriptionEn: "Create aging report for accounts receivable",
    type: "Report",
    priority: "Medium",
    status: "NOT_STARTED",
    dependencies: ["G3-T01", "G3-T02"],
    acceptanceCriteriaAr: "التقرير يعرض أعمار الذمم في فئات 30/60/90/120 يوم",
    implementationNotesAr: "AgingReportService مع generateCustomerAgingReport",
  },

  // ── G4: Treasury & Bank Management ────────────────────────────────────────
  {
    id: "G4-T01",
    number: "G4-01",
    nameAr: "إنشاء جدول الحسابات البنكية",
    nameEn: "Create bank accounts table",
    groupCode: "G4",
    descriptionAr: "تنفيذ جدول الحسابات البنكية مع ربط بالعملات",
    descriptionEn: "Implement bank accounts table with currency linkage",
    type: "Database",
    priority: "Critical",
    status: "NOT_STARTED",
    dependencies: ["G0-T04"],
    acceptanceCriteriaAr: "كل حساب بنكي مرتبط بعملة واحدة ويدعم التوازن الدقيق",
    implementationNotesAr: "جدول finance_bank_accounts مع bank_name وaccount_number",
  },
  {
    id: "G4-T02",
    number: "G4-02",
    nameAr: "تنفيذ التسوية البنكية",
    nameEn: "Implement bank reconciliation",
    groupCode: "G4",
    descriptionAr: "إنشاء نظام التسوية البنكية مع دعم الكشف البنكي",
    descriptionEn: "Create bank reconciliation system with bank statement support",
    type: "Backend",
    priority: "Critical",
    status: "NOT_STARTED",
    dependencies: ["G4-T01"],
    acceptanceCriteriaAr: "التسوية تربط المعاملات البنكية بالقيود الداخلية",
    implementationNotesAr: "ReconciliationService مع importStatement, matchTransaction, reconcile",
  },
  {
    id: "G4-T03",
    number: "G4-03",
    nameAr: "تنفيذ إدارة النقدية",
    nameEn: "Implement cash management",
    groupCode: "G4",
    descriptionAr: "تنفيذ خزينة النقدية مع تتبع الحركات اليومية",
    descriptionEn: "Implement cash vault with daily movement tracking",
    type: "Backend",
    priority: "High",
    status: "NOT_STARTED",
    dependencies: ["G4-T01"],
    acceptanceCriteriaAr: "الخزينة تدعم الإيداعات والسحوبات مع ت平衡 يومي",
    implementationNotesAr: "CashManagementService مع deposit, withdraw, dailyBalance",
  },
  {
    id: "G4-T04",
    number: "G4-04",
    nameAr: "تنفيذ تقرير تدفقات النقدية",
    nameEn: "Implement cash flow report",
    groupCode: "G4",
    descriptionAr: "إنشاء تقرير التدفقات النقدية اليومية والأسبوعية",
    descriptionEn: "Create daily and weekly cash flow report",
    type: "Report",
    priority: "Medium",
    status: "NOT_STARTED",
    dependencies: ["G4-T02", "G4-T03"],
    acceptanceCriteriaAr: "التقرير يعرض التدفقات الداخلة والخارجة والرصيد",
    implementationNotesAr: "CashFlowReportService مع generateDailyFlow, generateWeeklyFlow",
  },

  // ── G5: Fixed Assets & Depreciation ───────────────────────────────────────
  {
    id: "G5-T01",
    number: "G5-01",
    nameAr: "إنشاء سجل الأصول الثابتة",
    nameEn: "Create fixed asset register",
    groupCode: "G5",
    descriptionAr: "تنفيذ جدول الأصول الثابتة مع فئات الإهلاك",
    descriptionEn: "Implement fixed assets table with depreciation categories",
    type: "Database",
    priority: "Critical",
    status: "NOT_STARTED",
    dependencies: ["G0-T01"],
    acceptanceCriteriaAr: "الأصول تدعم الفئات وأسعار الشراء وقيمة الخردة",
    implementationNotesAr: "جدول finance_fixed_assets مع asset_category وsalvage_value",
  },
  {
    id: "G5-T02",
    number: "G5-02",
    nameAr: "تنفيذ محرك الإهلاك",
    nameEn: "Implement depreciation engine",
    groupCode: "G5",
    descriptionAr: "تنفيذ خوارزميات الإهلاك: القسط الثابت والانحداري والوحدات الإنتاجية",
    descriptionEn: "Implement depreciation methods: straight-line, declining balance, units of production",
    type: "Backend",
    priority: "Critical",
    status: "NOT_STARTED",
    dependencies: ["G5-T01"],
    acceptanceCriteriaAr: "المحرك يدعم 3 طرق إهلاك مع ترحيل تلقائي",
    implementationNotesAr: "DepreciationService مع calculateStraightLine, calculateDeclining, calculateUnits",
  },
  {
    id: "G5-T03",
    number: "G5-03",
    nameAr: "تنفيذ جدول الإهلاك المتراكم",
    nameEn: "Implement accumulated depreciation table",
    groupCode: "G5",
    descriptionAr: "تنفيذ جدول الإهلاك المتراكم مع ربط بالأصول",
    descriptionEn: "Implement accumulated depreciation table linked to assets",
    type: "Database",
    priority: "High",
    status: "NOT_STARTED",
    dependencies: ["G5-T01"],
    acceptanceCriteriaAr: "الجدول يتتبع الإهلاك الشهري لكل أصل",
    implementationNotesAr: "جدول finance_accumulated_depreciation مع period وamount",
  },
  {
    id: "G5-T04",
    number: "G5-04",
    nameAr: "تنفيذ إتلاف الأصول",
    nameEn: "Implement asset disposal",
    groupCode: "G5",
    descriptionAr: "تنفيذ عملية إتلاف الأصول مع حساب الربح أو الخسارة",
    descriptionEn: "Implement asset disposal with gain/loss calculation",
    type: "Backend",
    priority: "Medium",
    status: "NOT_STARTED",
    dependencies: ["G5-T01", "G5-T02"],
    acceptanceCriteriaAr: "الإتلاف يحسب الربح/الخسارة ويُرحل تلقائياً",
    implementationNotesAr: "DisposalService مع disposeAsset, calculateGainLoss",
  },

  // ── G6: Budgeting & Financial Planning ────────────────────────────────────
  {
    id: "G6-T01",
    number: "G6-01",
    nameAr: "إنشاء جداول الموازنة",
    nameEn: "Create budget tables",
    groupCode: "G6",
    descriptionAr: "تنفيذ جداول الموازنة مع دعم الموازنة بالحساب والمشروع",
    descriptionEn: "Implement budget tables with account and project budget support",
    type: "Database",
    priority: "Critical",
    status: "NOT_STARTED",
    dependencies: ["G0-T01"],
    acceptanceCriteriaAr: "الموازنة تدعم الحسابات والمشاريع والفترات المالية",
    implementationNotesAr: "جداول finance_budgets وfinance_budget_lines",
  },
  {
    id: "G6-T02",
    number: "G6-02",
    nameAr: "تنفيذ خدمة خطط الموازنة",
    nameEn: "Implement budget planning service",
    groupCode: "G6",
    descriptionAr: "إنشاء خدمة لإنشاء وتعديل خطط الموازنة",
    descriptionEn: "Create service for creating and editing budget plans",
    type: "Backend",
    priority: "Critical",
    status: "NOT_STARTED",
    dependencies: ["G6-T01"],
    acceptanceCriteriaAr: "الخدمة تدعم إنشاء الموازنة وتعديلها واعتمادها",
    implementationNotesAr: "BudgetService مع createPlan, modifyPlan, approvePlan",
  },
  {
    id: "G6-T03",
    number: "G6-03",
    nameAr: "تنفيذ تحليل الانحرافات",
    nameEn: "Implement variance analysis",
    groupCode: "G6",
    descriptionAr: "تنفيذ مقارنة الفعلي مع الموازنة وتحليل الانحرافات",
    descriptionEn: "Implement actual vs budget comparison and variance analysis",
    type: "Backend",
    priority: "High",
    status: "NOT_STARTED",
    dependencies: ["G6-T02"],
    acceptanceCriteriaAr: "تحليل الانحرافات يعرض النسب والمبالغ الدقيقة",
    implementationNotesAr: "VarianceService مع analyzeVariance, getVarianceReport",
  },
  {
    id: "G6-T04",
    number: "G6-04",
    nameAr: "تنفيذ تقرير تنفيذ الموازنة",
    nameEn: "Implement budget execution report",
    groupCode: "G6",
    descriptionAr: "إنشاء تقرير تنفيذ الموازنة مع الرسوم البيانية",
    descriptionEn: "Create budget execution report with charts",
    type: "Report",
    priority: "Medium",
    status: "NOT_STARTED",
    dependencies: ["G6-T03"],
    acceptanceCriteriaAr: "التقرير يعرض نسبة التنفيذ والانحرافات لكل حساب",
    implementationNotesAr: "BudgetReportService مع generateExecutionReport",
  },

  // ── G7: Financial Reporting & Close ───────────────────────────────────────
  {
    id: "G7-T01",
    number: "G7-01",
    nameAr: "تنفيذ قائمة الدخل والمصروفات",
    nameEn: "Implement income statement (P&L)",
    groupCode: "G7",
    descriptionAr: "إنشاء محرك توليد قائمة الدخل والمصروفات",
    descriptionEn: "Create income statement generation engine",
    type: "Backend",
    priority: "Critical",
    status: "NOT_STARTED",
    dependencies: ["G1-T04"],
    acceptanceCriteriaAr: "قائمة الدخل تشمل الإيرادات والمصروفات والربح الصافي",
    implementationNotesAr: "IncomeStatementService مع generateIncomeStatement",
  },
  {
    id: "G7-T02",
    number: "G7-02",
    nameAr: "تنفيذ الميزانية العمومية",
    nameEn: "Implement balance sheet",
    groupCode: "G7",
    descriptionAr: "إنشاء محرك توليد الميزانية العمومية",
    descriptionEn: "Create balance sheet generation engine",
    type: "Backend",
    priority: "Critical",
    status: "NOT_STARTED",
    dependencies: ["G1-T04"],
    acceptanceCriteriaAr: "الميزانية العمومية توازن الأصول بالخصوم وحقوق الملكية",
    implementationNotesAr: "BalanceSheetService مع generateBalanceSheet",
  },
  {
    id: "G7-T03",
    number: "G7-03",
    nameAr: "تنفيذ قائمة التدفقات النقدية",
    nameEn: "Implement cash flow statement",
    groupCode: "G7",
    descriptionAr: "إنشاء محرك توليد قائمة التدفقات النقدية (التشغيلية والاستثمارية والتمويلية)",
    descriptionEn: "Create cash flow statement generation engine (operating, investing, financing)",
    type: "Backend",
    priority: "High",
    status: "NOT_STARTED",
    dependencies: ["G1-T04", "G4-T02"],
    acceptanceCriteriaAr: "قائمة التدفقات تشمل الأنشطة التشغيلية والاستثمارية والتمويلية",
    implementationNotesAr: "CashFlowStatementService مع generateCashFlowStatement",
  },
  {
    id: "G7-T04",
    number: "G7-04",
    nameAr: "تنفيذ عملية الإغلاق الدوري",
    nameEn: "Implement period close process",
    groupCode: "G7",
    descriptionAr: "تنفيذ عملية إغلاق الفترة المالية مع ترحيل الأرباح المحتجزة",
    descriptionEn: "Implement fiscal period close with retained earnings posting",
    type: "Backend",
    priority: "Critical",
    status: "NOT_STARTED",
    dependencies: ["G7-T01", "G7-T02"],
    acceptanceCriteriaAr: "الإغلاق يُرحل أرباح الفترة للأرباح المحتجزة ويقفل الفترة",
    implementationNotesAr: "PeriodCloseService مع closePeriod, postRetainedEarnings, lockPeriod",
  },
];
