ALTER TABLE users ADD COLUMN platform_admin BOOLEAN NOT NULL DEFAULT FALSE;

ALTER TABLE tenants ADD COLUMN legal_name VARCHAR(250);
ALTER TABLE tenants ADD COLUMN billing_email VARCHAR(255);
ALTER TABLE tenants ADD COLUMN country_code VARCHAR(2);
ALTER TABLE tenants ADD COLUMN locale VARCHAR(10) NOT NULL DEFAULT 'ar-SA';
ALTER TABLE tenants ADD COLUMN timezone VARCHAR(64) NOT NULL DEFAULT 'Asia/Riyadh';
ALTER TABLE tenants ADD COLUMN currency_code VARCHAR(3) NOT NULL DEFAULT 'SAR';
ALTER TABLE tenants ADD COLUMN trial_ends_at TIMESTAMP WITH TIME ZONE;
ALTER TABLE tenants ADD COLUMN suspension_reason VARCHAR(500);

ALTER TABLE tenants DROP CONSTRAINT ck_tenants_status;
ALTER TABLE tenants ADD CONSTRAINT ck_tenants_status
    CHECK (status IN ('PENDING', 'TRIAL', 'ACTIVE', 'PAST_DUE', 'SUSPENDED', 'CANCELLED', 'ARCHIVED'));
