-- ============================================================
-- V20260908_1 — HRM-G1: recruitment & onboarding schema (design §5.2)
-- ============================================================
-- Append-only Flyway migration (no edits to prior migrations; no down-script).
--
-- Conventions follow the G0 baseline (V20260905_16 pattern):
--   * id UUID NOT NULL DEFAULT gen_random_uuid()  (time-ordered v7-style ids
--     are generated by the application layer; the DB default is a fallback)
--   * tenant_id UUID NOT NULL REFERENCES tenants(id)
--   * created_at / updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
--   * version INTEGER NOT NULL DEFAULT 0 for optimistic locking on aggregates
--   * UNIQUE (id, tenant_id) on parent tables so children can enforce
--     tenant congruence via composite FKs (child rows cannot point at a
--     parent row of another tenant)
--   * state columns VARCHAR + CHECK constraints mirroring the G1-T1 domain
--     enums (single source of truth for values; app layer owns transitions)
--
-- RLS (ENABLE + FORCE + tenant_isolation policy) is applied in
-- V20260908_2 so this file stays schema-only.
-- ============================================================

-- ------------------------------------------------------------
-- 1. hr_job_openings — aggregate root (§5.1/§6.1)
-- ------------------------------------------------------------
CREATE TABLE hr_job_openings (
    id                    UUID           NOT NULL DEFAULT gen_random_uuid(),
    tenant_id             UUID           NOT NULL REFERENCES tenants(id),
    opening_number        VARCHAR(32)    NOT NULL,
    job_id                UUID           NOT NULL REFERENCES hr_jobs(id),
    job_version_id        UUID           REFERENCES hr_job_versions(id),
    org_unit_id           UUID           NOT NULL REFERENCES hr_org_units(id),
    position_id           UUID           REFERENCES hr_positions(id),
    state                 VARCHAR(20)    NOT NULL DEFAULT 'DRAFT',
    requested_headcount   INTEGER        NOT NULL,
    filled_headcount      INTEGER        NOT NULL DEFAULT 0,
    compliance_decision   VARCHAR(32),
    compliance_decided_at TIMESTAMPTZ,
    opens_at              TIMESTAMPTZ,
    closes_at             TIMESTAMPTZ,
    version               INTEGER        NOT NULL DEFAULT 0,
    created_at            TIMESTAMPTZ    NOT NULL DEFAULT NOW(),
    updated_at            TIMESTAMPTZ    NOT NULL DEFAULT NOW(),
    CONSTRAINT pk_hr_job_openings PRIMARY KEY (id),
    CONSTRAINT uq_hr_job_openings_id_tenant UNIQUE (id, tenant_id),
    CONSTRAINT uq_hr_job_openings_number UNIQUE (tenant_id, opening_number),
    CONSTRAINT fk_hr_job_openings_job FOREIGN KEY (job_id)
        REFERENCES hr_jobs (id),
    CONSTRAINT fk_hr_job_openings_job_version FOREIGN KEY (job_version_id)
        REFERENCES hr_job_versions (id),
    CONSTRAINT fk_hr_job_openings_org_unit FOREIGN KEY (org_unit_id)
        REFERENCES hr_org_units (id),
    CONSTRAINT fk_hr_job_openings_position FOREIGN KEY (position_id)
        REFERENCES hr_positions (id),
    CONSTRAINT ck_hr_job_openings_state CHECK (
        state IN ('DRAFT','PENDING_APPROVAL','OPEN','PAUSED','CLOSED','CANCELLED')),
    CONSTRAINT ck_hr_job_openings_requested_headcount CHECK (requested_headcount >= 1),
    CONSTRAINT ck_hr_job_openings_filled_headcount CHECK (filled_headcount >= 0),
    CONSTRAINT ck_hr_job_openings_publish_window CHECK (
        opens_at IS NULL OR closes_at IS NULL OR closes_at >= opens_at)
);

-- ------------------------------------------------------------
-- 2. hr_job_opening_periods — opening lifecycle history (§5.2/§6.1)
-- ------------------------------------------------------------
CREATE TABLE hr_job_opening_periods (
    id          UUID           NOT NULL DEFAULT gen_random_uuid(),
    tenant_id   UUID           NOT NULL REFERENCES tenants(id),
    opening_id  UUID           NOT NULL,
    state       VARCHAR(20)    NOT NULL,
    from_at     TIMESTAMPTZ    NOT NULL DEFAULT NOW(),
    to_at       TIMESTAMPTZ,
    actor_id    UUID,
    reason_code VARCHAR(80),
    reason_text VARCHAR(500),
    created_at  TIMESTAMPTZ    NOT NULL DEFAULT NOW(),
    CONSTRAINT pk_hr_job_opening_periods PRIMARY KEY (id),
    CONSTRAINT fk_hr_job_opening_periods_opening FOREIGN KEY (opening_id, tenant_id)
        REFERENCES hr_job_openings (id, tenant_id),
    CONSTRAINT ck_hr_job_opening_periods_state CHECK (
        state IN ('DRAFT','PENDING_APPROVAL','OPEN','PAUSED','CLOSED','CANCELLED'))
);

CREATE INDEX idx_hr_job_opening_periods_opening
    ON hr_job_opening_periods (tenant_id, opening_id, from_at);

-- ------------------------------------------------------------
-- 3. hr_candidates — aggregate root, recruitment-scoped identity (§5.1/§10)
--    NOT hr_people. Contact PII minimized: ciphertext + normalized-hash only.
-- ------------------------------------------------------------
CREATE TABLE hr_candidates (
    id                                UUID           NOT NULL DEFAULT gen_random_uuid(),
    tenant_id                         UUID           NOT NULL REFERENCES tenants(id),
    candidate_number                  VARCHAR(32)    NOT NULL,
    display_name                      VARCHAR(400)   NOT NULL,
    contact_email_ciphertext          VARCHAR(500),
    contact_email_hash                VARCHAR(128),
    contact_phone_ciphertext          VARCHAR(500),
    contact_phone_hash                VARCHAR(128),
    pool_state                        VARCHAR(20)    NOT NULL DEFAULT 'ACTIVE',
    compensation_expectations_cipher  VARCHAR(500),
    attachments                       JSONB          NOT NULL DEFAULT '[]'::jsonb,
    version                           INTEGER        NOT NULL DEFAULT 0,
    created_at                        TIMESTAMPTZ    NOT NULL DEFAULT NOW(),
    updated_at                        TIMESTAMPTZ    NOT NULL DEFAULT NOW(),
    CONSTRAINT pk_hr_candidates PRIMARY KEY (id),
    CONSTRAINT uq_hr_candidates_id_tenant UNIQUE (id, tenant_id),
    CONSTRAINT uq_hr_candidates_number UNIQUE (tenant_id, candidate_number),
    CONSTRAINT ck_hr_candidates_pool_state CHECK (
        pool_state IN ('ACTIVE','HIRED','WITHDRAWN','ARCHIVED'))
);

CREATE INDEX idx_hr_candidates_email_hash
    ON hr_candidates (tenant_id, contact_email_hash);
CREATE INDEX idx_hr_candidates_phone_hash
    ON hr_candidates (tenant_id, contact_phone_hash);

-- ------------------------------------------------------------
-- 4. hr_applications — Candidate↔Opening edge (§5.1/§6.2)
--    ONE active application per (candidate, opening) via partial unique index
--    (added after table creation).
-- ------------------------------------------------------------
CREATE TABLE hr_applications (
    id             UUID           NOT NULL DEFAULT gen_random_uuid(),
    tenant_id      UUID           NOT NULL REFERENCES tenants(id),
    candidate_id   UUID           NOT NULL,
    job_opening_id UUID           NOT NULL,
    state          VARCHAR(20)    NOT NULL DEFAULT 'APPLIED',
    applied_at     TIMESTAMPTZ    NOT NULL DEFAULT NOW(),
    version        INTEGER        NOT NULL DEFAULT 0,
    created_at     TIMESTAMPTZ    NOT NULL DEFAULT NOW(),
    updated_at     TIMESTAMPTZ    NOT NULL DEFAULT NOW(),
    CONSTRAINT pk_hr_applications PRIMARY KEY (id),
    CONSTRAINT uq_hr_applications_id_tenant UNIQUE (id, tenant_id),
    CONSTRAINT fk_hr_applications_candidate FOREIGN KEY (candidate_id, tenant_id)
        REFERENCES hr_candidates (id, tenant_id),
    CONSTRAINT fk_hr_applications_opening FOREIGN KEY (job_opening_id, tenant_id)
        REFERENCES hr_job_openings (id, tenant_id),
    CONSTRAINT ck_hr_applications_state CHECK (
        state IN ('APPLIED','SCREENING','INTERVIEW','OFFER','HIRED','REJECTED','WITHDRAWN'))
);

CREATE UNIQUE INDEX uq_hr_applications_one_active_per_opening
    ON hr_applications (tenant_id, candidate_id, job_opening_id)
    WHERE state NOT IN ('REJECTED', 'WITHDRAWN', 'HIRED');

CREATE INDEX idx_hr_applications_candidate
    ON hr_applications (tenant_id, candidate_id);
CREATE INDEX idx_hr_applications_opening
    ON hr_applications (tenant_id, job_opening_id);

-- ------------------------------------------------------------
-- 5. hr_application_stage_periods — application lifecycle history (§5.2)
-- ------------------------------------------------------------
CREATE TABLE hr_application_stage_periods (
    id             UUID           NOT NULL DEFAULT gen_random_uuid(),
    tenant_id      UUID           NOT NULL REFERENCES tenants(id),
    application_id UUID           NOT NULL,
    stage          VARCHAR(20)    NOT NULL,
    from_at        TIMESTAMPTZ    NOT NULL DEFAULT NOW(),
    to_at          TIMESTAMPTZ,
    actor_id       UUID,
    reason_code    VARCHAR(80),
    reason_text    VARCHAR(500),
    created_at     TIMESTAMPTZ    NOT NULL DEFAULT NOW(),
    CONSTRAINT pk_hr_application_stage_periods PRIMARY KEY (id),
    CONSTRAINT fk_hr_application_stage_periods_application FOREIGN KEY (application_id, tenant_id)
        REFERENCES hr_applications (id, tenant_id),
    CONSTRAINT ck_hr_application_stage_periods_stage CHECK (
        stage IN ('APPLIED','SCREENING','INTERVIEW','OFFER','HIRED','REJECTED','WITHDRAWN'))
);

CREATE INDEX idx_hr_application_stage_periods_application
    ON hr_application_stage_periods (tenant_id, application_id, from_at);

-- ------------------------------------------------------------
-- 6. hr_interviews — child of HrApplication (§5.1)
-- ------------------------------------------------------------
CREATE TABLE hr_interviews (
    id              UUID           NOT NULL DEFAULT gen_random_uuid(),
    tenant_id       UUID           NOT NULL REFERENCES tenants(id),
    application_id  UUID           NOT NULL,
    planned_at      TIMESTAMPTZ    NOT NULL,
    duration_minutes INTEGER,
    mode            VARCHAR(10)    NOT NULL,
    state           VARCHAR(12)    NOT NULL DEFAULT 'SCHEDULED',
    outcome         VARCHAR(10),
    version         INTEGER        NOT NULL DEFAULT 0,
    created_at      TIMESTAMPTZ    NOT NULL DEFAULT NOW(),
    updated_at      TIMESTAMPTZ    NOT NULL DEFAULT NOW(),
    CONSTRAINT pk_hr_interviews PRIMARY KEY (id),
    CONSTRAINT uq_hr_interviews_id_tenant UNIQUE (id, tenant_id),
    CONSTRAINT fk_hr_interviews_application FOREIGN KEY (application_id, tenant_id)
        REFERENCES hr_applications (id, tenant_id),
    CONSTRAINT ck_hr_interviews_mode CHECK (mode IN ('ONSITE','REMOTE','PHONE')),
    CONSTRAINT ck_hr_interviews_state CHECK (
        state IN ('SCHEDULED','DONE','CANCELLED','NO_SHOW')),
    CONSTRAINT ck_hr_interviews_outcome CHECK (outcome IS NULL OR outcome IN ('PASSED','FAILED')),
    CONSTRAINT ck_hr_interviews_duration CHECK (duration_minutes IS NULL OR duration_minutes > 0)
);

CREATE INDEX idx_hr_interviews_application_planned
    ON hr_interviews (tenant_id, application_id, planned_at);

-- ------------------------------------------------------------
-- 7. hr_interview_participants — panel (tenant users via IAM) (§5.1)
-- ------------------------------------------------------------
CREATE TABLE hr_interview_participants (
    id           UUID           NOT NULL DEFAULT gen_random_uuid(),
    tenant_id    UUID           NOT NULL REFERENCES tenants(id),
    interview_id UUID           NOT NULL,
    user_id      UUID           NOT NULL,
    created_at   TIMESTAMPTZ    NOT NULL DEFAULT NOW(),
    CONSTRAINT pk_hr_interview_participants PRIMARY KEY (id),
    CONSTRAINT uq_hr_interview_participants UNIQUE (interview_id, user_id),
    CONSTRAINT fk_hr_interview_participants_interview FOREIGN KEY (interview_id, tenant_id)
        REFERENCES hr_interviews (id, tenant_id)
);

-- ------------------------------------------------------------
-- 8. hr_interview_feedback — structured scorecard per participant (§5.1/§13.4)
-- ------------------------------------------------------------
CREATE TABLE hr_interview_feedback (
    id             UUID           NOT NULL DEFAULT gen_random_uuid(),
    tenant_id      UUID           NOT NULL REFERENCES tenants(id),
    interview_id   UUID           NOT NULL,
    participant_id UUID           NOT NULL,
    scorecard      JSONB          NOT NULL,
    outcome        VARCHAR(10),
    version        INTEGER        NOT NULL DEFAULT 1,
    created_at     TIMESTAMPTZ    NOT NULL DEFAULT NOW(),
    updated_at     TIMESTAMPTZ    NOT NULL DEFAULT NOW(),
    CONSTRAINT pk_hr_interview_feedback PRIMARY KEY (id),
    CONSTRAINT uq_hr_interview_feedback UNIQUE (interview_id, participant_id),
    CONSTRAINT fk_hr_interview_feedback_interview FOREIGN KEY (interview_id, tenant_id)
        REFERENCES hr_interviews (id, tenant_id),
    CONSTRAINT ck_hr_interview_feedback_outcome CHECK (
        outcome IS NULL OR outcome IN ('PASSED','FAILED'))
);

-- ------------------------------------------------------------
-- 9. hr_offers — child of HrApplication (§5.1/§6.3)
-- ------------------------------------------------------------
CREATE TABLE hr_offers (
    id             UUID           NOT NULL DEFAULT gen_random_uuid(),
    tenant_id      UUID           NOT NULL REFERENCES tenants(id),
    application_id UUID           NOT NULL,
    offer_number   VARCHAR(32)    NOT NULL,
    state          VARCHAR(20)    NOT NULL DEFAULT 'DRAFT',
    expires_at     TIMESTAMPTZ,
    position_id    UUID           REFERENCES hr_positions(id),
    version        INTEGER        NOT NULL DEFAULT 0,
    created_at     TIMESTAMPTZ    NOT NULL DEFAULT NOW(),
    updated_at     TIMESTAMPTZ    NOT NULL DEFAULT NOW(),
    CONSTRAINT pk_hr_offers PRIMARY KEY (id),
    CONSTRAINT uq_hr_offers_id_tenant UNIQUE (id, tenant_id),
    CONSTRAINT uq_hr_offers_number UNIQUE (tenant_id, offer_number),
    CONSTRAINT fk_hr_offers_application FOREIGN KEY (application_id, tenant_id)
        REFERENCES hr_applications (id, tenant_id),
    CONSTRAINT fk_hr_offers_position FOREIGN KEY (position_id)
        REFERENCES hr_positions (id),
    CONSTRAINT ck_hr_offers_state CHECK (
        state IN ('DRAFT','PENDING_APPROVAL','EXTENDED','ACCEPTED','DECLINED','EXPIRED','WITHDRAWN'))
);

CREATE INDEX idx_hr_offers_application
    ON hr_offers (tenant_id, application_id, state);

-- ------------------------------------------------------------
-- 10. hr_offer_versions — immutable version rows (§5.1/§5.2)
--     Edits after EXTENDED create a NEW version (never in-place mutation).
-- ------------------------------------------------------------
CREATE TABLE hr_offer_versions (
    id               UUID           NOT NULL DEFAULT gen_random_uuid(),
    tenant_id        UUID           NOT NULL REFERENCES tenants(id),
    offer_id         UUID           NOT NULL,
    version_number   INTEGER        NOT NULL,
    contract_terms   JSONB          NOT NULL DEFAULT '{}'::jsonb,
    compensation     JSONB          NOT NULL DEFAULT '{}'::jsonb,
    created_by       UUID,
    created_at       TIMESTAMPTZ    NOT NULL DEFAULT NOW(),
    CONSTRAINT pk_hr_offer_versions PRIMARY KEY (id),
    CONSTRAINT uq_hr_offer_versions UNIQUE (offer_id, version_number),
    CONSTRAINT fk_hr_offer_versions_offer FOREIGN KEY (offer_id, tenant_id)
        REFERENCES hr_offers (id, tenant_id),
    CONSTRAINT ck_hr_offer_versions_number CHECK (version_number >= 1)
);

CREATE INDEX idx_hr_offer_versions_offer
    ON hr_offer_versions (tenant_id, offer_id);

-- ------------------------------------------------------------
-- 11. hr_onboarding_checklist_templates — versioned, tenant-scoped (§5.1)
-- ------------------------------------------------------------
CREATE TABLE hr_onboarding_checklist_templates (
    id         UUID           NOT NULL DEFAULT gen_random_uuid(),
    tenant_id  UUID           NOT NULL REFERENCES tenants(id),
    code       VARCHAR(32)    NOT NULL,
    name       VARCHAR(200)   NOT NULL,
    version    INTEGER        NOT NULL DEFAULT 1,
    definition JSONB          NOT NULL DEFAULT '[]'::jsonb,
    is_active  BOOLEAN        NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ    NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ    NOT NULL DEFAULT NOW(),
    CONSTRAINT pk_hr_onboarding_checklist_templates PRIMARY KEY (id),
    CONSTRAINT uq_hr_onboarding_checklist_templates_id_tenant UNIQUE (id, tenant_id),
    CONSTRAINT uq_hr_onboarding_checklist_templates_code UNIQUE (tenant_id, code),
    CONSTRAINT ck_hr_onboarding_checklist_templates_version CHECK (version >= 1)
);

-- ------------------------------------------------------------
-- 12. hr_onboarding_plans — aggregate root (§5.1/§6.4)
--     COMPLETED is derived (no OPEN tasks remain); never set manually.
-- ------------------------------------------------------------
CREATE TABLE hr_onboarding_plans (
    id                     UUID           NOT NULL DEFAULT gen_random_uuid(),
    tenant_id              UUID           NOT NULL REFERENCES tenants(id),
    plan_number            VARCHAR(32)    NOT NULL,
    employment_id          UUID           NOT NULL,
    checklist_template_id  UUID           REFERENCES hr_onboarding_checklist_templates(id),
    state                  VARCHAR(12)    NOT NULL DEFAULT 'ACTIVE',
    cancelled_reason_code  VARCHAR(80),
    version                INTEGER        NOT NULL DEFAULT 0,
    created_at             TIMESTAMPTZ    NOT NULL DEFAULT NOW(),
    updated_at             TIMESTAMPTZ    NOT NULL DEFAULT NOW(),
    CONSTRAINT pk_hr_onboarding_plans PRIMARY KEY (id),
    CONSTRAINT uq_hr_onboarding_plans_id_tenant UNIQUE (id, tenant_id),
    CONSTRAINT uq_hr_onboarding_plans_number UNIQUE (tenant_id, plan_number),
    CONSTRAINT fk_hr_onboarding_plans_employment FOREIGN KEY (employment_id)
        REFERENCES hr_employees (id),
    CONSTRAINT fk_hr_onboarding_plans_template FOREIGN KEY (checklist_template_id, tenant_id)
        REFERENCES hr_onboarding_checklist_templates (id, tenant_id),
    CONSTRAINT ck_hr_onboarding_plans_state CHECK (
        state IN ('ACTIVE','COMPLETED','CANCELLED'))
);

CREATE INDEX idx_hr_onboarding_plans_employment
    ON hr_onboarding_plans (tenant_id, employment_id);

-- ------------------------------------------------------------
-- 13. hr_hire_conversions — terminal-state ledger (§5.1/§7)
--     Written in the SAME transaction as every conversion output;
--     UK(tenant_id, offer_id) makes replays idempotent.
-- ------------------------------------------------------------
CREATE TABLE hr_hire_conversions (
    id                      UUID           NOT NULL DEFAULT gen_random_uuid(),
    tenant_id               UUID           NOT NULL REFERENCES tenants(id),
    offer_id                UUID           NOT NULL,
    application_id          UUID           NOT NULL,
    conversion_state        VARCHAR(20)    NOT NULL DEFAULT 'IN_PROGRESS',
    person_id               UUID,
    employment_id           UUID           REFERENCES hr_employees(id),
    assignment_id           UUID           REFERENCES hr_employee_assignments(id),
    contract_id             UUID,
    compensation_package_id UUID,
    onboarding_plan_id      UUID,
    failure_reason_code     VARCHAR(80),
    completed_at            TIMESTAMPTZ,
    created_at              TIMESTAMPTZ    NOT NULL DEFAULT NOW(),
    updated_at              TIMESTAMPTZ    NOT NULL DEFAULT NOW(),
    CONSTRAINT pk_hr_hire_conversions PRIMARY KEY (id),
    CONSTRAINT uq_hr_hire_conversions_offer UNIQUE (tenant_id, offer_id),
    CONSTRAINT fk_hr_hire_conversions_offer FOREIGN KEY (offer_id, tenant_id)
        REFERENCES hr_offers (id, tenant_id),
    CONSTRAINT fk_hr_hire_conversions_application FOREIGN KEY (application_id, tenant_id)
        REFERENCES hr_applications (id, tenant_id),
    CONSTRAINT fk_hr_hire_conversions_plan FOREIGN KEY (onboarding_plan_id, tenant_id)
        REFERENCES hr_onboarding_plans (id, tenant_id),
    CONSTRAINT fk_hr_hire_conversions_person FOREIGN KEY (person_id, tenant_id)
        REFERENCES hr_people (tenant_id, id),
    CONSTRAINT fk_hr_hire_conversions_contract FOREIGN KEY (contract_id, tenant_id)
        REFERENCES hr_employment_contracts (id, tenant_id),
    CONSTRAINT fk_hr_hire_conversions_comp_package FOREIGN KEY (compensation_package_id, tenant_id)
        REFERENCES hr_compensation_packages (id, tenant_id),
    CONSTRAINT ck_hr_hire_conversions_state CHECK (
        conversion_state IN ('IN_PROGRESS','COMPLETE','FAILED'))
);

-- ------------------------------------------------------------
-- 14. hr_onboarding_checklists — materialized template instance (§5.1)
--     Template edits never mutate existing instances (snapshot semantics).
-- ------------------------------------------------------------
CREATE TABLE hr_onboarding_checklists (
    id               UUID           NOT NULL DEFAULT gen_random_uuid(),
    tenant_id        UUID           NOT NULL REFERENCES tenants(id),
    plan_id          UUID           NOT NULL,
    template_id      UUID           REFERENCES hr_onboarding_checklist_templates(id),
    template_code    VARCHAR(32),
    template_version INTEGER,
    created_at       TIMESTAMPTZ    NOT NULL DEFAULT NOW(),
    CONSTRAINT pk_hr_onboarding_checklists PRIMARY KEY (id),
    CONSTRAINT uq_hr_onboarding_checklists_id_tenant UNIQUE (id, tenant_id),
    CONSTRAINT fk_hr_onboarding_checklists_plan FOREIGN KEY (plan_id, tenant_id)
        REFERENCES hr_onboarding_plans (id, tenant_id),
    CONSTRAINT fk_hr_onboarding_checklists_template FOREIGN KEY (template_id, tenant_id)
        REFERENCES hr_onboarding_checklist_templates (id, tenant_id)
);

CREATE INDEX idx_hr_onboarding_checklists_plan
    ON hr_onboarding_checklists (tenant_id, plan_id);

-- ------------------------------------------------------------
-- 15. hr_onboarding_tasks — child of plan/checklist (§5.1/§6.4)
-- ------------------------------------------------------------
CREATE TABLE hr_onboarding_tasks (
    id               UUID           NOT NULL DEFAULT gen_random_uuid(),
    tenant_id        UUID           NOT NULL REFERENCES tenants(id),
    plan_id          UUID           NOT NULL,
    checklist_id     UUID           NOT NULL,
    seq              INTEGER        NOT NULL DEFAULT 1,
    title            VARCHAR(200)   NOT NULL,
    state            VARCHAR(10)    NOT NULL DEFAULT 'OPEN',
    assignee_user_id UUID,
    due_at           TIMESTAMPTZ,
    reason_code      VARCHAR(80),
    resolved_at      TIMESTAMPTZ,
    created_at       TIMESTAMPTZ    NOT NULL DEFAULT NOW(),
    updated_at       TIMESTAMPTZ    NOT NULL DEFAULT NOW(),
    CONSTRAINT pk_hr_onboarding_tasks PRIMARY KEY (id),
    CONSTRAINT fk_hr_onboarding_tasks_plan FOREIGN KEY (plan_id, tenant_id)
        REFERENCES hr_onboarding_plans (id, tenant_id),
    CONSTRAINT fk_hr_onboarding_tasks_checklist FOREIGN KEY (checklist_id, tenant_id)
        REFERENCES hr_onboarding_checklists (id, tenant_id),
    CONSTRAINT ck_hr_onboarding_tasks_state CHECK (state IN ('OPEN','DONE','WAIVED')),
    CONSTRAINT ck_hr_onboarding_tasks_seq CHECK (seq >= 1)
);

CREATE INDEX idx_hr_onboarding_tasks_plan_state
    ON hr_onboarding_tasks (tenant_id, plan_id, state);

