-- G7 correctness hardening — separate row version from delta cursor.
--
-- sync_version remains the optimistic-concurrency version of one CRM row.
-- mobile_change_log.change_id is the monotonic tenant-scoped delta cursor.

CREATE TABLE mobile_change_log (
    change_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id UUID NOT NULL REFERENCES tenants(id),
    entity_type VARCHAR(40) NOT NULL CHECK (entity_type IN (
        'account','contact','lead','opportunity','task','note','activity'
    )),
    entity_id UUID NOT NULL,
    entity_version BIGINT NOT NULL,
    change_operation VARCHAR(10) NOT NULL CHECK (change_operation IN ('INSERT','UPDATE','DELETE')),
    changed_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW()
);

CREATE INDEX idx_mobile_change_log_tenant_entity_cursor
    ON mobile_change_log (tenant_id, entity_type, change_id);
CREATE INDEX idx_mobile_change_log_tenant_record
    ON mobile_change_log (tenant_id, entity_type, entity_id, change_id DESC);

ALTER TABLE mobile_change_log ENABLE ROW LEVEL SECURITY;
ALTER TABLE mobile_change_log FORCE ROW LEVEL SECURITY;

CREATE POLICY mobile_change_log_tenant_isolation ON mobile_change_log
    USING (tenant_id = current_setting('app.tenant_id', true)::UUID)
    WITH CHECK (tenant_id = current_setting('app.tenant_id', true)::UUID);

-- Bootstrap every row that existed before the lossless cursor was introduced.
-- Rows at sync_version=0 are deliberately included; this fixes the initial-sync gap.
INSERT INTO mobile_change_log (tenant_id, entity_type, entity_id, entity_version, change_operation, changed_at)
SELECT tenant_id, 'account', id, sync_version, 'INSERT', COALESCE(updated_at, NOW()) FROM crm_accounts;
INSERT INTO mobile_change_log (tenant_id, entity_type, entity_id, entity_version, change_operation, changed_at)
SELECT tenant_id, 'contact', id, sync_version, 'INSERT', COALESCE(updated_at, NOW()) FROM crm_contacts;
INSERT INTO mobile_change_log (tenant_id, entity_type, entity_id, entity_version, change_operation, changed_at)
SELECT tenant_id, 'lead', id, sync_version, 'INSERT', COALESCE(updated_at, NOW()) FROM crm_leads;
INSERT INTO mobile_change_log (tenant_id, entity_type, entity_id, entity_version, change_operation, changed_at)
SELECT tenant_id, 'opportunity', id, sync_version, 'INSERT', COALESCE(updated_at, NOW()) FROM crm_opportunities;
INSERT INTO mobile_change_log (tenant_id, entity_type, entity_id, entity_version, change_operation, changed_at)
SELECT tenant_id, 'task', id, sync_version, 'INSERT', COALESCE(updated_at, NOW()) FROM crm_tasks;
INSERT INTO mobile_change_log (tenant_id, entity_type, entity_id, entity_version, change_operation, changed_at)
SELECT tenant_id, 'note', id, sync_version, 'INSERT', COALESCE(updated_at, NOW()) FROM crm_notes;
INSERT INTO mobile_change_log (tenant_id, entity_type, entity_id, entity_version, change_operation, changed_at)
SELECT tenant_id, 'activity', id, sync_version, 'INSERT', COALESCE(updated_at, NOW()) FROM crm_activities;

CREATE OR REPLACE FUNCTION fn_mobile_capture_change()
RETURNS TRIGGER AS $$
DECLARE
    v_tenant UUID;
    v_entity UUID;
    v_version BIGINT;
BEGIN
    IF TG_OP = 'DELETE' THEN
        v_tenant := OLD.tenant_id;
        v_entity := OLD.id;
        v_version := OLD.sync_version;
    ELSE
        v_tenant := NEW.tenant_id;
        v_entity := NEW.id;
        v_version := NEW.sync_version;
    END IF;

    INSERT INTO mobile_change_log
        (tenant_id, entity_type, entity_id, entity_version, change_operation, changed_at)
    VALUES
        (v_tenant, TG_ARGV[0], v_entity, v_version, TG_OP, NOW());

    RETURN CASE WHEN TG_OP = 'DELETE' THEN OLD ELSE NEW END;
END;
$$ LANGUAGE plpgsql;

-- V20260812_2 missed activity row-versioning. Repair it without mutating applied history.
CREATE INDEX IF NOT EXISTS idx_activities_sync_version ON crm_activities(sync_version);
DROP TRIGGER IF EXISTS trg_activities_sync_version ON crm_activities;
CREATE TRIGGER trg_activities_sync_version
    BEFORE UPDATE ON crm_activities
    FOR EACH ROW EXECUTE FUNCTION fn_update_sync_version();

DROP TRIGGER IF EXISTS trg_accounts_mobile_change ON crm_accounts;
CREATE TRIGGER trg_accounts_mobile_change AFTER INSERT OR UPDATE OR DELETE ON crm_accounts
    FOR EACH ROW EXECUTE FUNCTION fn_mobile_capture_change('account');

DROP TRIGGER IF EXISTS trg_contacts_mobile_change ON crm_contacts;
CREATE TRIGGER trg_contacts_mobile_change AFTER INSERT OR UPDATE OR DELETE ON crm_contacts
    FOR EACH ROW EXECUTE FUNCTION fn_mobile_capture_change('contact');

DROP TRIGGER IF EXISTS trg_leads_mobile_change ON crm_leads;
CREATE TRIGGER trg_leads_mobile_change AFTER INSERT OR UPDATE OR DELETE ON crm_leads
    FOR EACH ROW EXECUTE FUNCTION fn_mobile_capture_change('lead');

DROP TRIGGER IF EXISTS trg_opportunities_mobile_change ON crm_opportunities;
CREATE TRIGGER trg_opportunities_mobile_change AFTER INSERT OR UPDATE OR DELETE ON crm_opportunities
    FOR EACH ROW EXECUTE FUNCTION fn_mobile_capture_change('opportunity');

DROP TRIGGER IF EXISTS trg_tasks_mobile_change ON crm_tasks;
CREATE TRIGGER trg_tasks_mobile_change AFTER INSERT OR UPDATE OR DELETE ON crm_tasks
    FOR EACH ROW EXECUTE FUNCTION fn_mobile_capture_change('task');

DROP TRIGGER IF EXISTS trg_notes_mobile_change ON crm_notes;
CREATE TRIGGER trg_notes_mobile_change AFTER INSERT OR UPDATE OR DELETE ON crm_notes
    FOR EACH ROW EXECUTE FUNCTION fn_mobile_capture_change('note');

DROP TRIGGER IF EXISTS trg_activities_mobile_change ON crm_activities;
CREATE TRIGGER trg_activities_mobile_change AFTER INSERT OR UPDATE OR DELETE ON crm_activities
    FOR EACH ROW EXECUTE FUNCTION fn_mobile_capture_change('activity');
