/**
 * Analytics Execution Data
 * ------------------------
 * Business data for Analytics & Business Intelligence execution groups and tasks.
 *
 * IMPORTANT: This file contains ONLY business data.
 * All execution logic (types, calculators, validators, constants)
 * MUST be imported from the shared framework: @/lib/execution
 */

import type {
  GroupStatus,
  TaskType,
  TaskPriority,
  TaskStatus,
} from "../../lib/execution";

// ── Analytics-Specific Task Type ──────────────────────────────────────────

/**
 * Analytics Task — Business data for an Analytics task.
 *
 * NOTE: This is NOT an ExecutionTask. The AnalyticsExecutionProvider
 * converts this to ExecutionTask when providing data to the framework.
 */
export interface AnalyticsTask {
  id: string;
  number: string;
  nameAr: string;
  nameEn: string;
  groupCode: string;
  descriptionAr: string;
  descriptionEn: string;
  type: TaskType;
  priority: TaskPriority;
  status: TaskStatus;
  dependencies: string[];
  acceptanceCriteriaAr: string;
  implementationNotesAr: string;
}

// ── Analytics Execution Groups ─────────────────────────────────────────────

/**
 * Analytics Execution Groups — Business data for group definitions.
 *
 * NOTE: This is NOT an ExecutionGroup[]. The AnalyticsExecutionProvider
 * converts this to ExecutionGroup[] when providing data to the framework.
 */
export const ANALYTICS_GROUP_DATA = [
  {
    code: "G0",
    titleAr: "البنية التحتية لwarehouse البيانات",
    titleEn: "Data Warehouse Foundation",
    purposeAr: "تأسيس مستودع البيانات وخطوط ETL الأساسية.",
    purposeEn: "Establish the data warehouse and foundational ETL pipelines.",
    status: "IN_PROGRESS" as GroupStatus,
    dependencies: [],
    canParallelizeWith: [],
    stageReport: null,
  },
  {
    code: "G1",
    titleAr: "الميزات الأساسية — لوحات وتقارير",
    titleEn: "Core Features — Dashboards & Reports",
    purposeAr: "بناء لوحة التحكم الرئيسية ومحرك التقارير الأساسي.",
    purposeEn: "Build the main dashboard and core reporting engine.",
    status: "NOT_STARTED" as GroupStatus,
    dependencies: ["G0"],
    canParallelizeWith: ["G2"],
    stageReport: null,
  },
  {
    code: "G2",
    titleAr: "التحليلات المتقدمة — التوقعات والاتجاهات",
    titleEn: "Advanced Analytics — Forecasting & Trends",
    purposeAr: "تنفيذ طبقات التحليل المتقدمة: التوقعات والاتجاهات والأنماط.",
    purposeEn: "Implement advanced analytics layers: forecasting, trends, and pattern detection.",
    status: "NOT_STARTED" as GroupStatus,
    dependencies: ["G0"],
    canParallelizeWith: ["G1"],
    stageReport: null,
  },
  {
    code: "G3",
    titleAr: "تصور البيانات — رسوم بيانية وعناصر",
    titleEn: "Data Visualization — Charts & Widgets",
    purposeAr: "بناء مكتبة الرسوم البيانية التفاعلية وعناصر التصور.",
    purposeEn: "Build the interactive chart library and visualization widgets.",
    status: "NOT_STARTED" as GroupStatus,
    dependencies: ["G1", "G2"],
    canParallelizeWith: [],
    stageReport: null,
  },
  {
    code: "G4",
    titleAr: "التصدير والتكامل",
    titleEn: "Export & Integration",
    purposeAr: "تنفيذ التصدير إلى PDF/Excel والتكامل مع ERP والمالية.",
    purposeEn: "Implement PDF/Excel export and ERP/Finance integration.",
    status: "NOT_STARTED" as GroupStatus,
    dependencies: ["G3"],
    canParallelizeWith: [],
    stageReport: null,
  },
];

// ── Analytics Tasks ────────────────────────────────────────────────────────

export const ANALYTICS_TASKS: AnalyticsTask[] = [
  // ── G0: Data Warehouse Foundation ────────────────────────────────────────
  {
    id: "G0-T01",
    number: "G0-01",
    nameAr: "تصميم مخطط مستودع البيانات",
    nameEn: "Design data warehouse schema",
    groupCode: "G0",
    descriptionAr: "تصميم جداول star schema: dim_date, dim_customer, dim_product, dim_employee, fact_sales, fact_inventory",
    descriptionEn: "Design star schema tables: dim_date, dim_customer, dim_product, dim_employee, fact_sales, fact_inventory",
    type: "Database",
    priority: "Critical",
    status: "DONE",
    dependencies: [],
    acceptanceCriteriaAr: "مخطط star schema موثق مع العلاقات",
    implementationNotesAr: "V20260801_1_STAR_SCHEMA",
  },
  {
    id: "G0-T02",
    number: "G0-02",
    nameAr: "إنشاء جداول fact و dimension",
    nameEn: "Create fact and dimension tables",
    groupCode: "G0",
    descriptionAr: "إنشاء 6 جداول fact و 4 جداول dimension مع فهارس الأداء",
    descriptionEn: "Create 6 fact tables and 4 dimension tables with performance indexes",
    type: "Database",
    priority: "Critical",
    status: "DONE",
    dependencies: ["G0-T01"],
    acceptanceCriteriaAr: "10 جداول مُنشأة مع tenant_id isolation",
    implementationNotesAr: "V20260801_2_TABLES, V20260801_3_INDEXES",
  },
  {
    id: "G0-T03",
    number: "G0-03",
    nameAr: "بناء خط أنابيب ETL الأساسي",
    nameEn: "Build core ETL pipeline",
    groupCode: "G0",
    descriptionAr: "بناء pipeline لاستخراج البيانات من ERP وFinance وتحويلها وتحميلها في warehouse",
    descriptionEn: "Build pipeline to extract data from ERP and Finance, transform, and load into warehouse",
    type: "Backend",
    priority: "Critical",
    status: "IN_PROGRESS",
    dependencies: ["G0-T02"],
    acceptanceCriteriaAr: "ETL ينقل البيانات من المصادر إلى warehouse بنجاح",
    implementationNotesAr: "AnalyticsEtlService, AnalyticsEtlScheduler",
  },
  {
    id: "G0-T04",
    number: "G0-04",
    nameAr: "تنفيذ جدولة ETL تلقائية",
    nameEn: "Implement automated ETL scheduling",
    groupCode: "G0",
    descriptionAr: "تنفيذ جدولة تلقائية لخطوط ETL مع إعادة المحاولة والسجلات",
    descriptionEn: "Implement automated scheduling for ETL pipelines with retry and logging",
    type: "Backend",
    priority: "High",
    status: "NOT_STARTED",
    dependencies: ["G0-T03"],
    acceptanceCriteriaAr: "ETL يُنفَّذ تلقائياً كل ساعة مع سجلات",
    implementationNotesAr: "AnalyticsEtlScheduler",
  },
  {
    id: "G0-T05",
    number: "G0-05",
    nameAr: "إنشاء API لاستعلامات warehouse",
    nameEn: "Create warehouse query API",
    groupCode: "G0",
    descriptionAr: "إنشاء REST API لاستعلامات warehouse مع caching و pagination",
    descriptionEn: "Create REST API for warehouse queries with caching and pagination",
    type: "API",
    priority: "Critical",
    status: "NOT_STARTED",
    dependencies: ["G0-T02"],
    acceptanceCriteriaAr: "API endpoints لجميع جداول warehouse",
    implementationNotesAr: "AnalyticsWarehouseController",
  },

  // ── G1: Core Features — Dashboards & Reports ────────────────────────────
  {
    id: "G1-T01",
    number: "G1-01",
    nameAr: "بناء لوحة التحكم الرئيسية",
    nameEn: "Build main analytics dashboard",
    groupCode: "G1",
    descriptionAr: "بناء لوحة تحكم رئيسية تعرض KPIs الرئيسية وملخصات الأداء",
    descriptionEn: "Build main dashboard displaying key KPIs and performance summaries",
    type: "Frontend",
    priority: "Critical",
    status: "NOT_STARTED",
    dependencies: [],
    acceptanceCriteriaAr: "لوحة تحكم تعرض 8 KPIs رئيسية",
    implementationNotesAr: "AnalyticsDashboard",
  },
  {
    id: "G1-T02",
    number: "G1-02",
    nameAr: "بناء محرك التقارير",
    nameEn: "Build reporting engine",
    groupCode: "G1",
    descriptionAr: "بناء محرك تقارير ديناميكي يدعم الفلاتر والトجميع والتسلسل الهرمي",
    descriptionEn: "Build dynamic reporting engine supporting filters, aggregation, and drill-down",
    type: "Backend",
    priority: "Critical",
    status: "NOT_STARTED",
    dependencies: ["G0-T05"],
    acceptanceCriteriaAr: "محرك التقارير يدعم 5 أنواع تقارير",
    implementationNotesAr: "AnalyticsReportEngine",
  },
  {
    id: "G1-T03",
    number: "G1-03",
    nameAr: "إنشاء صفحة إدارة التقارير",
    nameEn: "Create report management page",
    groupCode: "G1",
    descriptionAr: "صفحة لإنشاء وتعديل وحذف التقارير المخصصة",
    descriptionEn: "Page for creating, editing, and deleting custom reports",
    type: "Frontend",
    priority: "High",
    status: "NOT_STARTED",
    dependencies: ["G1-T01"],
    acceptanceCriteriaAr: "صفحة إدارة التقارير تعمل بالكامل",
    implementationNotesAr: "ReportsManagementPage",
  },
  {
    id: "G1-T04",
    number: "G1-04",
    nameAr: "بناء نظام تنبيهات الأداء",
    nameEn: "Build performance alerting system",
    groupCode: "G1",
    descriptionAr: "نظام تنبيهات يُفعَّل عند تجاوز KPIs لعتبات محددة",
    descriptionEn: "Alerting system triggered when KPIs exceed defined thresholds",
    type: "Backend",
    priority: "Medium",
    status: "NOT_STARTED",
    dependencies: ["G1-T02"],
    acceptanceCriteriaAr: "تنبيهات تُرسل عند تجاوز العتبات",
    implementationNotesAr: "AnalyticsAlertService",
  },
  {
    id: "G1-T05",
    number: "G1-05",
    nameAr: "إنشاء صفحة KPIs الرئيسية",
    nameEn: "Create KPI overview page",
    groupCode: "G1",
    descriptionAr: "صفحة مخصصة لعرض جميع KPIs مع الاتجاهات والتغيرات",
    descriptionEn: "Dedicated page showing all KPIs with trends and changes",
    type: "Frontend",
    priority: "High",
    status: "NOT_STARTED",
    dependencies: ["G1-T01"],
    acceptanceCriteriaAr: "صفحة KPIs تعرض جميع المؤشرات",
    implementationNotesAr: "KpiOverviewPage",
  },

  // ── G2: Advanced Analytics — Forecasting & Trends ───────────────────────
  {
    id: "G2-T01",
    number: "G2-01",
    nameAr: "بناء محرك التوقعات",
    nameEn: "Build forecasting engine",
    groupCode: "G2",
    descriptionAr: "بناء محرك توقعات باستخدام خوارزميات سلسلة الزمن (ARIMA, Exponential Smoothing)",
    descriptionEn: "Build forecasting engine using time series algorithms (ARIMA, Exponential Smoothing)",
    type: "Backend",
    priority: "Critical",
    status: "NOT_STARTED",
    dependencies: [],
    acceptanceCriteriaAr: "محرك التوقعات يتنبأ بـ 30 يوم مقبل",
    implementationNotesAr: "AnalyticsForecastService",
  },
  {
    id: "G2-T02",
    number: "G2-02",
    nameAr: "بناء كاشف الاتجاهات",
    nameEn: "Build trend detector",
    groupCode: "G2",
    descriptionAr: "بناء نظام كشف الاتجاهات والأنماط في بيانات المبيعات والعملاء",
    descriptionEn: "Build trend and pattern detection system in sales and customer data",
    type: "Backend",
    priority: "High",
    status: "NOT_STARTED",
    dependencies: ["G0-T03"],
    acceptanceCriteriaAr: "كاشف الاتجاهات يكشف 3 أنماط رئيسية",
    implementationNotesAr: "AnalyticsTrendService",
  },
  {
    id: "G2-T03",
    number: "G2-03",
    nameAr: "بناء صفحة التوقعات",
    nameEn: "Build forecasting page",
    groupCode: "G2",
    descriptionAr: "صفحة تفاعلية لعرض التوقعات مع الرسوم البيانية",
    descriptionEn: "Interactive page for displaying forecasts with charts",
    type: "Frontend",
    priority: "Critical",
    status: "NOT_STARTED",
    dependencies: ["G2-T01"],
    acceptanceCriteriaAr: "صفحة التوقعات تعرض 30 يوم مقبل",
    implementationNotesAr: "ForecastPage",
  },
  {
    id: "G2-T04",
    number: "G2-04",
    nameAr: "بناء تحليل سلسلة الزمن",
    nameEn: "Build time series analysis",
    groupCode: "G2",
    descriptionAr: "تحليل سلسلة الزمن مع تحديد الموسمية والاتجاهات طويلة المدى",
    descriptionEn: "Time series analysis with seasonality and long-term trend identification",
    type: "Backend",
    priority: "Medium",
    status: "NOT_STARTED",
    dependencies: ["G2-T01"],
    acceptanceCriteriaAr: "تحليل سلسلة الزمن يحدد الموسمية",
    implementationNotesAr: "AnalyticsTimeSeriesService",
  },

  // ── G3: Data Visualization — Charts & Widgets ──────────────────────────
  {
    id: "G3-T01",
    number: "G3-01",
    nameAr: "بناء مكتبة الرسوم البيانية",
    nameEn: "Build chart component library",
    groupCode: "G3",
    descriptionAr: "بناء مكتبة مكونات رسوم بيانية: Line, Bar, Pie, Scatter, Heatmap",
    descriptionEn: "Build chart component library: Line, Bar, Pie, Scatter, Heatmap",
    type: "Frontend",
    priority: "Critical",
    status: "NOT_STARTED",
    dependencies: [],
    acceptanceCriteriaAr: "5 أنواع رسوم بيانية تعمل بشكل صحيح",
    implementationNotesAr: "AnalyticsCharts library",
  },
  {
    id: "G3-T02",
    number: "G3-02",
    nameAr: "بناء عناصر التصور التفاعلية",
    nameEn: "Build interactive visualization widgets",
    groupCode: "G3",
    descriptionAr: "بناء عناصر تفاعلية: DateRangePicker, FilterPanel, DrillDownNavigator",
    descriptionEn: "Build interactive widgets: DateRangePicker, FilterPanel, DrillDownNavigator",
    type: "Frontend",
    priority: "High",
    status: "NOT_STARTED",
    dependencies: ["G3-T01"],
    acceptanceCriteriaAr: "3 عناصر تفاعلية تكمل الرسوم البيانية",
    implementationNotesAr: "AnalyticsWidgets",
  },
  {
    id: "G3-T03",
    number: "G3-03",
    nameAr: "بناء صفحة تخصيص Dashboard",
    nameEn: "Build dashboard customization page",
    groupCode: "G3",
    descriptionAr: "صفحة تسمح للمستخدمين بتخصيص تخطيط Dashboard بالسحب والإفلات",
    descriptionEn: "Page allowing users to customize dashboard layout via drag-and-drop",
    type: "Frontend",
    priority: "Medium",
    status: "NOT_STARTED",
    dependencies: ["G3-T02"],
    acceptanceCriteriaAr: "تخصيص Dashboard بالسحب والإفلات يعمل",
    implementationNotesAr: "DashboardCustomizer",
  },
  {
    id: "G3-T04",
    number: "G3-04",
    nameAr: "بناء وضع عرض البيانات الكبيرة",
    nameEn: "Build large data display mode",
    groupCode: "G3",
    descriptionAr: "وضع عرض محسّن للبيانات الكبيرة مع virtual scrolling و lazy loading",
    descriptionEn: "Optimized display mode for large datasets with virtual scrolling and lazy loading",
    type: "Frontend",
    priority: "Medium",
    status: "NOT_STARTED",
    dependencies: ["G3-T01"],
    acceptanceCriteriaAr: "عرض 10000 صف بدون تأثير على الأداء",
    implementationNotesAr: "LargeDataDisplayMode",
  },

  // ── G4: Export & Integration ─────────────────────────────────────────────
  {
    id: "G4-T01",
    number: "G4-01",
    nameAr: "بناء محرك تصدير PDF",
    nameEn: "Build PDF export engine",
    groupCode: "G4",
    descriptionAr: "بناء محرك تصدير التقارير إلى PDF مع تنسيق احترافي",
    descriptionEn: "Build report export engine to PDF with professional formatting",
    type: "Backend",
    priority: "Critical",
    status: "NOT_STARTED",
    dependencies: [],
    acceptanceCriteriaAr: "تصدير PDF يعمل لأي تقرير",
    implementationNotesAr: "AnalyticsPdfExportService",
  },
  {
    id: "G4-T02",
    number: "G4-02",
    nameAr: "بناء محرك تصدير Excel",
    nameEn: "Build Excel export engine",
    groupCode: "G4",
    descriptionAr: "بناء محرك تصدير التقارير إلى Excel/CSV مع تنسيق خلايا",
    descriptionEn: "Build report export engine to Excel/CSV with cell formatting",
    type: "Backend",
    priority: "High",
    status: "NOT_STARTED",
    dependencies: [],
    acceptanceCriteriaAr: "تصدير Excel يعمل مع تنسيق خلايا",
    implementationNotesAr: "AnalyticsExcelExportService",
  },
  {
    id: "G4-T03",
    number: "G4-03",
    nameAr: "بناء واجهة تكامل ERP",
    nameEn: "Build ERP integration interface",
    groupCode: "G4",
    descriptionAr: "واجهة REST API لتكامل Analytics مع ERP: بيانات المبيعات والمشتريات",
    descriptionEn: "REST API interface for Analytics-ERP integration: sales and procurement data",
    type: "API",
    priority: "Critical",
    status: "NOT_STARTED",
    dependencies: ["G0-T05"],
    acceptanceCriteriaAr: "تكامل ERP ينقل بيانات المبيعات والمشتريات",
    implementationNotesAr: "AnalyticsErpIntegrationController",
  },
  {
    id: "G4-T04",
    number: "G4-04",
    nameAr: "بناء واجهة تكامل المالية",
    nameEn: "Build Finance integration interface",
    groupCode: "G4",
    descriptionAr: "واجهة REST API لتكامل Analytics مع المالية: بيانات الإيرادات والمصروفات",
    descriptionEn: "REST API interface for Analytics-Finance integration: revenue and expense data",
    type: "API",
    priority: "Critical",
    status: "NOT_STARTED",
    dependencies: ["G0-T05"],
    acceptanceCriteriaAr: "تكامل المالية ينقل بيانات الإيرادات والمصروفات",
    implementationNotesAr: "AnalyticsFinanceIntegrationController",
  },
];
