package com.sanad.platform.module.lifecycle;

import java.time.Instant;
import java.util.List;
import java.util.UUID;

/**
 * Immutable preview of what a module reset would do.
 *
 * <p>Generated by {@link ModuleResetService#previewReset(UUID, String)} before any
 * destructive operation. The caller must review this preview and explicitly
 * confirm before executing the reset.
 *
 * @param tenantId          the tenant whose data would be reset
 * @param moduleCode        the module code (e.g., "CRM")
 * @param affectedTables   ordered list of tables that would be affected (children-first)
 * @param estimatedRows     estimated total rows across all affected tables
 * @param protectedTables   list of protected tables that will NOT be touched
 * @param irreversible      true if the reset is irreversible (data deletion)
 * @param previewGeneratedAt when the preview was generated
 */
public record ModuleResetPreview(
        UUID tenantId,
        String moduleCode,
        List<TablePreview> affectedTables,
        long estimatedRows,
        List<String> protectedTables,
        boolean irreversible,
        Instant previewGeneratedAt
) {
    /**
     * Per-table preview entry.
     *
     * @param tableName    the table name
     * @param estimatedRows estimated row count for this tenant in this table
     * @param classification data classification (always RESETTABLE for affected tables)
     */
    public record TablePreview(
            String tableName,
            long estimatedRows,
            DataClassification classification
    ) {}
}
