/**
 * ERP Execution Data
 * ------------------
 * Business data for ERP execution groups and tasks.
 *
 * IMPORTANT: This file contains ONLY business data.
 * All execution logic (types, calculators, validators, constants)
 * MUST be imported from the shared framework: @/lib/execution
 */

import type {
  GroupStatus,
  TaskType,
  TaskPriority,
  TaskStatus,
} from "../../lib/execution";

// ── ERP-Specific Task Type ────────────────────────────────────────────────

/**
 * ERP Task — Business data for an ERP task.
 *
 * NOTE: This is NOT an ExecutionTask. The ErpExecutionProvider
 * converts this to ExecutionTask when providing data to the framework.
 */
export interface ErpTask {
  id: string;
  number: string;
  nameAr: string;
  nameEn: string;
  groupCode: string;
  descriptionAr: string;
  descriptionEn: string;
  type: TaskType;
  priority: TaskPriority;
  status: TaskStatus;
  dependencies: string[];
  acceptanceCriteriaAr: string;
  implementationNotesAr: string;
}

// ── ERP Execution Groups ──────────────────────────────────────────────────

/**
 * ERP Execution Groups — Business data for group definitions.
 *
 * NOTE: This is NOT an ExecutionGroup[]. The ErpExecutionProvider
 * converts this to ExecutionGroup[] when providing data to the framework.
 */
export const ERP_GROUP_DATA = [
  {
    code: "G0",
    titleAr: "التأسيس والمخطط الرئيسي",
    titleEn: "Foundation & Database Schema",
    purposeAr: "إنشاء المخطط الأساسي للقاعدة البيانات والكيانات الجوهرية لنظام ERP.",
    purposeEn: "Create the core database schema and foundational entities for the ERP system.",
    status: "NOT_STARTED" as GroupStatus,
    dependencies: [],
    canParallelizeWith: [],
    stageReport: null,
  },
  {
    code: "G1",
    titleAr: "بيانات الأعضاء",
    titleEn: "Master Data Management",
    purposeAr: "إدارة المنتجات والعملاء والموردين والبيانات الأساسية المشتركة.",
    purposeEn: "Manage products, customers, suppliers, and shared master data.",
    status: "NOT_STARTED" as GroupStatus,
    dependencies: ["G0"],
    canParallelizeWith: [],
    stageReport: null,
  },
  {
    code: "G2",
    titleAr: "المشتريات",
    titleEn: "Procurement",
    purposeAr: "أوامر الشراء والاستلام وتقييم الموردين.",
    purposeEn: "Purchase orders, receiving, and supplier evaluation.",
    status: "NOT_STARTED" as GroupStatus,
    dependencies: ["G0", "G1"],
    canParallelizeWith: ["G3"],
    stageReport: null,
  },
  {
    code: "G3",
    titleAr: "المبيعات",
    titleEn: "Sales",
    purposeAr: "عروض الأسعار وأوامر البيع والفواتير وإدارة حسابات العملاء.",
    purposeEn: "Quotations, sales orders, invoicing, and customer account management.",
    status: "NOT_STARTED" as GroupStatus,
    dependencies: ["G0", "G1"],
    canParallelizeWith: ["G2"],
    stageReport: null,
  },
  {
    code: "G4",
    titleAr: "إدارة المخزون",
    titleEn: "Inventory Management",
    purposeAr: "إدارة المخزون والمستودعات وحركة البضائع.",
    purposeEn: "Stock management, warehouses, and goods movement.",
    status: "NOT_STARTED" as GroupStatus,
    dependencies: ["G1"],
    canParallelizeWith: ["G5"],
    stageReport: null,
  },
  {
    code: "G5",
    titleAr: "التصنيع",
    titleEn: "Manufacturing",
    purposeAr: "قائمة المواد (BOM) وأوامر الإنتاج وتتبع التكاليف.",
    purposeEn: "Bill of Materials, production orders, and cost tracking.",
    status: "NOT_STARTED" as GroupStatus,
    dependencies: ["G1", "G4"],
    canParallelizeWith: [],
    stageReport: null,
  },
  {
    code: "G6",
    titleAr: "المحاسبة",
    titleEn: "Accounting",
    purposeAr: "دفتر الأستاذ العام والقيود المحاسبية والتقارير المالية.",
    purposeEn: "General ledger, journal entries, and financial reports.",
    status: "NOT_STARTED" as GroupStatus,
    dependencies: ["G2", "G3"],
    canParallelizeWith: [],
    stageReport: null,
  },
  {
    code: "G7",
    titleAr: "التكامل والربط",
    titleEn: "Integration & API",
    purposeAr: "واجهات برمجة التطبيقات والربط مع الأنظمة الخارجية (EDI).",
    purposeEn: "APIs and external system integration (EDI).",
    status: "NOT_STARTED" as GroupStatus,
    dependencies: ["G0"],
    canParallelizeWith: ["G1", "G2", "G3"],
    stageReport: null,
  },
  {
    code: "G8",
    titleAr: "التحليلات والتقارير",
    titleEn: "Analytics & Reporting",
    purposeAr: "لوحات التحليل والتقارير الاستخباراتية والتنبؤات.",
    purposeEn: "Analytics dashboards, business intelligence reports, and forecasting.",
    status: "NOT_STARTED" as GroupStatus,
    dependencies: ["G6"],
    canParallelizeWith: [],
    stageReport: null,
  },
];

// ── ERP Tasks ─────────────────────────────────────────────────────────────

export const ERP_TASKS: ErpTask[] = [
  // ── G0: Foundation & Database Schema ─────────────────────────────────────
  {
    id: "G0-T01", number: "G0-01",
    nameAr: "إنشاء مخطط قاعدة البيانات الأساسي", nameEn: "Create core database schema",
    groupCode: "G0",
    descriptionAr: "إنشاء الجداول الأساسية لجميع كيانات ERP مع المخطط الأحادي المستأجر",
    descriptionEn: "Create core tables for all ERP entities with single-tenant schema",
    type: "Database", priority: "Critical", status: "NOT_STARTED",
    dependencies: [],
    acceptanceCriteriaAr: "جميع الجداول الأساسية موجودة مع الفهارس والقيود",
    implementationNotesAr: "استخدام TypeORM مع PostgreSQL",
  },
  {
    id: "G0-T02", number: "G0-02",
    nameAr: "إنشاء كيانات ERP الأساسية", nameEn: "Create core ERP entities",
    groupCode: "G0",
    descriptionAr: "تنفيذ كيانات Company, Branch, Department, Unit, Currency",
    descriptionEn: "Implement Company, Branch, Department, Unit, Currency entities",
    type: "Backend", priority: "Critical", status: "NOT_STARTED",
    dependencies: ["G0-T01"],
    acceptanceCriteriaAr: "5 كيانات أساسية مع CRUD كامل",
    implementationNotesAr: "RESTful endpoints مع validation",
  },
  {
    id: "G0-T03", number: "G0-03",
    nameAr: "إعداد نظام الصلاحيات والأدوار", nameEn: "Set up roles and permissions system",
    groupCode: "G0",
    descriptionAr: "تنفيذ Role, Permission, UserRole مع التحقق من الصلاحيات",
    descriptionEn: "Implement Role, Permission, UserRole with authorization checks",
    type: "Backend", priority: "Critical", status: "NOT_STARTED",
    dependencies: ["G0-T02"],
    acceptanceCriteriaAr: "نظام صلاحيات يعمل مع JWT tokens",
    implementationNotesAr: "Guard decorator مع Role-based access",
  },
  {
    id: "G0-T04", number: "G0-04",
    nameAr: "إنشاء لوحة التحكم الرئيسية", nameEn: "Create main ERP dashboard",
    groupCode: "G0",
    descriptionAr: "إنشاء صفحة /erp مع التخطيط المستقل والشريط الجانبي",
    descriptionEn: "Create /erp page with independent layout and sidebar",
    type: "Frontend", priority: "Critical", status: "NOT_STARTED",
    dependencies: [],
    acceptanceCriteriaAr: "لوحة تحكم تعرض KPIs وملخصات الوحدات",
    implementationNotesAr: "Layout مستقل مع React Context",
  },
  {
    id: "G0-T05", number: "G0-05",
    nameAr: "تطبيق التدويل RTL/LTR", nameEn: "Implement i18n RTL/LTR",
    groupCode: "G0",
    descriptionAr: "دعم العربية والإنجليزية مع RTL وLTR",
    descriptionEn: "Support Arabic/English with RTL/LTR",
    type: "Frontend", priority: "High", status: "NOT_STARTED",
    dependencies: ["G0-T04"],
    acceptanceCriteriaAr: "تبديل بين RTL وLTR يعمل بسلاسة",
    implementationNotesAr: "localStorage للحفظ المحلي",
  },

  // ── G1: Master Data Management ──────────────────────────────────────────
  {
    id: "G1-T01", number: "G1-01",
    nameAr: "إدارة المنتجات", nameEn: "Product Management",
    groupCode: "G1",
    descriptionAr: "إنشاء كيان المنتج مع الفئات وال unit measures والصور",
    descriptionEn: "Create product entity with categories, units of measure, and images",
    type: "Backend", priority: "Critical", status: "NOT_STARTED",
    dependencies: ["G0-T02"],
    acceptanceCriteriaAr: "CRUD للمنتجات مع بحث وفلترة",
    implementationNotesAr: "Product, Category, UnitOfMeasure entities",
  },
  {
    id: "G1-T02", number: "G1-02",
    nameAr: "إدارة العملاء", nameEn: "Customer Management",
    groupCode: "G1",
    descriptionAr: "إنشاء كيان العميل مع بيانات الاتصال والعناوين",
    descriptionEn: "Create customer entity with contacts and addresses",
    type: "Backend", priority: "Critical", status: "NOT_STARTED",
    dependencies: ["G0-T02"],
    acceptanceCriteriaAr: "CRUD للعملاء مع عناوين متعددة",
    implementationNotesAr: "Customer, Contact, Address entities",
  },
  {
    id: "G1-T03", number: "G1-03",
    nameAr: "إدارة الموردين", nameEn: "Supplier Management",
    groupCode: "G1",
    descriptionAr: "إنشاء كيان المورد مع تصنيف الموردين وتقييم الأداء",
    descriptionEn: "Create supplier entity with classification and performance rating",
    type: "Backend", priority: "High", status: "NOT_STARTED",
    dependencies: ["G0-T02"],
    acceptanceCriteriaAr: "CRUD للموردين مع تصنيف وتقييم",
    implementationNotesAr: "Supplier, SupplierClassification, SupplierRating",
  },
  {
    id: "G1-T04", number: "G1-04",
    nameAr: "واجهة إدارة المنتجات", nameEn: "Product management UI",
    groupCode: "G1",
    descriptionAr: "صفحة إدارة المنتجات مع جدول ونماذج إضافة/تعديل",
    descriptionEn: "Product management page with table and add/edit forms",
    type: "Frontend", priority: "Critical", status: "NOT_STARTED",
    dependencies: ["G1-T01", "G0-T04"],
    acceptanceCriteriaAr: "واجهة CRUD كاملة للمنتجات",
    implementationNotesAr: "DataTable مع 필터링 وبحث",
  },
  {
    id: "G1-T05", number: "G1-05",
    nameAr: "واجهة إدارة العملاء والموردين", nameEn: "Customer & Supplier management UI",
    groupCode: "G1",
    descriptionAr: "صفحات إدارة العملاء والموردين مع النماذج",
    descriptionEn: "Customer and supplier management pages with forms",
    type: "Frontend", priority: "High", status: "NOT_STARTED",
    dependencies: ["G1-T02", "G1-T03", "G0-T04"],
    acceptanceCriteriaAr: "واجهات CRUD للعملاء والموردين",
    implementationNotesAr: "Shared components between customers and suppliers",
  },

  // ── G2: Procurement ─────────────────────────────────────────────────────
  {
    id: "G2-T01", number: "G2-01",
    nameAr: "أوامر الشراء", nameEn: "Purchase Orders",
    groupCode: "G2",
    descriptionAr: "إنشاء وإدارة أوامر الشراء مع سير العمل",
    descriptionEn: "Create and manage purchase orders with workflow",
    type: "Backend", priority: "Critical", status: "NOT_STARTED",
    dependencies: ["G1-T03"],
    acceptanceCriteriaAr: "أوامر شراء مع حالات سير العمل",
    implementationNotesAr: "PO entity مع Draft → Approved → Received",
  },
  {
    id: "G2-T02", number: "G2-02",
    nameAr: "استلام البضائع", nameEn: "Goods Receiving",
    groupCode: "G2",
    descriptionAr: "نظام استلام البضائع مع الفحص والتوثيق",
    descriptionEn: "Goods receiving system with inspection and documentation",
    type: "Backend", priority: "Critical", status: "NOT_STARTED",
    dependencies: ["G2-T01"],
    acceptanceCriteriaAr: "استلام مع فحص جودة وتوثيق",
    implementationNotesAr: "GoodsReceipt مع QCStatus",
  },
  {
    id: "G2-T03", number: "G2-03",
    nameAr: "تقييم الموردين", nameEn: "Supplier Evaluation",
    groupCode: "G2",
    descriptionAr: "نظام تقييم أداء الموردين بناء على التسليم والجودة",
    descriptionEn: "Supplier performance evaluation based on delivery and quality",
    type: "Backend", priority: "Medium", status: "NOT_STARTED",
    dependencies: ["G2-T02", "G1-T03"],
    acceptanceCriteriaAr: "تقييم تلقائي بعد كل استلام",
    implementationNotesAr: "SupplierEvaluation مع scoring algorithm",
  },
  {
    id: "G2-T04", number: "G2-04",
    nameAr: "واجهة أوامر الشراء", nameEn: "Purchase Orders UI",
    groupCode: "G2",
    descriptionAr: "واجهة لإدارة أوامر الشراء مع سير العمل",
    descriptionEn: "UI for managing purchase orders with workflow",
    type: "Frontend", priority: "Critical", status: "NOT_STARTED",
    dependencies: ["G2-T01", "G0-T04"],
    acceptanceCriteriaAr: "واجهة كاملة لأوامر الشراء",
    implementationNotesAr: "Multi-step form مع approval flow",
  },

  // ── G3: Sales ───────────────────────────────────────────────────────────
  {
    id: "G3-T01", number: "G3-01",
    nameAr: "عروض الأسعار", nameEn: "Quotations",
    groupCode: "G3",
    descriptionAr: "إنشاء وإدارة عروض الأسعار مع حساب الضريبة",
    descriptionEn: "Create and manage quotations with tax calculation",
    type: "Backend", priority: "Critical", status: "NOT_STARTED",
    dependencies: ["G1-T01", "G1-T02"],
    acceptanceCriteriaAr: "عروض أسعار مع حساب تلقائي للضريبة",
    implementationNotesAr: "Quotation entity مع line items",
  },
  {
    id: "G3-T02", number: "G3-02",
    nameAr: "أوامر البيع", nameEn: "Sales Orders",
    groupCode: "G3",
    descriptionAr: "تحويل عروض الأسعار إلى أوامر بيع مع تأكيد المخزون",
    descriptionEn: "Convert quotations to sales orders with inventory reservation",
    type: "Backend", priority: "Critical", status: "NOT_STARTED",
    dependencies: ["G3-T01"],
    acceptanceCriteriaAr: "أوامر بيع مع حجز المخزون التلقائي",
    implementationNotesAr: "SalesOrder مع InventoryReservation",
  },
  {
    id: "G3-T03", number: "G3-03",
    nameAr: "الفوترة والمبيعات", nameEn: "Invoicing & Billing",
    groupCode: "G3",
    descriptionAr: "إنشاء الفواتير من أوامر البيع مع دفعات متعددة",
    descriptionEn: "Generate invoices from sales orders with partial payments",
    type: "Backend", priority: "Critical", status: "NOT_STARTED",
    dependencies: ["G3-T02"],
    acceptanceCriteriaAr: "فواتير مع دفعات جزئية ودفتر أستاذ",
    implementationNotesAr: "Invoice مع PaymentPlan",
  },
  {
    id: "G3-T04", number: "G3-04",
    nameAr: "واجهة المبيعات", nameEn: "Sales UI",
    groupCode: "G3",
    descriptionAr: "واجهة شاملة للمبيعات (عروض → أوامر → فواتير)",
    descriptionEn: "Comprehensive sales UI (quotations → orders → invoices)",
    type: "Frontend", priority: "Critical", status: "NOT_STARTED",
    dependencies: ["G3-T01", "G3-T02", "G3-T03", "G0-T04"],
    acceptanceCriteriaAr: "مسار مبيعات كامل من العرض إلى الفاتورة",
    implementationNotesAr: "Multi-step wizard مع progress indicator",
  },

  // ── G4: Inventory Management ────────────────────────────────────────────
  {
    id: "G4-T01", number: "G4-01",
    nameAr: "إدارة المستودعات", nameEn: "Warehouse Management",
    groupCode: "G4",
    descriptionAr: "إدارة المستودعات والأماكن (bins) والمناطق",
    descriptionEn: "Manage warehouses, bins, and zones",
    type: "Backend", priority: "Critical", status: "NOT_STARTED",
    dependencies: ["G1-T01"],
    acceptanceCriteriaAr: "مستودعات مع هيكل أماكن شجري",
    implementationNotesAr: "Warehouse, Zone, Bin entities",
  },
  {
    id: "G4-T02", number: "G4-02",
    nameAr: "حركة البضائع", nameEn: "Stock Movements",
    groupCode: "G4",
    descriptionAr: "تسجيل حركات الإدخال والإخراج والتحويل",
    descriptionEn: "Record stock in, stock out, and transfer movements",
    type: "Backend", priority: "Critical", status: "NOT_STARTED",
    dependencies: ["G4-T01"],
    acceptanceCriteriaAr: "حركات مخزون مع تدقيق مزدوج",
    implementationNotesAr: "StockMovement مع double-entry",
  },
  {
    id: "G4-T03", number: "G4-03",
    nameAr: "جرد المخزون", nameEn: "Inventory Counting",
    groupCode: "G4",
    descriptionAr: "عمليات الجرد الدورية والتفقيط والتسويات",
    descriptionEn: "Periodic cycle counting and adjustments",
    type: "Backend", priority: "High", status: "NOT_STARTED",
    dependencies: ["G4-T02"],
    acceptanceCriteriaAr: "جدول جرد مع تسويات تلقائية",
    implementationNotesAr: "StockCount, StockAdjustment entities",
  },
  {
    id: "G4-T04", number: "G4-04",
    nameAr: "تنبيهات المخزون", nameEn: "Stock Alerts",
    groupCode: "G4",
    descriptionAr: "تنبيهات الحد الأدنى والحد الأقصى للمخزون",
    descriptionEn: "Minimum and maximum stock level alerts",
    type: "Backend", priority: "Medium", status: "NOT_STARTED",
    dependencies: ["G4-T02"],
    acceptanceCriteriaAr: "تنبيهات عند بلوغ الحد الأدنى",
    implementationNotesAr: "StockAlert مع notification service",
  },
  {
    id: "G4-T05", number: "G4-05",
    nameAr: "واجهة المخزون", nameEn: "Inventory UI",
    groupCode: "G4",
    descriptionAr: "واجهة لإدارة المخزون والمستودعات والجرد",
    descriptionEn: "UI for inventory, warehouses, and counting",
    type: "Frontend", priority: "Critical", status: "NOT_STARTED",
    dependencies: ["G4-T01", "G4-T02", "G0-T04"],
    acceptanceCriteriaAr: "واجهة شاملة لإدارة المخزون",
    implementationNotesAr: "Dashboard مع heat maps للمخزون",
  },

  // ── G5: Manufacturing ───────────────────────────────────────────────────
  {
    id: "G5-T01", number: "G5-01",
    nameAr: "قائمة المواد (BOM)", nameEn: "Bill of Materials (BOM)",
    groupCode: "G5",
    descriptionAr: "إدارة قوائم المواد مع التسلسل الهرمي",
    descriptionEn: "Manage bills of materials with hierarchy",
    type: "Backend", priority: "Critical", status: "NOT_STARTED",
    dependencies: ["G1-T01"],
    acceptanceCriteriaAr: "BOM متعدد الطبقات مع حساب التكلفة",
    implementationNotesAr: "BOM, BOMItem مع recursive tree",
  },
  {
    id: "G5-T02", number: "G5-02",
    nameAr: "أوامر الإنتاج", nameEn: "Production Orders",
    groupCode: "G5",
    descriptionAr: "إنشاء وأدارة أوامر الإنتاج مع تتبع التقدم",
    descriptionEn: "Create and manage production orders with progress tracking",
    type: "Backend", priority: "Critical", status: "NOT_STARTED",
    dependencies: ["G5-T01", "G4-T02"],
    acceptanceCriteriaAr: "أوامر إنتاج مع تتبع مباشر",
    implementationNotesAr: "ProductionOrder مع status tracking",
  },
  {
    id: "G5-T03", number: "G5-03",
    nameAr: "تتبع تكاليف الإنتاج", nameEn: "Production Cost Tracking",
    groupCode: "G5",
    descriptionAr: "تتبع تكاليف المواد والعمالة والمصروفات间接ة",
    descriptionEn: "Track material, labor, and overhead costs",
    type: "Backend", priority: "High", status: "NOT_STARTED",
    dependencies: ["G5-T02"],
    acceptanceCriteriaAr: "تكلفة إجمالية لكل أمر إنتاج",
    implementationNotesAr: "ProductionCost مع cost allocation",
  },
  {
    id: "G5-T04", number: "G5-04",
    nameAr: "واجهة التصنيع", nameEn: "Manufacturing UI",
    groupCode: "G5",
    descriptionAr: "واجهة لإدارة BOM وأوامر الإنتاج",
    descriptionEn: "UI for BOM and production order management",
    type: "Frontend", priority: "Critical", status: "NOT_STARTED",
    dependencies: ["G5-T01", "G5-T02", "G0-T04"],
    acceptanceCriteriaAr: "واجهة BOM tree و.production tracking",
    implementationNotesAr: "Visual BOM editor مع drag-and-drop",
  },

  // ── G6: Accounting ──────────────────────────────────────────────────────
  {
    id: "G6-T01", number: "G6-01",
    nameAr: "دفتر الأستاذ العام", nameEn: "General Ledger",
    groupCode: "G6",
    descriptionAr: "إنشاء دفتر الأستاذ مع شجرة الحسابات",
    descriptionEn: "Create general ledger with chart of accounts",
    type: "Backend", priority: "Critical", status: "NOT_STARTED",
    dependencies: ["G0-T02"],
    acceptanceCriteriaAr: "شجرة حسابات متعددة المستويات",
    implementationNotesAr: "Account, AccountType, AccountBalance",
  },
  {
    id: "G6-T02", number: "G6-02",
    nameAr: "القيود المحاسبية", nameEn: "Journal Entries",
    groupCode: "G6",
    descriptionAr: "إنشاء القيود المحاسبية مع التحقق من التوازن",
    descriptionEn: "Create journal entries with balance verification",
    type: "Backend", priority: "Critical", status: "NOT_STARTED",
    dependencies: ["G6-T01"],
    acceptanceCriteriaAr: "قيود متوازنة مع تدقيق مزدوج",
    implementationNotesAr: "JournalEntry, JournalLine مع double-entry validation",
  },
  {
    id: "G6-T03", number: "G6-03",
    nameAr: "الميزانية العمومية", nameEn: "Trial Balance",
    groupCode: "G6",
    descriptionAr: "إعداد الميزانية العمومية وتدقيق التوازن",
    descriptionEn: "Prepare trial balance and verify balance",
    type: "Backend", priority: "High", status: "NOT_STARTED",
    dependencies: ["G6-T02"],
    acceptanceCriteriaAr: "ميزانية عمومية متوازنة دائماً",
    implementationNotesAr: "TrialBalance service مع real-time calculation",
  },
  {
    id: "G6-T04", number: "G6-04",
    nameAr: "التقارير المالية", nameEn: "Financial Reports",
    groupCode: "G6",
    descriptionAr: "قائمة الدخل والميزانية العمومية وتدفق النقد",
    descriptionEn: "Income statement, balance sheet, and cash flow",
    type: "Backend", priority: "High", status: "NOT_STARTED",
    dependencies: ["G6-T03"],
    acceptanceCriteriaAr: "3 تقارير مالية أساسية",
    implementationNotesAr: "FinancialReport service مع date range filtering",
  },
  {
    id: "G6-T05", number: "G6-05",
    nameAr: "واجهة المحاسبة", nameEn: "Accounting UI",
    groupCode: "G6",
    descriptionAr: "واجهة لإدارة الحسابات والقيود والتقارير المالية",
    descriptionEn: "UI for accounts, entries, and financial reports",
    type: "Frontend", priority: "Critical", status: "NOT_STARTED",
    dependencies: ["G6-T01", "G6-T02", "G6-T04", "G0-T04"],
    acceptanceCriteriaAr: "واجهة شاملة للنظام المحاسبي",
    implementationNotesAr: "Chart of accounts tree view مع drill-down",
  },

  // ── G7: Integration & API ───────────────────────────────────────────────
  {
    id: "G7-T01", number: "G7-01",
    nameAr: "واجهات برمجة التطبيقات العامة", nameEn: "Public REST APIs",
    groupCode: "G7",
    descriptionAr: "إنشاء APIs عامة لكل كيانات ERP مع OpenAPI docs",
    descriptionEn: "Create public REST APIs for all ERP entities with OpenAPI docs",
    type: "Backend", priority: "High", status: "NOT_STARTED",
    dependencies: ["G0-T02"],
    acceptanceCriteriaAr: "APIs موثقة مع Swagger/OpenAPI",
    implementationNotesAr: "NestJS Swagger decorators",
  },
  {
    id: "G7-T02", number: "G7-02",
    nameAr: "ربط الأنظمة الخارجية", nameEn: "External System Integration",
    groupCode: "G7",
    descriptionAr: "نظامربط مع الأنظمة الخارجية عبر EDI وwebhooks",
    descriptionEn: "Integration with external systems via EDI and webhooks",
    type: "Backend", priority: "Medium", status: "NOT_STARTED",
    dependencies: ["G7-T01"],
    acceptanceCriteriaAr: "webhooks لإشعارات الأحداث",
    implementationNotesAr: "Webhook service مع retry logic",
  },
  {
    id: "G7-T03", number: "G7-03",
    nameAr: "استيراد وتصدير البيانات", nameEn: "Data Import & Export",
    groupCode: "G7",
    descriptionAr: "استيراد/تصدير CSV وExcel لجميع الكيانات",
    descriptionEn: "CSV/Excel import/export for all entities",
    type: "Backend", priority: "High", status: "NOT_STARTED",
    dependencies: ["G7-T01"],
    acceptanceCriteriaAr: "استيراد وتصدير لـ 10+ كيانات",
    implementationNotesAr: "ExcelJS + CSV parser مع validation",
  },
  {
    id: "G7-T04", number: "G7-04",
    nameAr: "واجهة التكامل", nameEn: "Integration UI",
    groupCode: "G7",
    descriptionAr: "واجهة لإدارة الربط والبيانات المستوردة/المُصدَّرة",
    descriptionEn: "UI for managing integrations and imported/exported data",
    type: "Frontend", priority: "Medium", status: "NOT_STARTED",
    dependencies: ["G7-T01", "G7-T02", "G0-T04"],
    acceptanceCriteriaAr: "لوحة إدارة للربط والاستيراد/التصدير",
    implementationNotesAr: "Integration dashboard مع status indicators",
  },

  // ── G8: Analytics & Reporting ───────────────────────────────────────────
  {
    id: "G8-T01", number: "G8-01",
    nameAr: "لوحات التحليلات", nameEn: "Analytics Dashboards",
    groupCode: "G8",
    descriptionAr: "إنشاء لوحات تحليلات للمبيعات والمشتريات والمخزون",
    descriptionEn: "Create analytics dashboards for sales, procurement, inventory",
    type: "Backend", priority: "High", status: "NOT_STARTED",
    dependencies: ["G6-T04"],
    acceptanceCriteriaAr: "3 لوحات تحليلات أساسية",
    implementationNotesAr: "Analytics service مع aggregation queries",
  },
  {
    id: "G8-T02", number: "G8-02",
    nameAr: "التقارير الاستخباراتية", nameEn: "Business Intelligence Reports",
    groupCode: "G8",
    descriptionAr: "تقارير BI متقدمة مع رسوم بيانية تفاعلية",
    descriptionEn: "Advanced BI reports with interactive charts",
    type: "Backend", priority: "Medium", status: "NOT_STARTED",
    dependencies: ["G8-T01"],
    acceptanceCriteriaAr: "تقارير قابلة للتصدير مع رسوم بيانية",
    implementationNotesAr: "Chart.js integration مع PDF export",
  },
  {
    id: "G8-T03", number: "G8-03",
    nameAr: "التنبؤ بالمبيعات", nameEn: "Sales Forecasting",
    groupCode: "G8",
    descriptionAr: "نماذج تنبؤ بالمبيعات بناء على البيانات التاريخية",
    descriptionEn: "Sales forecasting models based on historical data",
    type: "Backend", priority: "Low", status: "NOT_STARTED",
    dependencies: ["G8-T01"],
    acceptanceCriteriaAr: "تنبؤات شهري/ربع سنوي",
    implementationNotesAr: "Simple moving average + trend analysis",
  },
  {
    id: "G8-T04", number: "G8-04",
    nameAr: "واجهة التحليلات", nameEn: "Analytics UI",
    groupCode: "G8",
    descriptionAr: "واجهة لعرض اللوحات والتقارير التحليلية",
    descriptionEn: "UI for analytics dashboards and reports",
    type: "Frontend", priority: "High", status: "NOT_STARTED",
    dependencies: ["G8-T01", "G8-T02", "G0-T04"],
    acceptanceCriteriaAr: "لوحة تحليلات تفاعلية مع فلاتر",
    implementationNotesAr: "Dashboard layout مع responsive charts",
  },
];
