package com.sanad.platform.organization.domain;

import com.sanad.platform.tenant.domain.Tenant;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.EntityListeners;
import jakarta.persistence.EnumType;
import jakarta.persistence.Enumerated;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.Table;
import jakarta.persistence.UniqueConstraint;
import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.NotNull;
import jakarta.validation.constraints.Size;
import org.springframework.data.annotation.CreatedDate;
import org.springframework.data.annotation.LastModifiedDate;
import org.springframework.data.jpa.domain.support.AuditingEntityListener;

import java.time.Instant;
import java.util.Objects;
import java.util.UUID;

/**
 * JPA entity representing an Organization within a {@link Tenant}.
 *
 * <p>An Organization is the first operational aggregate built on top of
 * the Tenant aggregate. It is the container for future ERP, CRM, HRM,
 * Accounting, and Commerce modules. Each Organization belongs to
 * exactly one Tenant and has a unique name within that Tenant.</p>
 *
 * <p>Stage 0 implementation: no business methods beyond equals/hashCode/
 * toString. Behavior (activate, archive, transfer) will be added in later
 * stages alongside the application service layer.</p>
 */
@Entity
@Table(
        name = "organizations",
        uniqueConstraints = @UniqueConstraint(
                name = "uk_organizations_tenant_name",
                columnNames = {"tenant_id", "name"}
        )
)
@EntityListeners(AuditingEntityListener.class)
public class Organization {

    /** Surrogate primary key. UUID v4 generated by the application. */
    @Id
    @GeneratedValue(strategy = GenerationType.UUID)
    @Column(name = "id", nullable = false, updatable = false, columnDefinition = "uuid")
    private UUID id;

    /**
     * The Tenant this Organization belongs to. Many-to-one relationship;
     * lazy-loaded to avoid N+1 issues when only the tenant ID is needed.
     * The FK column is {@code tenant_id}, NOT NULL.
     *
     * <p>Spring Data JPA query methods (e.g. {@code findByTenant(...)})
     * traverse this relationship, so callers pass a Tenant reference.
     * For ID-only lookups, see {@link #tenantId}.</p>
     */
    @ManyToOne(fetch = FetchType.LAZY, optional = false)
    @JoinColumn(name = "tenant_id", nullable = false,
            foreignKey = @jakarta.persistence.ForeignKey(name = "fk_organizations_tenant"))
    private Tenant tenant;

    /**
     * Read-only mirror of {@link #tenant}'s ID, mapped to the same
     * {@code tenant_id} column via {@code insertable=false, updatable=false}.
     * This allows Spring Data JPA repository methods to use
     * {@code findByTenantId(UUID)} directly without traversing the
     * {@code tenant} proxy, which keeps repository queries simple and
     * avoids lazy-loading side effects.
     */
    @Column(name = "tenant_id", nullable = false, insertable = false, updatable = false,
            columnDefinition = "uuid")
    private UUID tenantId;

    /** Human-readable organization name (e.g. "Acme Riyadh Branch"). Unique per tenant. */
    @NotBlank
    @Size(max = 200)
    @Column(name = "name", nullable = false, length = 200)
    private String name;

    /** Optional longer description of the organization. */
    @Size(max = 1000)
    @Column(name = "description", length = 1000)
    private String description;

    /** Current lifecycle status. */
    @NotNull
    @Enumerated(EnumType.STRING)
    @Column(name = "status", nullable = false, length = 20)
    private OrganizationStatus status;

    /** Audit: when the row was first persisted. Set by JPA auditing. */
    @CreatedDate
    @Column(name = "created_at", nullable = false, updatable = false)
    private Instant createdAt;

    /** Audit: when the row was last modified. Set by JPA auditing. */
    @LastModifiedDate
    @Column(name = "updated_at", nullable = false)
    private Instant updatedAt;

    // ------------------------------------------------------------
    // Constructors
    // ------------------------------------------------------------

    /** No-arg constructor required by JPA. */
    protected Organization() {
    }

    public Organization(Tenant tenant, String name, String description, OrganizationStatus status) {
        this.tenant = tenant;
        this.name = name;
        this.description = description;
        this.status = status;
    }

    // ------------------------------------------------------------
    // Getters / Setters
    // ------------------------------------------------------------

    public UUID getId() {
        return id;
    }

    public void setId(UUID id) {
        this.id = id;
    }

    public Tenant getTenant() {
        return tenant;
    }

    public void setTenant(Tenant tenant) {
        this.tenant = tenant;
    }

    /**
     * Convenience accessor for the tenant ID. Returns the JPA-managed
     * {@link #tenantId} mirror field which is populated on entity load
     * via the {@code tenant_id} column mapping. Does NOT trigger lazy
     * loading of the {@link #tenant} relationship.
     */
    public UUID getTenantId() {
        return tenantId;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public OrganizationStatus getStatus() {
        return status;
    }

    public void setStatus(OrganizationStatus status) {
        this.status = status;
    }

    public Instant getCreatedAt() {
        return createdAt;
    }

    public void setCreatedAt(Instant createdAt) {
        this.createdAt = createdAt;
    }

    public Instant getUpdatedAt() {
        return updatedAt;
    }

    public void setUpdatedAt(Instant updatedAt) {
        this.updatedAt = updatedAt;
    }

    // ------------------------------------------------------------
    // equals / hashCode / toString
    // ------------------------------------------------------------

    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (!(o instanceof Organization that)) {
            return false;
        }
        // Compare by ID if both persisted, otherwise by (tenantId, name)
        if (id != null && that.id != null) {
            return Objects.equals(id, that.id);
        }
        return Objects.equals(getTenantId(), that.getTenantId())
                && Objects.equals(name, that.name);
    }

    @Override
    public int hashCode() {
        // Hash by tenant ID + name (stable pre- and post-persist)
        return Objects.hash(getTenantId(), name);
    }

    @Override
    public String toString() {
        return "Organization{" +
                "id=" + id +
                ", tenantId=" + getTenantId() +
                ", name='" + name + '\'' +
                ", description='" + (description != null && description.length() > 50
                        ? description.substring(0, 50) + "..." : description) + '\'' +
                ", status=" + status +
                ", createdAt=" + createdAt +
                ", updatedAt=" + updatedAt +
                '}';
    }
}
