package com.sanad.platform.organization.domain;

import com.sanad.platform.tenant.domain.Tenant;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.EntityListeners;
import jakarta.persistence.EnumType;
import jakarta.persistence.Enumerated;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.Table;
import jakarta.persistence.UniqueConstraint;
import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.NotNull;
import jakarta.validation.constraints.Size;
import org.springframework.data.annotation.CreatedDate;
import org.springframework.data.annotation.LastModifiedDate;
import org.springframework.data.jpa.domain.support.AuditingEntityListener;

import java.time.Instant;
import java.util.Objects;
import java.util.UUID;

/**
 * JPA entity representing an Organization within a {@link Tenant} in the
 * SANAD multi-tenant platform.
 *
 * <p>An Organization is the first operational aggregate linked to a Tenant.
 * Multiple Organizations may exist under a single Tenant, each representing
 * a distinct business unit (e.g. a branch, a subsidiary, a brand). All
 * operational modules (ERP, CRM, HRM, Accounting, Commerce) will reference
 * an Organization as their immediate parent.</p>
 *
 * <p>The pair (tenantId, name) is enforced as unique at the database level
 * so that two Organizations under the same Tenant cannot share a name,
 * while Organizations under different Tenants may.</p>
 *
 * <p>Stage 0 (this class) intentionally contains no business methods beyond
 * equals/hashCode/toString. Behaviour will be added in subsequent stages
 * alongside the application service layer.</p>
 */
@Entity
@Table(
        name = "organizations",
        uniqueConstraints = @UniqueConstraint(
                name = "uk_organizations_tenant_name",
                columnNames = {"tenant_id", "name"}
        )
)
@EntityListeners(AuditingEntityListener.class)
public class Organization {

    /** Surrogate primary key. UUID v4 generated by the application. */
    @Id
    @GeneratedValue(strategy = GenerationType.UUID)
    @Column(name = "id", nullable = false, updatable = false, columnDefinition = "uuid")
    private UUID id;

    /**
     * The Tenant this Organization belongs to. Modeled as a @ManyToOne
     * relation so that JPA can lazy-load the parent Tenant when needed.
     * The FK column is {@code tenant_id}, NOT NULL because every
     * Organization must belong to exactly one Tenant.
     */
    @ManyToOne(fetch = jakarta.persistence.FetchType.LAZY)
    @JoinColumn(
            name = "tenant_id",
            nullable = false,
            updatable = false,
            foreignKey = @jakarta.persistence.ForeignKey(name = "fk_organizations_tenant")
    )
    private Tenant tenant;

    /** Human-readable Organization name (e.g. "Acme Riyadh Branch"). */
    @NotBlank
    @Size(max = 200)
    @Column(name = "name", nullable = false, length = 200)
    private String name;

    /** Optional longer description of the Organization. */
    @Size(max = 1000)
    @Column(name = "description", length = 1000)
    private String description;

    /** Current lifecycle status of the Organization. */
    @NotNull
    @Enumerated(EnumType.STRING)
    @Column(name = "status", nullable = false, length = 20)
    private OrganizationStatus status;

    /** Audit: when the row was first persisted. Set by JPA auditing. */
    @CreatedDate
    @Column(name = "created_at", nullable = false, updatable = false)
    private Instant createdAt;

    /** Audit: when the row was last modified. Set by JPA auditing. */
    @LastModifiedDate
    @Column(name = "updated_at", nullable = false)
    private Instant updatedAt;

    // ------------------------------------------------------------
    // Constructors
    // ------------------------------------------------------------

    /** No-arg constructor required by JPA. */
    protected Organization() {
    }

    public Organization(Tenant tenant, String name, String description, OrganizationStatus status) {
        this.tenant = tenant;
        this.name = name;
        this.description = description;
        this.status = status;
    }

    // ------------------------------------------------------------
    // Getters / Setters
    // ------------------------------------------------------------

    public UUID getId() {
        return id;
    }

    public void setId(UUID id) {
        this.id = id;
    }

    public Tenant getTenant() {
        return tenant;
    }

    public void setTenant(Tenant tenant) {
        this.tenant = tenant;
    }

    /**
     * Convenience accessor exposing the Tenant's UUID directly, without
     * forcing callers to navigate the @ManyToOne relation (which would
     * trigger a lazy load). Used by repository query methods.
     */
    public UUID getTenantId() {
        return tenant != null ? tenant.getId() : null;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public OrganizationStatus getStatus() {
        return status;
    }

    public void setStatus(OrganizationStatus status) {
        this.status = status;
    }

    public Instant getCreatedAt() {
        return createdAt;
    }

    public void setCreatedAt(Instant createdAt) {
        this.createdAt = createdAt;
    }

    public Instant getUpdatedAt() {
        return updatedAt;
    }

    public void setUpdatedAt(Instant updatedAt) {
        this.updatedAt = updatedAt;
    }

    // ------------------------------------------------------------
    // equals / hashCode / toString
    // ------------------------------------------------------------

    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (!(o instanceof Organization that)) {
            return false;
        }
        // If both have IDs, compare by ID; otherwise compare by (tenantId, name).
        if (id != null && that.id != null) {
            return Objects.equals(id, that.id);
        }
        return Objects.equals(getTenantId(), that.getTenantId())
                && Objects.equals(name, that.name);
    }

    @Override
    public int hashCode() {
        // Hash by (tenantId, name) — natural composite key — so hash is
        // stable pre- and post-persist.
        return Objects.hash(getTenantId(), name);
    }

    @Override
    public String toString() {
        return "Organization{" +
                "id=" + id +
                ", tenantId=" + getTenantId() +
                ", name='" + name + '\'' +
                ", status=" + status +
                ", createdAt=" + createdAt +
                ", updatedAt=" + updatedAt +
                '}';
    }
}
