package com.sanad.platform.organization.domain;

import com.sanad.platform.tenant.domain.Tenant;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.EntityListeners;
import jakarta.persistence.EnumType;
import jakarta.persistence.Enumerated;
import jakarta.persistence.FetchType;
import jakarta.persistence.ForeignKey;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.Table;
import jakarta.persistence.UniqueConstraint;
import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.NotNull;
import jakarta.validation.constraints.Size;
import org.springframework.data.annotation.CreatedDate;
import org.springframework.data.annotation.LastModifiedDate;
import org.springframework.data.jpa.domain.support.AuditingEntityListener;

import java.time.Instant;
import java.util.Objects;
import java.util.UUID;

/**
 * JPA entity representing an Organization aggregate within the SANAD platform.
 *
 * <p>An Organization is the first operational aggregate built on top of the
 * Tenant aggregate. It is the container for future ERP, CRM, HRM, Accounting,
 * and Commerce modules. Each Organization belongs to exactly one Tenant and
 * has a unique name within that Tenant.</p>
 *
 * <h2>Aggregate Consistency (DDD)</h2>
 *
 * <p>Per DDD rules, an Organization aggregate MUST reference its parent
 * Tenant through a direct entity relationship ({@code @ManyToOne Tenant}),
 * never through a bare {@code UUID tenantId} field. This enforces the
 * invariant that an Organization cannot exist without a Tenant entity,
 * and prevents application code from bypassing the Tenant aggregate.</p>
 *
 * <p>Concretely:</p>
 * <ul>
 *   <li>There is NO {@code private UUID tenantId} field on this entity.</li>
 *   <li>There is NO {@code setTenantId(UUID)} method.</li>
 *   <li>The only way to construct an Organization in application code is via
 *       {@link #Organization(Tenant, String, String, OrganizationStatus)},
 *       which requires a {@link Tenant} entity reference.</li>
 *   <li>The {@code tenant_id} database column is mapped exclusively through
 *       the {@link #tenant} {@code @ManyToOne} relationship.</li>
 *   <li>Repository query methods that accept a {@code UUID tenantId}
 *       parameter use explicit JPQL ({@code o.tenant.id = :tenantId}) to
 *       traverse the relationship rather than relying on a denormalized
 *       field on this entity.</li>
 * </ul>
 *
 * <p>Stage 0 implementation: no business methods beyond equals/hashCode/
 * toString. Behavior (activate, archive, transfer) will be added in later
 * stages alongside the application service layer.</p>
 */
@Entity
@Table(
        name = "organizations",
        uniqueConstraints = @UniqueConstraint(
                name = "uk_organizations_tenant_name",
                columnNames = {"tenant_id", "name"}
        )
)
@EntityListeners(AuditingEntityListener.class)
public class Organization {

    /** Surrogate primary key. UUID v4 generated by the application. */
    @Id
    @GeneratedValue(strategy = GenerationType.UUID)
    @Column(name = "id", nullable = false, updatable = false, columnDefinition = "uuid")
    private UUID id;

    /**
     * The Tenant this Organization belongs to. This is the CANONICAL
     * reference to the parent aggregate; there is no separate
     * {@code tenantId} field on this entity.
     *
     * <p>The {@code tenant_id} database column is mapped exclusively
     * through this {@code @ManyToOne} relationship. All access to the
     * tenant identity in application code must go through
     * {@code organization.getTenant().getId()} (or equivalent) to
     * preserve DDD aggregate consistency.</p>
     */
    @ManyToOne(fetch = FetchType.LAZY, optional = false)
    @JoinColumn(
            name = "tenant_id",
            nullable = false,
            foreignKey = @ForeignKey(name = "fk_organizations_tenant")
    )
    private Tenant tenant;

    /** Human-readable organization name (e.g. "Acme Riyadh Branch"). Unique per tenant. */
    @NotBlank
    @Size(max = 200)
    @Column(name = "name", nullable = false, length = 200)
    private String name;

    /** Optional longer description of the organization. */
    @Size(max = 1000)
    @Column(name = "description", length = 1000)
    private String description;

    /** Current lifecycle status. */
    @NotNull
    @Enumerated(EnumType.STRING)
    @Column(name = "status", nullable = false, length = 20)
    private OrganizationStatus status;

    /** Audit: when the row was first persisted. Set by JPA auditing. */
    @CreatedDate
    @Column(name = "created_at", nullable = false, updatable = false)
    private Instant createdAt;

    /** Audit: when the row was last modified. Set by JPA auditing. */
    @LastModifiedDate
    @Column(name = "updated_at", nullable = false)
    private Instant updatedAt;

    // ------------------------------------------------------------
    // Constructors
    // ------------------------------------------------------------

    /**
     * Protected no-arg constructor required by JPA.
     *
     * <p>Application code MUST NOT call this directly. Use
     * {@link #Organization(Tenant, String, String, OrganizationStatus)}
     * to construct a new Organization.</p>
     */
    protected Organization() {
    }

    /**
     * Create a new Organization belonging to the given Tenant.
     *
     * <p>This is the ONLY way to construct an Organization in application
     * code. A {@link Tenant} entity reference is required — the tenant
     * identity cannot be supplied as a bare {@link UUID}, which enforces
     * the DDD aggregate-consistency invariant.</p>
     *
     * <p>Callers are expected to first load the Tenant aggregate via
     * {@code tenantRepository.findById(tenantId)} and then pass the
     * resolved entity to this constructor.</p>
     *
     * @param tenant      the parent Tenant aggregate (must not be null)
     * @param name        human-readable name (max 200 chars, must not be blank)
     * @param description longer description (max 1000 chars, may be null)
     * @param status      initial lifecycle status (must not be null)
     */
    public Organization(Tenant tenant, String name, String description, OrganizationStatus status) {
        this.tenant = tenant;
        this.name = name;
        this.description = description;
        this.status = status;
    }

    // ------------------------------------------------------------
    // Getters / Setters
    //
    // NOTE: No getTenantId() / setTenantId() exists on this entity.
    // All access to the tenant identity must go through the Tenant
    // aggregate reference returned by getTenant().
    // ------------------------------------------------------------

    public UUID getId() {
        return id;
    }

    /**
     * @return the parent Tenant aggregate (never null for a persisted entity)
     */
    public Tenant getTenant() {
        return tenant;
    }

    /**
     * Replace the parent Tenant reference. Exposed for JPA entity-state
     * transitions and rare administrative transfer use cases. Application
     * code should normally not call this directly; tenant reassignment
     * belongs in a dedicated domain service (added in a future stage).
     */
    public void setTenant(Tenant tenant) {
        this.tenant = tenant;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public OrganizationStatus getStatus() {
        return status;
    }

    public void setStatus(OrganizationStatus status) {
        this.status = status;
    }

    public Instant getCreatedAt() {
        return createdAt;
    }

    public Instant getUpdatedAt() {
        return updatedAt;
    }

    // ------------------------------------------------------------
    // equals / hashCode / toString
    // ------------------------------------------------------------

    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (!(o instanceof Organization that)) {
            return false;
        }
        // Compare by ID if both persisted, otherwise by (tenant.id, name)
        if (id != null && that.id != null) {
            return Objects.equals(id, that.id);
        }
        return Objects.equals(this.tenantIdentity(), that.tenantIdentity())
                && Objects.equals(name, that.name);
    }

    @Override
    public int hashCode() {
        // Hash by tenant.id + name (stable pre- and post-persist).
        // Uses tenantIdentity() to keep the logic centralized.
        return Objects.hash(this.tenantIdentity(), name);
    }

    @Override
    public String toString() {
        return "Organization{" +
                "id=" + id +
                ", tenantId=" + tenantIdentity() +
                ", name='" + name + '\'' +
                ", description='" + (description != null && description.length() > 50
                        ? description.substring(0, 50) + "..." : description) + '\'' +
                ", status=" + status +
                ", createdAt=" + createdAt +
                ", updatedAt=" + updatedAt +
                '}';
    }

    /**
     * Internal helper that derives the tenant's UUID from the
     * {@link #tenant} relationship. This is a private convenience for
     * equals/hashCode/toString only; it is NOT exposed as a public
     * getter to prevent application code from depending on a bare
     * tenant identity outside the Tenant aggregate.
     */
    private UUID tenantIdentity() {
        return tenant != null ? tenant.getId() : null;
    }
}
