/**
 * HR Execution Data
 * -----------------
 * Business data for HR execution groups and tasks.
 *
 * IMPORTANT: This file contains ONLY business data.
 * All execution logic (types, calculators, validators, constants)
 * MUST be imported from the shared framework: @/lib/execution
 */

import type {
  GroupStatus,
  TaskType,
  TaskPriority,
  TaskStatus,
} from "../../lib/execution";

// ── HR-Specific Task Type ────────────────────────────────────────────────

/**
 * HR Task — Business data for an HR task.
 *
 * NOTE: This is NOT an ExecutionTask. The HrExecutionProvider
 * converts this to ExecutionTask when providing data to the framework.
 */
export interface HrTask {
  id: string;
  number: string;
  nameAr: string;
  nameEn: string;
  groupCode: string;
  descriptionAr: string;
  descriptionEn: string;
  type: TaskType;
  priority: TaskPriority;
  status: TaskStatus;
  dependencies: string[];
  acceptanceCriteriaAr: string;
  implementationNotesAr: string;
}

// ── HR Execution Groups ──────────────────────────────────────────────────

/**
 * HR Execution Groups — Business data for group definitions.
 *
 * NOTE: This is NOT an ExecutionGroup[]. The HrExecutionProvider
 * converts this to ExecutionGroup[] when providing data to the framework.
 */
export const HR_GROUP_DATA = [
  {
    code: "G0",
    titleAr: "الأساس: سجلات الموظفين والهيكل التنظيمي",
    titleEn: "Foundation: Employee Records & Org Structure",
    purposeAr: "تأسيس نظام الموظفين مع السجلات الأساسية والهيكل التنظيمي.",
    purposeEn: "Establish the employee system with core records and organizational structure.",
    status: "NOT_STARTED" as GroupStatus,
    dependencies: [],
    canParallelizeWith: [],
    stageReport: null,
  },
  {
    code: "G1",
    titleAr: "الميزات الأساسية: التوظيف والتأهيل",
    titleEn: "Core Features: Recruitment & Onboarding",
    purposeAr: "تنفيذ التوظيف وإجراءات التأهيل للموظفين الجدد.",
    purposeEn: "Implement recruitment workflows and new hire onboarding processes.",
    status: "NOT_STARTED" as GroupStatus,
    dependencies: ["G0"],
    canParallelizeWith: ["G2"],
    stageReport: null,
  },
  {
    code: "G2",
    titleAr: "الوقت والحضور: الجداول والإجازات",
    titleEn: "Time & Attendance: Timesheets & Leave",
    purposeAr: "إدارة حضور الموظفين وأوقات العمل وإجازاتهم.",
    purposeEn: "Manage employee attendance, work hours, and leave requests.",
    status: "NOT_STARTED" as GroupStatus,
    dependencies: ["G0"],
    canParallelizeWith: ["G1"],
    stageReport: null,
  },
  {
    code: "G3",
    titleAr: "الأداء: التقييمات والأهداف",
    titleEn: "Performance: Reviews & Goals",
    purposeAr: "نظام تقييم الأداء وأهداف الموظفين ودورات المراجعة.",
    purposeEn: "Performance evaluation system, employee goals, and review cycles.",
    status: "NOT_STARTED" as GroupStatus,
    dependencies: ["G1"],
    canParallelizeWith: ["G2"],
    stageReport: null,
  },
  {
    code: "G4",
    titleAr: "التكامل مع الرواتب",
    titleEn: "Payroll Integration",
    purposeAr: "ربط بيانات الموظفين والوقت والحضور بنظام الرواتب.",
    purposeEn: "Integrate employee data, time, and attendance with the payroll system.",
    status: "NOT_STARTED" as GroupStatus,
    dependencies: ["G2", "G3"],
    canParallelizeWith: [],
    stageReport: null,
  },
  {
    code: "G5",
    titleAr: "التحليلات والتقارير",
    titleEn: "Analytics & Reporting",
    purposeAr: "تقارير الموارد البشرية ولوحات التحليل والتقارير التشغيلية.",
    purposeEn: "HR reports, analytics dashboards, and operational reporting.",
    status: "NOT_STARTED" as GroupStatus,
    dependencies: ["G4"],
    canParallelizeWith: [],
    stageReport: null,
  },
];

// ── HR Tasks ─────────────────────────────────────────────────────────────

export const HR_TASKS: HrTask[] = [
  // ── G0: Foundation — Employee Records & Org Structure ──────────────────────
  {
    id: "G0-T01",
    number: "G0-01",
    nameAr: "إنشاء جدول الموظفين الأساسي",
    nameEn: "Create core employees table",
    groupCode: "G0",
    descriptionAr: "جدول employees مع الحقول الأساسية: الاسم، الرقم الوظيفي، القسم، المنصب، تاريخ التعيين",
    descriptionEn: "Employees table with core fields: name, employee ID, department, position, hire date",
    type: "Database",
    priority: "Critical",
    status: "NOT_STARTED",
    dependencies: [],
    acceptanceCriteriaAr: "جدول employees يحتوي جميع الحقول الأساسية مع tenant_id",
    implementationNotesAr: "يتطلب UUID للمعرّف وقيود فريدة على الرقم الوظيفي",
  },
  {
    id: "G0-T02",
    number: "G0-02",
    nameAr: "إنشاء جدول الهيكل التنظيمي",
    nameEn: "Create organizational structure table",
    groupCode: "G0",
    descriptionAr: "جدول org_units للأقسام والإدارات مع علاقات الهرمية",
    descriptionEn: "org_units table for departments and divisions with hierarchy relationships",
    type: "Database",
    priority: "Critical",
    status: "NOT_STARTED",
    dependencies: ["G0-T01"],
    acceptanceCriteriaAr: "جدول org_units مع دعم الشجرة الهرمية (parent_id)",
    implementationNotesAr: "استخدام recursive CTE لل querying",
  },
  {
    id: "G0-T03",
    number: "G0-03",
    nameAr: "إنشاء واجهة إدارة الموظفين",
    nameEn: "Create employee management UI",
    groupCode: "G0",
    descriptionAr: "صفحة قائمة الموظفين مع البحث والتصفية وإضافة موظف جديد",
    descriptionEn: "Employee list page with search, filter, and add new employee",
    type: "Frontend",
    priority: "High",
    status: "NOT_STARTED",
    dependencies: ["G0-T01"],
    acceptanceCriteriaAr: "قائمة الموظفين تعرض جميع السجلات مع البحث والتصفية",
    implementationNotesAr: "استخدام جدول بيانات مع pagination",
  },
  {
    id: "G0-T04",
    number: "G0-04",
    nameAr: "إنشاء صفحة ملف الموظف",
    nameEn: "Create employee profile page",
    groupCode: "G0",
    descriptionAr: "صفحة ملف الموظف الشخصي مع جميع بياناته وسجله الوظيفي",
    descriptionEn: "Employee profile page with all personal data and employment history",
    type: "Frontend",
    priority: "High",
    status: "NOT_STARTED",
    dependencies: ["G0-T03"],
    acceptanceCriteriaAr: "ملف الموظف يعرض جميع البيانات الشخصية والوظيفية",
    implementationNotesAr: "تخطيط شريط جانبي مع تبويبات",
  },
  {
    id: "G0-T05",
    number: "G0-05",
    nameAr: "إنشاء مخطط الهيكل التنظيمي",
    nameEn: "Create org chart visualization",
    groupCode: "G0",
    descriptionAr: "رسم تلقائي للمخطط التنظيمي بناءً على بيانات org_units",
    descriptionEn: "Automatic org chart rendering based on org_units data",
    type: "Frontend",
    priority: "Medium",
    status: "NOT_STARTED",
    dependencies: ["G0-T02"],
    acceptanceCriteriaAr: "المخطط التنظيمي يعرض جميع الأقسام بشكل شجري",
    implementationNotesAr: "استخدام مكتبة رسم شجرة",
  },

  // ── G1: Core Features — Recruitment & Onboarding ──────────────────────────
  {
    id: "G1-T01",
    number: "G1-01",
    nameAr: "إنشاء جدول الوظائف المفتوحة",
    nameEn: "Create job openings table",
    groupCode: "G1",
    descriptionAr: "جدول job_openings للوظائف المفتوحة مع الوصف والمتطلبات والقسم",
    descriptionEn: "job_openings table for open positions with description, requirements, department",
    type: "Database",
    priority: "Critical",
    status: "NOT_STARTED",
    dependencies: [],
    acceptanceCriteriaAr: "جدول job_openings مع relationship مع org_units",
    implementationNotesAr: "دعم حالات: Draft, Open, On Hold, Closed",
  },
  {
    id: "G1-T02",
    number: "G1-02",
    nameAr: "إنشاء جدول المتقدمين للوظائف",
    nameEn: "Create job applicants table",
    groupCode: "G1",
    descriptionAr: "جدول applicants للمتقدمين مع السيرة الذاتية وحالة التقديم",
    descriptionEn: "applicants table for candidates with resume and application status",
    type: "Database",
    priority: "Critical",
    status: "NOT_STARTED",
    dependencies: ["G1-T01"],
    acceptanceCriteriaAr: "جدول applicants مع مسار التوظيف (pipeline stage)",
    implementationNotesAr: "دعم حالات: Applied, Screening, Interview, Offer, Hired, Rejected",
  },
  {
    id: "G1-T03",
    number: "G1-03",
    nameAr: "إنشاء واجهة لوحة التوظيف",
    nameEn: "Create recruitment dashboard UI",
    groupCode: "G1",
    descriptionAr: "لوحة التوظيف مع عرض الوظائف المفتوحة وعدد المتقدمين لكل مرحلة",
    descriptionEn: "Recruitment dashboard showing open positions and applicant counts per stage",
    type: "Frontend",
    priority: "High",
    status: "NOT_STARTED",
    dependencies: ["G1-T02"],
    acceptanceCriteriaAr: "لوحة التوظيف تعرض إحصائيات التوظيف الحالية",
    implementationNotesAr: "عرض Kanban للمتقدمين حسب مرحلة التوظيف",
  },
  {
    id: "G1-T04",
    number: "G1-04",
    nameAr: "إنشاء نموذج التأهيل الإلكتروني",
    nameEn: "Create digital onboarding checklist",
    groupCode: "G1",
    descriptionAr: "قائمة تأهيل تفاعلية للموظفين الجدد مع المهام والمتابعة",
    descriptionEn: "Interactive onboarding checklist for new hires with tasks and tracking",
    type: "Frontend",
    priority: "High",
    status: "NOT_STARTED",
    dependencies: ["G0-T01"],
    acceptanceCriteriaAr: "قائمة التأهيل تتبع إكمال المهام تلقائياً",
    implementationNotesAr: "ربط تلقائي عند تحويل المتقدم إلى موظف",
  },
  {
    id: "G1-T05",
    number: "G1-05",
    nameAr: "إنشاء API التوظيف والتأهيل",
    nameEn: "Create recruitment and onboarding APIs",
    groupCode: "G1",
    descriptionAr: "واجهات برمجية لإدارة الوظائف والمتقدمين وعمليات التأهيل",
    descriptionEn: "APIs for managing job openings, applicants, and onboarding processes",
    type: "Backend",
    priority: "Critical",
    status: "NOT_STARTED",
    dependencies: ["G1-T01", "G1-T02"],
    acceptanceCriteriaAr: "جميع CRUD operations تعمل مع عزل المستأجرين",
    implementationNotesAr: "REST API مع التحقق من الصلاحيات",
  },

  // ── G2: Time & Attendance — Timesheets & Leave ────────────────────────────
  {
    id: "G2-T01",
    number: "G2-01",
    nameAr: "إنشاء جدول سجل الحضور",
    nameEn: "Create attendance records table",
    groupCode: "G2",
    descriptionAr: "جدول attendance لتسجيل الدخول والخروج اليومي للموظفين",
    descriptionEn: "attendance table for daily employee clock-in and clock-out records",
    type: "Database",
    priority: "Critical",
    status: "NOT_STARTED",
    dependencies: [],
    acceptanceCriteriaAr: "جدول attendance مع timestamp وحساب ساعات العمل",
    implementationNotesAr: "دعم تسجيل يدوي ואلي",
  },
  {
    id: "G2-T02",
    number: "G2-02",
    nameAr: "إنشاء جدول طلبات الإجازات",
    nameEn: "Create leave requests table",
    groupCode: "G2",
    descriptionAr: "جدول leave_requests لطلب الإجازات مع الموافقة والرفض",
    descriptionEn: "leave_requests table for leave applications with approval workflow",
    type: "Database",
    priority: "Critical",
    status: "NOT_STARTED",
    dependencies: ["G0-T01"],
    acceptanceCriteriaAr: "جدول leave_requests مع أنواع الإجازات ورصيد الإجازات",
    implementationNotesAr: "أنواع: سنوية، مرضية، عادية، أمومة، أبوة",
  },
  {
    id: "G2-T03",
    number: "G2-03",
    nameAr: "إنشاء واجهة تسجيل الحضور",
    nameEn: "Create attendance tracking UI",
    groupCode: "G2",
    descriptionAr: "واجهة لتسجيل الدخول والخروج وعرض سجل الحضور الشهري",
    descriptionEn: "Interface for clock-in/out and viewing monthly attendance records",
    type: "Frontend",
    priority: "High",
    status: "NOT_STARTED",
    dependencies: ["G2-T01"],
    acceptanceCriteriaAr: "زر تسجيل دخول/خروج يعمل مع عرض السجل",
    implementationNotesAr: "عرض تقويم شهري مع ملخص ساعات العمل",
  },
  {
    id: "G2-T04",
    number: "G2-04",
    nameAr: "إنشاء واجهة إدارة الإجازات",
    nameEn: "Create leave management UI",
    groupCode: "G2",
    descriptionAr: "واجهة لطلب الإجازات وعرض الرصيد وموافقة المدير",
    descriptionEn: "Interface for requesting leave, viewing balance, and manager approval",
    type: "Frontend",
    priority: "High",
    status: "NOT_STARTED",
    dependencies: ["G2-T02"],
    acceptanceCriteriaAr: "طلب إجازة يمر بخط الموافقة (Manager -> HR)",
    implementationNotesAr: "عرض رصيد الإجازات المتبقية",
  },
  {
    id: "G2-T05",
    number: "G2-05",
    nameAr: "إنشاء تقرير الحضور الشهري",
    nameEn: "Create monthly attendance report",
    groupCode: "G2",
    descriptionAr: "تقرير شامل للحضور والغياب وساعات العمل الشهرية لكل موظف",
    descriptionEn: "Comprehensive monthly attendance, absence, and work hours report per employee",
    type: "Report",
    priority: "Medium",
    status: "NOT_STARTED",
    dependencies: ["G2-T03"],
    acceptanceCriteriaAr: "التقرير يعرض إحصائيات حضور شاملة لكل موظف",
    implementationNotesAr: "تصدير PDF و Excel",
  },

  // ── G3: Performance — Reviews & Goals ──────────────────────────────────────
  {
    id: "G3-T01",
    number: "G3-01",
    nameAr: "إنشاء جدول أهداف الأداء",
    nameEn: "Create performance goals table",
    groupCode: "G3",
    descriptionAr: "جدول performance_goals لأهداف الموظفين مع قياس التقدم",
    descriptionEn: "performance_goals table for employee goals with progress tracking",
    type: "Database",
    priority: "Critical",
    status: "NOT_STARTED",
    dependencies: [],
    acceptanceCriteriaAr: "جدول goals مع metric و target و progress",
    implementationNotesAr: "ربط مع employee_id و دعم دورة الأهداف السنوية",
  },
  {
    id: "G3-T02",
    number: "G3-02",
    nameAr: "إنشاء جدول تقييمات الأداء",
    nameEn: "Create performance reviews table",
    groupCode: "G3",
    descriptionAr: "جدول performance_reviews لتقييمات الأداء الدورية مع النتائج",
    descriptionEn: "performance_reviews table for periodic performance evaluations with results",
    type: "Database",
    priority: "Critical",
    status: "NOT_STARTED",
    dependencies: ["G3-T01"],
    acceptanceCriteriaAr: "جدول reviews مع تقييمات من المدير والزميل والذاتي",
    implementationNotesAr: "دعم 360-degree review",
  },
  {
    id: "G3-T03",
    number: "G3-03",
    nameAr: "إنشاء واجهة تقييم الأداء",
    nameEn: "Create performance evaluation UI",
    groupCode: "G3",
    descriptionAr: "واجهة لتقييم الأداء مع استمارات التقييم وعرض النتائج",
    descriptionEn: "Performance evaluation interface with rating forms and results display",
    type: "Frontend",
    priority: "High",
    status: "NOT_STARTED",
    dependencies: ["G3-T02"],
    acceptanceCriteriaAr: "نموذج تقييم يدعم التقييمات المتعددة والتعليقات",
    implementationNotesAr: "عرض تطور الأداء عبر الفترات الزمنية",
  },
  {
    id: "G3-T04",
    number: "G3-04",
    nameAr: "إنشاء واجهة تتبع الأهداف",
    nameEn: "Create goals tracking UI",
    groupCode: "G3",
    descriptionAr: "واجهة لمتابعة أهداف الموظفين مع تقييم التقدم والتحديث",
    descriptionEn: "Interface for tracking employee goals with progress assessment and updates",
    type: "Frontend",
    priority: "High",
    status: "NOT_STARTED",
    dependencies: ["G3-T01"],
    acceptanceCriteriaAr: "متابعة الأهداف مع مؤشرات الأداء الرئيسية",
    implementationNotesAr: "عرض سجل التحديثات لكل هدف",
  },

  // ── G4: Payroll Integration ────────────────────────────────────────────────
  {
    id: "G4-T01",
    number: "G4-01",
    nameAr: "إنشاء جدول بيانات الرواتب",
    nameEn: "Create payroll data table",
    groupCode: "G4",
    descriptionAr: "جدول payroll_data لربط بيانات الموظفين والوقت بحساب الرواتب",
    descriptionEn: "payroll_data table linking employee data and time to payroll calculations",
    type: "Database",
    priority: "Critical",
    status: "NOT_STARTED",
    dependencies: [],
    acceptanceCriteriaAr: "جدول payroll_data يربط employee_id مع work_hours و deductions",
    implementationNotesAr: "دعم كشف راتب شهري",
  },
  {
    id: "G4-T02",
    number: "G4-02",
    nameAr: "إنشاء محرك حساب الرواتب",
    nameEn: "Create payroll calculation engine",
    groupCode: "G4",
    descriptionAr: "محرك لحساب الرواتب بناءً على ساعات العمل والإجازات والخصومات",
    descriptionEn: "Engine for calculating payroll based on work hours, leave, and deductions",
    type: "Backend",
    priority: "Critical",
    status: "NOT_STARTED",
    dependencies: ["G4-T01"],
    acceptanceCriteriaAr: "المحرك يحسب الراتب الأساسي والبدلات والخصومات بدقة",
    implementationNotesAr: "دعم قواعد حساب متعددة حسب نوع الموظف",
  },
  {
    id: "G4-T03",
    number: "G4-03",
    nameAr: "إنشاء واجهة مراجعة كشف الراتب",
    nameEn: "Create payroll review UI",
    groupCode: "G4",
    descriptionAr: "واجهة لمراجعة كشف الراتب قبل الاعتماد مع عرض التفاصيل",
    descriptionEn: "Interface for reviewing payroll before approval with detailed breakdown",
    type: "Frontend",
    priority: "High",
    status: "NOT_STARTED",
    dependencies: ["G4-T02"],
    acceptanceCriteriaAr: "عرض كشف الراتب مع تفاصيل الدخل والخصومات",
    implementationNotesAr: "دعم التحقق والتعديل قبل الاعتماد",
  },

  // ── G5: Analytics & Reporting ──────────────────────────────────────────────
  {
    id: "G5-T01",
    number: "G5-01",
    nameAr: "إنشاء لوحة تحليلات الموارد البشرية",
    nameEn: "Create HR analytics dashboard",
    groupCode: "G5",
    descriptionAr: "لوحة تفاعلية لعرض إحصائيات الموارد البشرية الرئيسية",
    descriptionEn: "Interactive dashboard displaying key HR metrics and statistics",
    type: "Frontend",
    priority: "High",
    status: "NOT_STARTED",
    dependencies: [],
    acceptanceCriteriaAr: "اللوحة تعرض: عدد الموظفين، معدل التوظيف، معدل التخفي، متوسط الرواتب",
    implementationNotesAr: "استخدام رسوم بيانية تفاعلية",
  },
  {
    id: "G5-T02",
    number: "G5-02",
    nameAr: "إنشاء تقرير Attrition",
    nameEn: "Create attrition report",
    groupCode: "G5",
    descriptionAr: "تقرير شامل لمعدل التخفي وأسباب المغادرة والاتجاهات",
    descriptionEn: "Comprehensive attrition report with turnover rates, exit reasons, and trends",
    type: "Report",
    priority: "Medium",
    status: "NOT_STARTED",
    dependencies: ["G0-T01"],
    acceptanceCriteriaAr: "التقرير يحسب معدل التخفي الشهري والسنوي",
    implementationNotesAr: "تحليل حسب القسم والعمر والمدة",
  },
  {
    id: "G5-T03",
    number: "G5-03",
    nameAr: "إنشاء تقارير الموارد البشرية التشغيلية",
    nameEn: "Create operational HR reports",
    groupCode: "G5",
    descriptionAr: "تقارير تشغيلية: التوظيف النشط، الإجازات المعلقة، طلبات التأهيل",
    descriptionEn: "Operational reports: active recruitment, pending leaves, onboarding requests",
    type: "Report",
    priority: "Medium",
    status: "NOT_STARTED",
    dependencies: ["G5-T01"],
    acceptanceCriteriaAr: "تقارير تشغيلية تتحدث بشكل دوري",
    implementationNotesAr: "تصدير PDF و Excel مع جدولة التقارير",
  },
];
