#!/bin/bash
# ============================================================================
# SNAD — API Contract Compatibility Check (Stage 03A)
# ----------------------------------------------------------------------------
# Uses oasdiff (pinned version) to compare the runtime OpenAPI document
# produced by OpenApiContractExportTest against the committed baseline at
# docs/api-contracts/openapi-v1-baseline.yaml.
#
# Failure policy (NO SKIPS ALLOWED):
#   * Missing baseline          -> FAIL
#   * Missing current spec      -> FAIL
#   * oasdiff not installed     -> FAIL
#   * Any breaking change       -> FAIL
#   * oasdiff reports ERR/WARN  -> FAIL  (we use --fail-on=ERR)
#
# The script also runs the fixture-based self-test (tests/contracts/) so
# the breaking-change detection rules are proven on every invocation.
# ============================================================================
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "$0")/../.." && pwd)"
cd "$REPO_ROOT"

OASDIFF_VERSION="1.21.0"
OASDIFF_BIN="${OASDIFF_BIN:-oasdiff}"

BASELINE="docs/api-contracts/openapi-v1-baseline.yaml"
METADATA="docs/api-contracts/openapi-v1-baseline-metadata.json"
CURRENT="apps/sanad-platform/build/api-contract/openapi-current.json"
FIXTURES_DIR="tests/contracts"

echo "=== API Contract Compatibility Check (Stage 03A) ==="
echo "oasdiff version (pin): ${OASDIFF_VERSION}"

# -----------------------------------------------------------------------------
# 1. Verify oasdiff is available; if not, attempt a hermetic download.
# -----------------------------------------------------------------------------
if ! command -v "$OASDIFF_BIN" >/dev/null 2>&1; then
    echo "oasdiff not found on PATH — attempting hermetic install..."
    INSTALL_DIR="${HOME}/.cache/oasdiff/${OASDIFF_VERSION}"
    INSTALL_BIN="${INSTALL_DIR}/oasdiff"
    if [ ! -x "$INSTALL_BIN" ]; then
        mkdir -p "$INSTALL_DIR"
        URL="https://github.com/oasdiff/oasdiff/releases/download/v${OASDIFF_VERSION}/oasdiff_${OASDIFF_VERSION}_linux_amd64.tar.gz"
        echo "Downloading: $URL"
        curl -fsSL -o /tmp/oasdiff.tar.gz "$URL"
        tar -xzf /tmp/oasdiff.tar.gz -C "$INSTALL_DIR" oasdiff
        chmod +x "$INSTALL_BIN"
        rm -f /tmp/oasdiff.tar.gz
    fi
    OASDIFF_BIN="$INSTALL_BIN"
fi

ACTUAL_VERSION="$("$OASDIFF_BIN" --version 2>&1 | head -1)"
echo "Using: $OASDIFF_BIN ($ACTUAL_VERSION)"

# -----------------------------------------------------------------------------
# 2. Baseline must exist and be non-trivial.
# -----------------------------------------------------------------------------
if [ ! -f "$BASELINE" ]; then
    echo "FAIL: baseline missing at $BASELINE"
    echo "Run: bash scripts/dev/capture-openapi-baseline.sh"
    echo "RESULT: FAIL_NO_BASELINE"
    exit 1
fi

BASELINE_SIZE=$(wc -c <"$BASELINE" | tr -d ' ')
if [ "$BASELINE_SIZE" -lt 1000 ]; then
    echo "FAIL: baseline file is suspiciously small (${BASELINE_SIZE} bytes)"
    echo "RESULT: FAIL_BASELINE_TOO_SMALL"
    exit 1
fi

if [ ! -f "$METADATA" ]; then
    echo "FAIL: baseline metadata file missing at $METADATA"
    exit 1
fi
echo "Baseline: $BASELINE (${BASELINE_SIZE} bytes)"

# -----------------------------------------------------------------------------
# 3. Current runtime spec must exist (generated by OpenApiContractExportTest).
# -----------------------------------------------------------------------------
if [ ! -f "$CURRENT" ]; then
    echo "FAIL: runtime OpenAPI not found at $CURRENT"
    echo "Run: ./mvnw -B -ntp test -Dtest=OpenApiContractExportTest"
    echo "RESULT: FAIL_NO_CURRENT_SPEC"
    exit 1
fi

CURRENT_SIZE=$(wc -c <"$CURRENT" | tr -d ' ')
if [ "$CURRENT_SIZE" -lt 1000 ]; then
    echo "FAIL: current spec is suspiciously small (${CURRENT_SIZE} bytes)"
    exit 1
fi
echo "Current : $CURRENT (${CURRENT_SIZE} bytes)"

# -----------------------------------------------------------------------------
# 4. Run breaking-change diff (baseline = original, current = revision).
#    oasdiff exits 0 on no breaking changes, 1 on breaking change (with
#    --fail-on=ERR), 2 on usage error.
# -----------------------------------------------------------------------------
echo ""
echo "=== oasdiff breaking-change comparison ==="
DIFF_OUTPUT_FILE="apps/sanad-platform/build/api-contract/diff-report.txt"
mkdir -p "$(dirname "$DIFF_OUTPUT_FILE")"

# We deliberately do NOT pipe to head/tee so the exit code is preserved.
set +e
"$OASDIFF_BIN" breaking \
    --fail-on=ERR \
    --format=text \
    "$BASELINE" "$CURRENT" >"$DIFF_OUTPUT_FILE" 2>&1
DIFF_EXIT=$?
set -e

if [ "$DIFF_EXIT" -eq 0 ]; then
    echo "BREAKING_CHANGE_DETECTION: PASS (no breaking changes)"
elif [ "$DIFF_EXIT" -eq 1 ]; then
    echo "BREAKING_CHANGE_DETECTION: FAIL — breaking changes detected"
    echo "--- diff report ---"
    cat "$DIFF_OUTPUT_FILE"
    echo "--- end diff report ---"
    echo "RESULT: FAIL_BREAKING_CHANGE"
    exit 1
else
    echo "FAIL: oasdiff exited with $DIFF_EXIT (usage or internal error)"
    cat "$DIFF_OUTPUT_FILE"
    echo "RESULT: FAIL_OASDIFF_ERROR"
    exit 1
fi

# -----------------------------------------------------------------------------
# 5. Fixture-based self-test: prove the engine actually catches breaking
#    changes and allows non-breaking ones.
# -----------------------------------------------------------------------------
echo ""
echo "=== Fixture self-test ==="
if [ ! -d "$FIXTURES_DIR" ]; then
    echo "FAIL: fixtures directory missing at $FIXTURES_DIR"
    exit 1
fi

FIXTURE_PASS=0
FIXTURE_FAIL=0

run_fixture_case() {
    local name="$1"
    local base="$2"
    local rev="$3"
    local expect_breaking="$4"   # "breaking" or "non-breaking"

    set +e
    "$OASDIFF_BIN" breaking --fail-on=ERR --format=text "$base" "$rev" \
        >/tmp/oasdiff-fixture.out 2>&1
    local rc=$?
    set -e

    local actual
    if [ "$rc" -eq 0 ]; then
        actual="non-breaking"
    elif [ "$rc" -eq 1 ]; then
        actual="breaking"
    else
        echo "  [ERROR] $name — oasdiff exited with $rc"
        cat /tmp/oasdiff-fixture.out
        FIXTURE_FAIL=$((FIXTURE_FAIL + 1))
        return
    fi

    if [ "$actual" = "$expect_breaking" ]; then
        echo "  [PASS] $name (expected=$expect_breaking, actual=$actual)"
        FIXTURE_PASS=$((FIXTURE_PASS + 1))
    else
        echo "  [FAIL] $name (expected=$expect_breaking, actual=$actual)"
        cat /tmp/oasdiff-fixture.out
        FIXTURE_FAIL=$((FIXTURE_FAIL + 1))
    fi
}

for fixture_dir in "$FIXTURES_DIR"/breaking/*/; do
    [ -d "$fixture_dir" ] || continue
    name="breaking/$(basename "$fixture_dir")"
    base="${fixture_dir}baseline.yaml"
    rev="${fixture_dir}revision.yaml"
    if [ ! -f "$base" ] || [ ! -f "$rev" ]; then
        echo "  [SKIP] $name — missing baseline.yaml or revision.yaml"
        FIXTURE_FAIL=$((FIXTURE_FAIL + 1))
        continue
    fi
    run_fixture_case "$name" "$base" "$rev" "breaking"
done

for fixture_dir in "$FIXTURES_DIR"/non-breaking/*/; do
    [ -d "$fixture_dir" ] || continue
    name="non-breaking/$(basename "$fixture_dir")"
    base="${fixture_dir}baseline.yaml"
    rev="${fixture_dir}revision.yaml"
    if [ ! -f "$base" ] || [ ! -f "$rev" ]; then
        echo "  [SKIP] $name — missing baseline.yaml or revision.yaml"
        FIXTURE_FAIL=$((FIXTURE_FAIL + 1))
        continue
    fi
    run_fixture_case "$name" "$base" "$rev" "non-breaking"
done

echo ""
echo "Fixture summary: PASS=$FIXTURE_PASS  FAIL=$FIXTURE_FAIL"
if [ "$FIXTURE_FAIL" -gt 0 ]; then
    echo "RESULT: FAIL_FIXTURES"
    exit 1
fi

# -----------------------------------------------------------------------------
# 6. Final result.
# -----------------------------------------------------------------------------
echo ""
echo "=== Summary ==="
echo "Baseline:        $BASELINE"
echo "Current runtime: $CURRENT"
echo "Diff report:     $DIFF_OUTPUT_FILE"
echo "Fixtures:        PASS=$FIXTURE_PASS  FAIL=$FIXTURE_FAIL"
echo "RESULT: PASS — no breaking changes detected; engine verified by fixtures"
exit 0
