/**
 * AI Platform Execution Data
 * --------------------------
 * Business data for AI Platform execution groups and tasks.
 *
 * IMPORTANT: This file contains ONLY business data.
 * All execution logic (types, calculators, validators, constants)
 * MUST be imported from the shared framework: ../../lib/execution
 */

import type {
  GroupStatus,
  TaskType,
  TaskPriority,
  TaskStatus,
} from "../../lib/execution";

// ── AI Platform-Specific Task Type ──────────────────────────────────────────

/**
 * AI Platform Task — Business data for an AI Platform task.
 *
 * NOTE: This is NOT an ExecutionTask. The AiPlatformExecutionProvider
 * converts this to ExecutionTask when providing data to the framework.
 */
export interface AiPlatformTask {
  id: string;
  number: string;
  nameAr: string;
  nameEn: string;
  groupCode: string;
  descriptionAr: string;
  descriptionEn: string;
  type: TaskType;
  priority: TaskPriority;
  status: TaskStatus;
  dependencies: string[];
  acceptanceCriteriaAr: string;
  implementationNotesAr: string;
}

// ── AI Platform Execution Groups ────────────────────────────────────────────

/**
 * AI Platform Execution Groups — Business data for group definitions.
 *
 * NOTE: This is NOT an ExecutionGroup[]. The AiPlatformExecutionProvider
 * converts this to ExecutionGroup[] when providing data to the framework.
 */
export const AI_PLATFORM_GROUP_DATA = [
  {
    code: "G0",
    titleAr: "البنية التحتية للتعلم الآلي وسجل النماذج",
    titleEn: "ML Infrastructure & Model Registry",
    purposeAr: "تأسيس البنية التحتية الأساسية للتعلم الآلي وسجل النماذج المركزي.",
    purposeEn: "Establish core ML infrastructure and central model registry.",
    status: "NOT_STARTED" as GroupStatus,
    dependencies: [],
    canParallelizeWith: [],
    stageReport: null,
  },
  {
    code: "G1",
    titleAr: "التدريب والنشر والمراقبة الأساسية",
    titleEn: "Core Training, Deployment & Monitoring",
    purposeAr: "تنفيذ خطوط التدريب الآلي، نشر النماذج، والمراقبة الأساسية للأداء.",
    purposeEn: "Implement automated training pipelines, model deployment, and core performance monitoring.",
    status: "NOT_STARTED" as GroupStatus,
    dependencies: ["G0"],
    canParallelizeWith: ["G2", "G3"],
    stageReport: null,
  },
  {
    code: "G2",
    titleAr: "معالجة اللغات الطبيعية (NLP)",
    titleEn: "Natural Language Processing (NLP)",
    purposeAr: "تنفيذ خدمات تحليل النصوص، تحليل المشاعر، والترجمة التلقائية.",
    purposeEn: "Implement text analysis services, sentiment analysis, and automatic translation.",
    status: "NOT_STARTED" as GroupStatus,
    dependencies: ["G1"],
    canParallelizeWith: ["G3"],
    stageReport: null,
  },
  {
    code: "G3",
    titleAr: "الرؤية الحاسوبية ومعالجة الصور",
    titleEn: "Computer Vision & Image Processing",
    purposeAr: "تنفيذ خدمات معالجة الصور، التعرف الضوئي على الحروف (OCR)، واكتشاف الكائنات.",
    purposeEn: "Implement image processing, OCR, and object detection services.",
    status: "NOT_STARTED" as GroupStatus,
    dependencies: ["G1"],
    canParallelizeWith: ["G2"],
    stageReport: null,
  },
  {
    code: "G4",
    titleAr: "التحليلات التنبؤية والتوصيات",
    titleEn: "Predictive Analytics & Recommendations",
    purposeAr: "تنفيذ نماذج التنبؤ بالمستقبل، التوصيات الذكية، والتحليلات السيرية الزمنية.",
    purposeEn: "Implement forecasting models, intelligent recommendations, and time-series analytics.",
    status: "NOT_STARTED" as GroupStatus,
    dependencies: ["G1", "G2", "G3"],
    canParallelizeWith: [],
    stageReport: null,
  },
  {
    code: "G5",
    titleAr: "عمليات تعلم الآلة (MLOps)",
    titleEn: "Machine Learning Operations (MLOps)",
    purposeAr: "تنفيذ مراقبة النماذج في الإنتاج، إعادة التدريب التلقائي، وإدارة الدورات.",
    purposeEn: "Implement production model monitoring, automated retraining, and lifecycle management.",
    status: "NOT_STARTED" as GroupStatus,
    dependencies: ["G1"],
    canParallelizeWith: [],
    stageReport: null,
  },
  {
    code: "G6",
    titleAr: "التكامل والواجهات البرمجية",
    titleEn: "Integration & API",
    purposeAr: "تنفيذ واجهة REST API الشاملة، نظام الصلاحيات، وتكامل الخدمات مع النظام الأساسي.",
    purposeEn: "Implement comprehensive REST API, permission system, and platform service integration.",
    status: "NOT_STARTED" as GroupStatus,
    dependencies: ["G1", "G2", "G3", "G4", "G5"],
    canParallelizeWith: [],
    stageReport: null,
  },
];

// ── AI Platform Tasks ───────────────────────────────────────────────────────

export const AI_PLATFORM_TASKS: AiPlatformTask[] = [
  // ── G0: ML Infrastructure & Model Registry ─────────────────────────────────
  {
    id: "G0-T01",
    number: "G0-01",
    nameAr: "إنشاء مسار /ai-platform",
    nameEn: "Create /ai-platform route",
    groupCode: "G0",
    descriptionAr: "إنشاء مسار الصفحة الرئيسية لمنصة الذكاء الاصطناعي مع التخطيط المستقل",
    descriptionEn: "Create main AI Platform page route with independent layout",
    type: "Frontend",
    priority: "Critical",
    status: "NOT_STARTED",
    dependencies: [],
    acceptanceCriteriaAr: "المسار /ai-platform يفتح لوحة تحكم منصة الذكاء الاصطناعي",
    implementationNotesAr: "يجب أن يتبع نمط /crm مع تخطيط مستقل وشريط جانبي",
  },
  {
    id: "G0-T02",
    number: "G0-02",
    nameAr: "إنشاء جدول ai_models الرئيسي",
    nameEn: "Create main ai_models table",
    groupCode: "G0",
    descriptionAr: "إنشاء جدول سجل النماذج الرئيسي مع tenant_id وعلاقات التتبع",
    descriptionEn: "Create main model registry table with tenant_id and tracking relations",
    type: "Database",
    priority: "Critical",
    status: "NOT_STARTED",
    dependencies: [],
    acceptanceCriteriaAr: "جدول ai_models يحتوي tenant_id UUID NOT NULL مع فهارس أداء",
    implementationNotesAr: "يتطلب ترحيل Flyway مع فهرسة tenant_id كعمود رئيسي",
  },
  {
    id: "G0-T03",
    number: "G0-03",
    nameAr: "إنشاء جدول ai_model_versions",
    nameEn: "Create ai_model_versions table",
    groupCode: "G0",
    descriptionAr: "جدول إصدارات النماذج مع تتبع الإصدارات والمتانة",
    descriptionEn: "Model versions table with version tracking and durability",
    type: "Database",
    priority: "Critical",
    status: "NOT_STARTED",
    dependencies: ["G0-T02"],
    acceptanceCriteriaAr: "جدول ai_model_versions مع relationship صحيحة مع ai_models",
    implementationNotesAr: "كل إصدار يجب أن يحتوي metrics snapshot و artifacts reference",
  },
  {
    id: "G0-T04",
    number: "G0-04",
    nameAr: "إنشاء جدول ai_model_artifacts",
    nameEn: "Create ai_model_artifacts table",
    groupCode: "G0",
    descriptionAr: "جدول مكونات النماذج (أوزان، صيغ، تكوينات)",
    descriptionEn: "Model artifacts table (weights, formats, configurations)",
    type: "Database",
    priority: "High",
    status: "NOT_STARTED",
    dependencies: ["G0-T02"],
    acceptanceCriteriaAr: "جدول ai_model_artifacts يدعم التخزين المرجعي للملفات الكبيرة",
    implementationNotesAr: "يجب دعم ONNX، TensorFlow SavedModel، PyTorch، Hugging Face formats",
  },
  {
    id: "G0-T05",
    number: "G0-05",
    nameAr: "تنفيذ خدمة سجل النماذج",
    nameEn: "Implement model registry service",
    groupCode: "G0",
    descriptionAr: "خدمة backend لإدارة النماذج: إنشاء، تحديث، نسخ، أرشفة",
    descriptionEn: "Backend service for model management: create, update, archive, promote",
    type: "Backend",
    priority: "Critical",
    status: "NOT_STARTED",
    dependencies: ["G0-T02", "G0-T03"],
    acceptanceCriteriaAr: "API endpoints لإنشاء وتحديث وحذف النماذج مع tenant isolation",
    implementationNotesAr: "يجب دعم الترحيل بين البيئات (dev/staging/production)",
  },
  {
    id: "G0-T06",
    number: "G0-06",
    nameAr: "إنشاء لوحة تحكم سجل النماذج",
    nameEn: "Create model registry dashboard",
    groupCode: "G0",
    descriptionAr: "واجهة ويب لتصفح وإدارة سجل النماذج مع بحث وتصفية",
    descriptionEn: "Web interface for browsing and managing model registry with search and filtering",
    type: "Frontend",
    priority: "High",
    status: "NOT_STARTED",
    dependencies: ["G0-T01", "G0-T05"],
    acceptanceCriteriaAr: "لوحة تحكم تعرض جميع النماذج مع إحصائيات وحالة النشر",
    implementationNotesAr: "تسلسل شجري لعرض إصدارات كل نموذج",
  },

  // ── G1: Core Training, Deployment & Monitoring ─────────────────────────────
  {
    id: "G1-T01",
    number: "G1-01",
    nameAr: "إنشاء جدول ai_training_jobs",
    nameEn: "Create ai_training_jobs table",
    groupCode: "G1",
    descriptionAr: "جدول مهام التدريب مع الحالة والمعلمات وسجل التنفيذ",
    descriptionEn: "Training jobs table with status, parameters, and execution log",
    type: "Database",
    priority: "Critical",
    status: "NOT_STARTED",
    dependencies: ["G0-T02"],
    acceptanceCriteriaAr: "جدول ai_training_jobs مع tenant_id وعلاقة مع ai_models",
    implementationNotesAr: "يتطلب تسجيل المعلمات الفائقة (hyperparameters) كـ JSONB",
  },
  {
    id: "G1-T02",
    number: "G1-02",
    nameAr: "تنفيذ محرك التدريب الآلي",
    nameEn: "Implement automated training engine",
    groupCode: "G1",
    descriptionAr: "محرك لتنفيذ مهام التدريب مع دعم GPU/CPU والجدولة",
    descriptionEn: "Engine for executing training jobs with GPU/CPU support and scheduling",
    type: "Backend",
    priority: "Critical",
    status: "NOT_STARTED",
    dependencies: ["G1-T01"],
    acceptanceCriteriaAr: "المحرك ينفذ مهام التدريب ويُسجّل المقاييس (metrics) بشكل مستمر",
    implementationNotesAr: "دعم horovod للتدريب الموزع و MLflow لتسجيل المعلمات",
  },
  {
    id: "G1-T03",
    number: "G1-03",
    nameAr: "تنفيذ خدمة النشر (Deployment Service)",
    nameEn: "Implement deployment service",
    groupCode: "G1",
    descriptionAr: "خدمة لنشر النماذج كـ REST endpoints مع دعم A/B testing",
    descriptionEn: "Service to deploy models as REST endpoints with A/B testing support",
    type: "Backend",
    priority: "Critical",
    status: "NOT_STARTED",
    dependencies: ["G0-T05"],
    acceptanceCriteriaAr: "النموذج المنشور متاح عبر REST API مع latency < 100ms",
    implementationNotesAr: "دعم ONNX Runtime و TensorFlow Serving و TorchServe",
  },
  {
    id: "G1-T04",
    number: "G1-04",
    nameAr: "تنفيذ نظام قياس أداء النماذج",
    nameEn: "Implement model performance monitoring",
    groupCode: "G1",
    descriptionAr: "نظام لمراقبة مقاييس الأداء (latency, throughput, accuracy) في الوقت الحقيقي",
    descriptionEn: "System to monitor performance metrics (latency, throughput, accuracy) in real-time",
    type: "Backend",
    priority: "High",
    status: "NOT_STARTED",
    dependencies: ["G1-T03"],
    acceptanceCriteriaAr: "لوحة متابعة تعرض المقاييس الحية مع تنبيهات للانحرافات",
    implementationNotesAr: "استخدام Prometheus و Grafana أو بديل مدمج",
  },

  // ── G2: NLP ────────────────────────────────────────────────────────────────
  {
    id: "G2-T01",
    number: "G2-01",
    nameAr: "تنفيذ خدمة تحليل النصوص",
    nameEn: "Implement text analysis service",
    groupCode: "G2",
    descriptionAr: "خدمة لتحليل النصوص: استخراج الكيانات المسماة (NER)، تصنيف النصوص، واستخراج المواضيع",
    descriptionEn: "Service for text analysis: Named Entity Recognition (NER), text classification, and topic extraction",
    type: "Backend",
    priority: "Critical",
    status: "NOT_STARTED",
    dependencies: ["G0-T05"],
    acceptanceCriteriaAr: "API endpoint يحلل النص ويعيد الكيانات والتصنيفات بدقة > 90%",
    implementationNotesAr: "استخدام نموذج عربي مسبق التدريب مع دعم multilingual",
  },
  {
    id: "G2-T02",
    number: "G2-02",
    nameAr: "تنفيذ خدمة تحليل المشاعر",
    nameEn: "Implement sentiment analysis service",
    groupCode: "G2",
    descriptionAr: "خدمة لتحليل مشاعر النصوص: إيجابي/سلبي/محايد مع درجة الثقة",
    descriptionEn: "Service for sentiment analysis: positive/negative/neutral with confidence score",
    type: "Backend",
    priority: "High",
    status: "NOT_STARTED",
    dependencies: ["G2-T01"],
    acceptanceCriteriaAr: "تحليل المشاعر بدقة > 85% على النصوص العربية",
    implementationNotesAr: "دعم تحليل المشاعر على مستوى الجملة والفقرة والمستند",
  },
  {
    id: "G2-T03",
    number: "G2-03",
    nameAr: "تنفيذ خدمة الترجمة التلقائية",
    nameEn: "Implement machine translation service",
    groupCode: "G2",
    descriptionAr: "خدمة لترجمة النصوص بين العربية والإنجليزية وأخرى تلقائيًا",
    descriptionEn: "Service for automatic translation between Arabic, English, and other languages",
    type: "Backend",
    priority: "High",
    status: "NOT_STARTED",
    dependencies: ["G0-T05"],
    acceptanceCriteriaAr: "ترجمة جملية بدقة قابلة للاستخدام مع BLEU score > 30",
    implementationNotesAr: "استخدام نموذج transformer مخصص أو API خارجية كبديل",
  },
  {
    id: "G2-T04",
    number: "G2-04",
    nameAr: "تنفيذ واجهة NLP للمستخدمين",
    nameEn: "Implement NLP user interface",
    groupCode: "G2",
    descriptionAr: "واجهة ويب لتجربة خدمات NLP مع إمكانية رفع النصوص والتحقق من النتائج",
    descriptionEn: "Web interface for trying NLP services with text upload and result inspection",
    type: "Frontend",
    priority: "Medium",
    status: "NOT_STARTED",
    dependencies: ["G2-T01", "G2-T02"],
    acceptanceCriteriaAr: "صفحة تفاعلية تتيح اختبار جميع خدمات NLP",
    implementationNotesAr: "عرض النتائج بشكل مرئي مع تمييز الكيانات والألوان",
  },

  // ── G3: Computer Vision & Image Processing ─────────────────────────────────
  {
    id: "G3-T01",
    number: "G3-01",
    nameAr: "تنفيذ خدمة معالجة الصور",
    nameEn: "Implement image processing service",
    groupCode: "G3",
    descriptionAr: "خدمة لمعالجة الصور: تغيير الحجم، القص، تحسين الجودة، إزالة الخلفية",
    descriptionEn: "Service for image processing: resize, crop, enhancement, background removal",
    type: "Backend",
    priority: "Critical",
    status: "NOT_STARTED",
    dependencies: ["G0-T05"],
    acceptanceCriteriaAr: "API endpoint يعالج الصور ويُرجع النتيجة في < 2 ثانية",
    implementationNotesAr: "استخدام Sharp أو OpenCV مع دعم GPU عبر ONNX Runtime",
  },
  {
    id: "G3-T02",
    number: "G3-02",
    nameAr: "تنفيذ خدمة OCR متعددة اللغات",
    nameEn: "Implement multilingual OCR service",
    groupCode: "G3",
    descriptionAr: "خدمة للتعرف الضوئي على الحروف في الصور مع دعم العربية والإنجليزية",
    descriptionEn: "Service for optical character recognition with Arabic and English support",
    type: "Backend",
    priority: "Critical",
    status: "NOT_STARTED",
    dependencies: ["G3-T01"],
    acceptanceCriteriaAr: "OCR يستخرج النص بدقة > 95% من المستندات الممسوحة",
    implementationNotesAr: "استخدام Tesseract مع نماذج عربية أو نموذج TrOCR مخصص",
  },
  {
    id: "G3-T03",
    number: "G3-03",
    nameAr: "تنفيذ خدمة اكتشاف الكائنات",
    nameEn: "Implement object detection service",
    groupCode: "G3",
    descriptionAr: "خدمة لاكتشاف وتصنيف الكائنات في الصور مع تحديد الأماكنBounding Boxes",
    descriptionEn: "Service for detecting and classifying objects in images with bounding boxes",
    type: "Backend",
    priority: "High",
    status: "NOT_STARTED",
    dependencies: ["G3-T01"],
    acceptanceCriteriaAr: "اكتشاف الكائنات بدقة mAP > 70% على COCO dataset",
    implementationNotesAr: "استخدام YOLO أو EfficientDet مع ONNX Runtime",
  },
  {
    id: "G3-T04",
    number: "G3-04",
    nameAr: "تنفيذ واجهة الرؤية الحاسوبية",
    nameEn: "Implement computer vision UI",
    groupCode: "G3",
    descriptionAr: "واجهة ويب لتجربة خدمات الرؤية الحاسوبية مع عرض النتائج المرئية",
    descriptionEn: "Web interface for trying computer vision services with visual result display",
    type: "Frontend",
    priority: "Medium",
    status: "NOT_STARTED",
    dependencies: ["G3-T01", "G3-T02", "G3-T03"],
    acceptanceCriteriaAr: "صفحة تفاعلية تعرض النتائج مع bounding boxes ونصوص مستخرجة",
    implementationNotesAr: "عرض تفاعلي للصور مع canvas overlay للكائنات المكتشفة",
  },

  // ── G4: Predictive Analytics & Recommendations ─────────────────────────────
  {
    id: "G4-T01",
    number: "G4-01",
    nameAr: "تنفيذ خدمة التنبؤ بالمستقبل",
    nameEn: "Implement forecasting service",
    groupCode: "G4",
    descriptionAr: "خدمة للتنبؤ بالقيم المستقبلية باستخدام سلاسل زمنية (time series)",
    descriptionEn: "Service for predicting future values using time series analysis",
    type: "Backend",
    priority: "Critical",
    status: "NOT_STARTED",
    dependencies: ["G0-T05"],
    acceptanceCriteriaAr: "تنبؤ بدقة MAPE < 15% على بيانات المبيعات التاريخية",
    implementationNotesAr: "استخدام Prophet أو LSTM مع دعم seasonality و holidays",
  },
  {
    id: "G4-T02",
    number: "G4-02",
    nameAr: "تنفيذ خدمة التوصيات",
    nameEn: "Implement recommendation service",
    groupCode: "G4",
    descriptionAr: "خدمة لتوصيات ذكية باستخدام collaborative و content-based filtering",
    descriptionEn: "Service for intelligent recommendations using collaborative and content-based filtering",
    type: "Backend",
    priority: "High",
    status: "NOT_STARTED",
    dependencies: ["G0-T05"],
    acceptanceCriteriaAr: "التوصيات مخصصة لكل مستخدم مع click-through rate > 5%",
    implementationNotesAr: "استخدام ALS أو neural collaborative filtering مع دعم cold start",
  },
  {
    id: "G4-T03",
    number: "G4-03",
    nameAr: "تنفيذ لوحة التحليلات التنبؤية",
    nameEn: "Implement predictive analytics dashboard",
    groupCode: "G4",
    descriptionAr: "لوحة ويب تعرض التنبؤات والتوصيات مع إمكانية تخصيص النماذج",
    descriptionEn: "Web dashboard showing forecasts and recommendations with model customization",
    type: "Frontend",
    priority: "Medium",
    status: "NOT_STARTED",
    dependencies: ["G4-T01", "G4-T02"],
    acceptanceCriteriaAr: "لوحة تفاعلية تعرض التنبؤات مع مستويات الثقة والتوصيات",
    implementationNotesAr: "رسوم بيانية تفاعلية مع Recharts و filtres متعددة",
  },

  // ── G5: MLOps ──────────────────────────────────────────────────────────────
  {
    id: "G5-T01",
    number: "G5-01",
    nameAr: "تنفيذ مراقبة الانحراف (Drift Detection)",
    nameEn: "Implement drift detection",
    groupCode: "G5",
    descriptionAr: "نظام لاكتشاف انحراف البيانات والنموذج في الوقت الحقيقي",
    descriptionEn: "System for detecting data and model drift in real-time",
    type: "Backend",
    priority: "Critical",
    status: "NOT_STARTED",
    dependencies: ["G1-T04"],
    acceptanceCriteriaAr: "كشف انحراف البيانات (PSI > 0.2) وتنبيه المسؤولين",
    implementationNotesAr: "استخدام Population Stability Index و Kolmogorov-Smirnov test",
  },
  {
    id: "G5-T02",
    number: "G5-02",
    nameAr: "تنفيذ إعادة التدريب التلقائي",
    nameEn: "Implement automated retraining",
    groupCode: "G5",
    descriptionAr: "نوميجة لإعادة تدريب النماذج تلقائيًا عند انحراف الأداء",
    descriptionEn: "Workflow for automatically retraining models when performance degrades",
    type: "Backend",
    priority: "High",
    status: "NOT_STARTED",
    dependencies: ["G5-T01", "G1-T02"],
    acceptanceCriteriaAr: "إعادة تدريب تلقائية عند انحراف accuracy > 10% مع إشعار المسؤولين",
    implementationNotesAr: "استخدام Airflow أو Prefect لتنسيق خطوات إعادة التدريب",
  },
  {
    id: "G5-T03",
    number: "G5-03",
    nameAr: "تنفيذ إدارة دورة حياة النماذج",
    nameEn: "Implement model lifecycle management",
    groupCode: "G5",
    descriptionAr: "إدارة كاملة لدورة حياة النموذج:Development → Staging → Production → Archived",
    descriptionEn: "Full model lifecycle management: Development → Staging → Production → Archived",
    type: "Backend",
    priority: "High",
    status: "NOT_STARTED",
    dependencies: ["G0-T05"],
    acceptanceCriteriaAr: "إمكانية نقل النموذج بين المراحل مع موافقات وتخطيط",
    implementationNotesAr: "دعم promotion و rollback مع تسجيل كامل للأحداث",
  },
  {
    id: "G5-T04",
    number: "G5-04",
    nameAr: "تنفيذ لوحة MLOps",
    nameEn: "Implement MLOps dashboard",
    groupCode: "G5",
    descriptionAr: "لوحة ويب لمراقبة دورة حياة النماذج وصحة النماذج في الإنتاج",
    descriptionEn: "Web dashboard for monitoring model lifecycle and production model health",
    type: "Frontend",
    priority: "Medium",
    status: "NOT_STARTED",
    dependencies: ["G5-T01", "G5-T03"],
    acceptanceCriteriaAr: "لوحة تعرض حالة جميع النماذج المنتجة مع مقاييس الصحة",
    implementationNotesAr: "رسوم بيانية حية مع تحديث تلقائي كل 30 ثانية",
  },

  // ── G6: Integration & API ──────────────────────────────────────────────────
  {
    id: "G6-T01",
    number: "G6-01",
    nameAr: "تنفيذ REST API الشامل",
    nameEn: "Implement comprehensive REST API",
    groupCode: "G6",
    descriptionAr: "واجهة REST API شاملة لجميع خدمات منصة الذكاء الاصطناعي",
    descriptionEn: "Comprehensive REST API for all AI Platform services",
    type: "Backend",
    priority: "Critical",
    status: "NOT_STARTED",
    dependencies: ["G1-T03", "G2-T01", "G3-T01"],
    acceptanceCriteriaAr: "API endpoints لكل خدمة مع توثيق Swagger كامل",
    implementationNotesAr: "استخدام FastAPI مع OpenAPI auto-documentation و rate limiting",
  },
  {
    id: "G6-T02",
    number: "G6-02",
    nameAr: "نظام الصلاحيات والأمان",
    nameEn: "Permission and security system",
    groupCode: "G6",
    descriptionAr: "نظام صلاحيات مبني على الأدوار (RBAC) مع دعم tenant isolation",
    descriptionEn: "Role-based access control (RBAC) system with tenant isolation support",
    type: "Backend",
    priority: "Critical",
    status: "NOT_STARTED",
    dependencies: ["G0-T05"],
    acceptanceCriteriaAr: "صلاحيات على مستوى النموذج والخدمة مع عزل المستأجرين",
    implementationNotesAr: "دعم admin, data_scientist, viewer roles مع API key management",
  },
  {
    id: "G6-T03",
    number: "G6-03",
    nameAr: "تكامل مع خدمات النظام الأساسي",
    nameEn: "Platform service integration",
    groupCode: "G6",
    descriptionAr: "تكامل مع CRM، Analytics، وخدمات أخرى في النظام الأساسي",
    descriptionEn: "Integration with CRM, Analytics, and other platform services",
    type: "Backend",
    priority: "High",
    status: "NOT_STARTED",
    dependencies: ["G6-T01"],
    acceptanceCriteriaAr: "webhooks و events لتكامل مع CRM و Analytics",
    implementationNotesAr: "استخدام event-driven architecture مع message queue",
  },
  {
    id: "G6-T04",
    number: "G6-04",
    nameAr: "توثيق API ونموذج للdevelopers",
    nameEn: "API documentation and developer portal",
    groupCode: "G6",
    descriptionAr: "توثيق شامل لـ API مع أمثلة تفاعلية وأدوات تجربة",
    descriptionEn: "Comprehensive API documentation with interactive examples and playground",
    type: "Frontend",
    priority: "Medium",
    status: "NOT_STARTED",
    dependencies: ["G6-T01"],
    acceptanceCriteriaAr: "توثيق Swagger UI مع أمثلة runnable لكل endpoint",
    implementationNotesAr: "استخدام Swagger UI أو Redoc مع أمثلة مسبقة",
  },
  {
    id: "G6-T05",
    number: "G6-05",
    nameAr: "إنشاء تقرير المرحلة النهائي G6",
    nameEn: "Create final G6 stage report",
    groupCode: "G6",
    descriptionAr: "تقرير المرحلة النهائي لمنصة الذكاء الاصطناعي",
    descriptionEn: "Final stage report for AI Platform module",
    type: "Report",
    priority: "Critical",
    status: "NOT_STARTED",
    dependencies: ["G6-T01", "G6-T02", "G6-T03", "G6-T04"],
    acceptanceCriteriaAr: "تقرير شامل يغطي جميع المجموعات G0-G6 مع مقاييس الجودة",
    implementationNotesAr: "يتضمن مقاييس الأداء والأمان ونتائج الاختبارات",
  },
];
