/**
 * Identity Execution Data
 * -----------------------
 * Business data for Identity & Access Management execution groups and tasks.
 *
 * IMPORTANT: This file contains ONLY business data.
 * All execution logic (types, calculators, validators, constants)
 * MUST be imported from the shared framework: @/lib/execution
 */

import type {
  GroupStatus,
  TaskType,
  TaskPriority,
  TaskStatus,
} from "../../lib/execution";

// ── Identity-Specific Task Type ────────────────────────────────────────────

/**
 * Identity Task — Business data for an Identity task.
 *
 * NOTE: This is NOT an ExecutionTask. The IdentityExecutionProvider
 * converts this to ExecutionTask when providing data to the framework.
 */
export interface IdentityTask {
  id: string;
  number: string;
  nameAr: string;
  nameEn: string;
  groupCode: string;
  descriptionAr: string;
  descriptionEn: string;
  type: TaskType;
  priority: TaskPriority;
  status: TaskStatus;
  dependencies: string[];
  acceptanceCriteriaAr: string;
  implementationNotesAr: string;
}

// ── Identity Execution Groups ──────────────────────────────────────────────

/**
 * Identity Execution Groups — Business data for group definitions.
 *
 * NOTE: This is NOT an ExecutionGroup[]. The IdentityExecutionProvider
 * converts this to ExecutionGroup[] when providing data to the framework.
 */
export const IDENTITY_GROUP_DATA = [
  {
    code: "G0",
    titleAr: "الأساس: إدارة المستخدمين والمصادقة",
    titleEn: "Foundation: User Management & Authentication",
    purposeAr: "تأسيس نظام إدارة المستخدمين والمصادقة الأساسي.",
    purposeEn: "Establish core user management and authentication system.",
    status: "NOT_STARTED" as GroupStatus,
    dependencies: [],
    canParallelizeWith: [],
    stageReport: null,
  },
  {
    code: "G1",
    titleAr: "الميزات الأساسية: الأدوار والصلاحيات",
    titleEn: "Core Features: Roles & Permissions",
    purposeAr: "بناء نظام الأدوار والصلاحيات الأساسي.",
    purposeEn: "Build core roles and permissions system.",
    status: "NOT_STARTED" as GroupStatus,
    dependencies: ["G0"],
    canParallelizeWith: ["G2"],
    stageReport: null,
  },
  {
    code: "G2",
    titleAr: "المصادقة المتقدمة: MFA و SSO",
    titleEn: "Advanced Auth: MFA & SSO",
    purposeAr: "تطبيق المصادقة متعددة العوامل و Single Sign-On.",
    purposeEn: "Implement multi-factor authentication and Single Sign-On.",
    status: "NOT_STARTED" as GroupStatus,
    dependencies: ["G0"],
    canParallelizeWith: ["G1"],
    stageReport: null,
  },
  {
    code: "G3",
    titleAr: "التفويض: RBAC و ABAC",
    titleEn: "Authorization: RBAC & ABAC",
    purposeAr: "تنفيذ نماذج التفويض القائم على الأدوار والسمات.",
    purposeEn: "Implement role-based and attribute-based authorization models.",
    status: "NOT_STARTED" as GroupStatus,
    dependencies: ["G1"],
    canParallelizeWith: ["G4"],
    stageReport: null,
  },
  {
    code: "G4",
    titleAr: "التدقيق والامتثال",
    titleEn: "Audit & Compliance",
    purposeAr: "نظام تسجيل الأحداث وتتبع التغييرات والامتثال التنظيمي.",
    purposeEn: "Event logging, change tracking, and regulatory compliance.",
    status: "NOT_STARTED" as GroupStatus,
    dependencies: ["G0", "G1"],
    canParallelizeWith: ["G3"],
    stageReport: null,
  },
  {
    code: "G5",
    titleAr: "الاتحاد: LDAP و SAML",
    titleEn: "Federation: LDAP & SAML",
    purposeAr: "ربط النظام مع LDAP و SAML لدعم المؤسسات الكبرى.",
    purposeEn: "Integrate with LDAP and SAML for enterprise support.",
    status: "NOT_STARTED" as GroupStatus,
    dependencies: ["G2", "G3"],
    canParallelizeWith: ["G6"],
    stageReport: null,
  },
  {
    code: "G6",
    titleAr: "مراقبة الأمان",
    titleEn: "Security Monitoring",
    purposeAr: "نظام مراقبة الأحداث الأمنية والتنبيهات والتحليلات.",
    purposeEn: "Security event monitoring, alerts, and analytics.",
    status: "NOT_STARTED" as GroupStatus,
    dependencies: ["G4", "G5"],
    canParallelizeWith: [],
    stageReport: null,
  },
];

// ── Identity Tasks ─────────────────────────────────────────────────────────

export const IDENTITY_TASKS: IdentityTask[] = [
  // ── G0: Foundation — User Management & Authentication ──────────────────────
  {
    id: "G0-T01",
    number: "G0-01",
    nameAr: "تصميم مخطط قاعدة بيانات المستخدمين",
    nameEn: "Design users database schema",
    groupCode: "G0",
    descriptionAr: "إنشاء جدول users الأساسي مع tenant_id و جميع الحقول المطلوبة",
    descriptionEn: "Create core users table with tenant_id and all required fields",
    type: "Database",
    priority: "Critical",
    status: "NOT_STARTED",
    dependencies: [],
    acceptanceCriteriaAr: "جدول users يحتوي id, tenant_id, email, password_hash, display_name, status, created_at, updated_at",
    implementationNotesAr: "Flyway migration مع فهرسة tenant_id + email unique constraint",
  },
  {
    id: "G0-T02",
    number: "G0-02",
    nameAr: "إنشاء خدمة التسجيل للمستخدمين",
    nameEn: "Create user registration service",
    groupCode: "G0",
    descriptionAr: "خدمة backend لإنشاء حسابات مستخدمين جدد مع تشفير كلمة المرور",
    descriptionEn: "Backend service for creating new user accounts with password hashing",
    type: "Backend",
    priority: "Critical",
    status: "NOT_STARTED",
    dependencies: ["G0-T01"],
    acceptanceCriteriaAr: "POST /api/identity/users يسجل مستخدم جديد مع تشفير bcrypt",
    implementationNotesAr: "bcrypt hash مع salt rounds 12، التحقق من عدم تكرار البريد الإلكتروني",
  },
  {
    id: "G0-T03",
    number: "G0-03",
    nameAr: "إنشاء خدمة تسجيل الدخول",
    nameEn: "Create login service",
    groupCode: "G0",
    descriptionAr: "خدمة backend للمصادقة عبر البريد الإلكتروني وكلمة المرور",
    descriptionEn: "Backend authentication service via email and password",
    type: "Backend",
    priority: "Critical",
    status: "NOT_STARTED",
    dependencies: ["G0-T02"],
    acceptanceCriteriaAr: "POST /api/identity/auth/login يرجع JWT عند صحة بيانات الدخول",
    implementationNotesAr: "JWT access token (15min) + refresh token (7 days)، تسجيل محاولات الدخول",
  },
  {
    id: "G0-T04",
    number: "G0-04",
    nameAr: "إنشاء صفحة تسجيل الدخول",
    nameEn: "Create login page",
    groupCode: "G0",
    descriptionAr: "واجهة أمامية لتسجيل الدخول بتصميم احترافي",
    descriptionEn: "Frontend login form with professional design",
    type: "Frontend",
    priority: "Critical",
    status: "NOT_STARTED",
    dependencies: ["G0-T03"],
    acceptanceCriteriaAr: "صفحة /identity/login تعمل مع RTL و LTR و تظهر أخطاء الدخول",
    implementationNotesAr: "React form مع react-hook-form و zod validation",
  },
  {
    id: "G0-T05",
    number: "G0-05",
    nameAr: "إنشاء صفحة تسجيل الحساب",
    nameEn: "Create registration page",
    groupCode: "G0",
    descriptionAr: "واجهة أمامية لإنشاء حساب جديد",
    descriptionEn: "Frontend registration form for new accounts",
    type: "Frontend",
    priority: "High",
    status: "NOT_STARTED",
    dependencies: ["G0-T04"],
    acceptanceCriteriaAr: "صفحة /identity/register تعمل مع التحقق من صحة المدخلات",
    implementationNotesAr: "React form مع تحقق من قوة كلمة المرور",
  },
  {
    id: "G0-T06",
    number: "G0-06",
    nameAr: "إنشاء خدمة إدارة الجلسات",
    nameEn: "Create session management service",
    groupCode: "G0",
    descriptionAr: "إدارة refresh tokens و إصدار جلسات جديدة و إلغاء الجلسات",
    descriptionEn: "Manage refresh tokens, issue new sessions, revoke sessions",
    type: "Backend",
    priority: "Critical",
    status: "NOT_STARTED",
    dependencies: ["G0-T03"],
    acceptanceCriteriaAr: "POST /api/identity/auth/refresh يصدر token جديد، POST /api/identity/auth/logout يلغي الجلسة",
    implementationNotesAr: "Redis store للجلسات النشطة مع TTL",
  },

  // ── G1: Core Features — Roles & Permissions ────────────────────────────────
  {
    id: "G1-T01",
    number: "G1-01",
    nameAr: "تصميم مخطط جداول الأدوار والصلاحيات",
    nameEn: "Design roles & permissions schema",
    groupCode: "G1",
    descriptionAr: "إنشاء جداول roles, permissions, role_permissions, user_roles",
    descriptionEn: "Create roles, permissions, role_permissions, user_roles tables",
    type: "Database",
    priority: "Critical",
    status: "NOT_STARTED",
    dependencies: ["G0-T01"],
    acceptanceCriteriaAr: "4 جداول مع tenant_id و unique constraints مطبقة",
    implementationNotesAr: "Flyway migration مع foreign keys و junction tables",
  },
  {
    id: "G1-T02",
    number: "G1-02",
    nameAr: "إنشاء خدمة إدارة الأدوار",
    nameEn: "Create role management service",
    groupCode: "G1",
    descriptionAr: "CRUD للأدوار مع إمكانية تعيين الصلاحيات للأدوار",
    descriptionEn: "CRUD for roles with ability to assign permissions to roles",
    type: "Backend",
    priority: "Critical",
    status: "NOT_STARTED",
    dependencies: ["G1-T01"],
    acceptanceCriteriaAr: "API endpoints لإنشاء وتحديث وحذف الأدوار وتعيين الصلاحيات",
    implementationNotesAr: "role name unique per tenant، حماية الأدوار النظامية من الحذف",
  },
  {
    id: "G1-T03",
    number: "G1-03",
    nameAr: "إنشاء خدمة إدارة الصلاحيات",
    nameEn: "Create permission management service",
    groupCode: "G1",
    descriptionAr: "CRUD للصلاحيات مع دعم الصلاحيات المتداخلة",
    descriptionEn: "CRUD for permissions with hierarchical permission support",
    type: "Backend",
    priority: "Critical",
    status: "NOT_STARTED",
    dependencies: ["G1-T01"],
    acceptanceCriteriaAr: "API endpoints لإنشاء وتحديث وحذف الصلاحيات مع hierarchy",
    implementationNotesAr: "Permission format: resource:action (e.g., users:read, orders:write)",
  },
  {
    id: "G1-T04",
    number: "G1-04",
    nameAr: "إنشاء صفحة إدارة الأدوار",
    nameEn: "Create roles management page",
    groupCode: "G1",
    descriptionAr: "واجهة أمامية لإدارة الأدوار وتعيين الصلاحيات",
    descriptionEn: "Frontend for managing roles and assigning permissions",
    type: "Frontend",
    priority: "High",
    status: "NOT_STARTED",
    dependencies: ["G1-T02"],
    acceptanceCriteriaAr: "صفحة /identity/roles تسمح بإنشاء وتعديل وحذف الأدوار",
    implementationNotesAr: "DataTable مع إمكانية السحب والإفلات للصلاحيات",
  },
  {
    id: "G1-T05",
    number: "G1-05",
    nameAr: "إنشاء صفحة إدارة المستخدمين",
    nameEn: "Create user management page",
    groupCode: "G1",
    descriptionAr: "واجهة أمامية لإدارة المستخدمين وتعيين الأدوار",
    descriptionEn: "Frontend for managing users and assigning roles",
    type: "Frontend",
    priority: "High",
    status: "NOT_STARTED",
    dependencies: ["G1-T04"],
    acceptanceCriteriaAr: "صفحة /identity/users تسمح بعرض وتعديل وحذف المستخدمين",
    implementationNotesAr: "DataTable مع بحث وفلتر وتفعيل/تعطيل المستخدمين",
  },

  // ── G2: Advanced Auth — MFA & SSO ─────────────────────────────────────────
  {
    id: "G2-T01",
    number: "G2-01",
    nameAr: "تصميم مخطط بيانات MFA",
    nameEn: "Design MFA data schema",
    groupCode: "G2",
    descriptionAr: "إنشاء جدول user_mfa_settings مع دعم TOTP و SMS",
    descriptionEn: "Create user_mfa_settings table with TOTP and SMS support",
    type: "Database",
    priority: "Critical",
    status: "NOT_STARTED",
    dependencies: ["G0-T01"],
    acceptanceCriteriaAr: "جدول user_mfa_settings مع encrypted secret و backup codes",
    implementationNotesAr: "Flyway migration مع تشفير المفاتيح السرية",
  },
  {
    id: "G2-T02",
    number: "G2-02",
    nameAr: "تنفيذ خدمة TOTP",
    nameEn: "Implement TOTP service",
    groupCode: "G2",
    descriptionAr: "خدمة لإنشاء التحقق من تطبيق المصادقة (Google Authenticator)",
    descriptionEn: "Service for generating authenticator app verification (Google Authenticator)",
    type: "Backend",
    priority: "Critical",
    status: "NOT_STARTED",
    dependencies: ["G2-T01"],
    acceptanceCriteriaAr: "POST /api/identity/mfa/totp/setup يرجع QR code و secret",
    implementationNotesAr: "RFC 6238 compliance مع base32 secret encoding",
  },
  {
    id: "G2-T03",
    number: "G2-03",
    nameAr: "تنفيذ خدمة SMS OTP",
    nameEn: "Implement SMS OTP service",
    groupCode: "G2",
    descriptionAr: "خدمة لإرسال رموز التحقق عبر SMS",
    descriptionEn: "Service for sending verification codes via SMS",
    type: "Backend",
    priority: "High",
    status: "NOT_STARTED",
    dependencies: ["G2-T01"],
    acceptanceCriteriaAr: "POST /api/identity/mfa/sms/send يرسل رمز 6 أرقام",
    implementationNotesAr: "Redis cache للرموز مع TTL 5 دقائق، Rate limiting",
  },
  {
    id: "G2-T04",
    number: "G2-04",
    nameAr: "إنشاء صفحة إعداد MFA",
    nameEn: "Create MFA setup page",
    groupCode: "G2",
    descriptionAr: "واجهة أمامية لإعداد المصادقة متعددة العوامل",
    descriptionEn: "Frontend for setting up multi-factor authentication",
    type: "Frontend",
    priority: "High",
    status: "NOT_STARTED",
    dependencies: ["G2-T02", "G2-T03"],
    acceptanceCriteriaAr: "صفحة /identity/mfa/setup تدعم QR code و SMS setup",
    implementationNotesAr: "React component مع خطوات متعددة (wizard)",
  },
  {
    id: "G2-T05",
    number: "G2-05",
    nameAr: "تنفيذ خدمة SSO مع OIDC",
    nameEn: "Implement SSO with OIDC",
    groupCode: "G2",
    descriptionAr: "دعم Single Sign-On عبر OpenID Connect",
    descriptionEn: "Support Single Sign-On via OpenID Connect",
    type: "Backend",
    priority: "High",
    status: "NOT_STARTED",
    dependencies: ["G2-T02"],
    acceptanceCriteriaAr: "POST /api/identity/auth/sso/callback يقبل OIDC tokens",
    implementationNotesAr: "OIDC discovery endpoint مع JWKS rotation",
  },
  {
    id: "G2-T06",
    number: "G2-06",
    nameAr: "إنشاء صفحة تأكيد MFA",
    nameEn: "Create MFA verification page",
    groupCode: "G2",
    descriptionAr: "واجهة أمامية للتحقق من رمز MFA أثناء تسجيل الدخول",
    descriptionEn: "Frontend for verifying MFA code during login",
    type: "Frontend",
    priority: "Critical",
    status: "NOT_STARTED",
    dependencies: ["G2-T04"],
    acceptanceCriteriaAr: "صفحة /identity/mfa/verify تقبل رمز TOTP أو SMS",
    implementationNotesAr: "Auto-submit عند إدخال 6 أرقام",
  },

  // ── G3: Authorization — RBAC & ABAC ───────────────────────────────────────
  {
    id: "G3-T01",
    number: "G3-01",
    nameAr: "تنفيذ محرك RBAC",
    nameEn: "Implement RBAC engine",
    groupCode: "G3",
    descriptionAr: "محرك للتحقق من الصلاحيات بناءً على الأدوار المُسندة",
    descriptionEn: "Engine for checking permissions based on assigned roles",
    type: "Backend",
    priority: "Critical",
    status: "NOT_STARTED",
    dependencies: ["G1-T02", "G1-T03"],
    acceptanceCriteriaAr: "hasPermission(userId, resource, action) يتحقق من جميع الأدوار المُسندة",
    implementationNotesAr: "Cache permissions في Redis مع invalidation عند تغيير الأدوار",
  },
  {
    id: "G3-T02",
    number: "G3-02",
    nameAr: "تنفيذ محرك ABAC",
    nameEn: "Implement ABAC engine",
    groupCode: "G3",
    descriptionAr: "محرك للتحقق من الصلاحيات بناءً على السمات (العمر، القسم، الموقع)",
    descriptionEn: "Engine for attribute-based authorization (age, department, location)",
    type: "Backend",
    priority: "High",
    status: "NOT_STARTED",
    dependencies: ["G3-T01"],
    acceptanceCriteriaAr: "evaluatePolicy(userId, resource, attributes) ينفذ سياسات ABAC",
    implementationNotesAr: "XACML-inspired policy language مع JSON DSL",
  },
  {
    id: "G3-T03",
    number: "G3-03",
    nameAr: "إنشاء middleware للتفويض",
    nameEn: "Create authorization middleware",
    groupCode: "G3",
    descriptionAr: "Middleware للتحقق من الصلاحيات قبل الوصول للـ endpoints",
    descriptionEn: "Middleware to verify permissions before endpoint access",
    type: "Backend",
    priority: "Critical",
    status: "NOT_STARTED",
    dependencies: ["G3-T01"],
    acceptanceCriteriaAr: "requirePermission(resource, action) يمنع الوصول بدون صلاحية",
    implementationNotesAr: "Express/Fastify middleware مع cached permission check",
  },
  {
    id: "G3-T04",
    number: "G3-04",
    nameAr: "إنشاء صفحة إدارة السياسات",
    nameEn: "Create policy management page",
    groupCode: "G3",
    descriptionAr: "واجهة أمامية لإدارة سياسات ABAC",
    descriptionEn: "Frontend for managing ABAC policies",
    type: "Frontend",
    priority: "Medium",
    status: "NOT_STARTED",
    dependencies: ["G3-T02"],
    acceptanceCriteriaAr: "صفحة /identity/policies تسمح بإنشاء وتعديل وحذف السياسات",
    implementationNotesAr: "Visual policy builder مع JSON editor toggle",
  },
  {
    id: "G3-T05",
    number: "G3-05",
    nameAr: "كتابة اختبارات RBAC و ABAC",
    nameEn: "Write RBAC and ABAC tests",
    groupCode: "G3",
    descriptionAr: "اختبارات شاملة لمحركات RBAC و ABAC",
    descriptionEn: "Comprehensive tests for RBAC and ABAC engines",
    type: "Test",
    priority: "Critical",
    status: "NOT_STARTED",
    dependencies: ["G3-T03"],
    acceptanceCriteriaAr: "جميع اختبارات RBAC و ABAC تمر (unit + integration)",
    implementationNotesAr: "Vitest مع mock permissions و roles",
  },

  // ── G4: Audit & Compliance ─────────────────────────────────────────────────
  {
    id: "G4-T01",
    number: "G4-01",
    nameAr: "تصميم مخطط سجل التدقيق",
    nameEn: "Design audit log schema",
    groupCode: "G4",
    descriptionAr: "إنشاء جدول audit_logs مع tenant_id و partitioning",
    descriptionEn: "Create audit_logs table with tenant_id and partitioning",
    type: "Database",
    priority: "Critical",
    status: "NOT_STARTED",
    dependencies: ["G0-T01"],
    acceptanceCriteriaAr: "جدول audit_logs مع action, entity_type, entity_id, old_value, new_value, performed_by",
    implementationNotesAr: "Partitioned by month مع retention policy",
  },
  {
    id: "G4-T02",
    number: "G4-02",
    nameAr: "تنفيذ خدمة تسجيل الأحداث",
    nameEn: "Implement event logging service",
    groupCode: "G4",
    descriptionAr: "خدمة لتسجيل جميع الأحداث التالية في سجل التدقيق",
    descriptionEn: "Service for logging all subsequent events to audit log",
    type: "Backend",
    priority: "Critical",
    status: "NOT_STARTED",
    dependencies: ["G4-T01"],
    acceptanceCriteriaAr: "logEvent(action, entityType, entityId, oldValue, newValue, performedBy) يسجل الحدث",
    implementationNotesAr: "Async logging مع queue لتجنب تأخير الاستجابة",
  },
  {
    id: "G4-T03",
    number: "G4-03",
    nameAr: "تنفيذ تتبع التغييرات للحسابات",
    nameEn: "Implement account change tracking",
    groupCode: "G4",
    descriptionAr: "تتبع جميع تغييرات المستخدمين (اسم، بريد، حالة، أدوار)",
    descriptionEn: "Track all user changes (name, email, status, roles)",
    type: "Backend",
    priority: "High",
    status: "NOT_STARTED",
    dependencies: ["G4-T02"],
    acceptanceCriteriaAr: "كل تغيير في user يسجل مع old_value و new_value",
    implementationNotesAr: "Database triggers + application-level logging",
  },
  {
    id: "G4-T04",
    number: "G4-04",
    nameAr: "إنشاء صفحة سجل التدقيق",
    nameEn: "Create audit log page",
    groupCode: "G4",
    descriptionAr: "واجهة أمامية لعرض سجل التدقيق مع بحث وفلتر",
    descriptionEn: "Frontend for viewing audit log with search and filter",
    type: "Frontend",
    priority: "High",
    status: "NOT_STARTED",
    dependencies: ["G4-T02"],
    acceptanceCriteriaAr: "صفحة /identity/audit تسمح بالبحث والفلتر حسب التاريخ والحدث والمستخدم",
    implementationNotesAr: "DataTable مع تصدير CSV و PDF",
  },
  {
    id: "G4-T05",
    number: "G4-05",
    nameAr: "تنفيذ تقارير الامتثال",
    nameEn: "Implement compliance reports",
    groupCode: "G4",
    descriptionAr: "تقارير تلقائية للامتثال التنظيمي (GDPR, SOC2)",
    descriptionEn: "Automated reports for regulatory compliance (GDPR, SOC2)",
    type: "Report",
    priority: "Medium",
    status: "NOT_STARTED",
    dependencies: ["G4-T04"],
    acceptanceCriteriaAr: "تقارير PDF للامتثال تُنشأ تلقائياً شهرياً",
    implementationNotesAr: "Cron job مع PDF generation و email notification",
  },

  // ── G5: Federation — LDAP & SAML ──────────────────────────────────────────
  {
    id: "G5-T01",
    number: "G5-01",
    nameAr: "تنفيذ اتصال LDAP",
    nameEn: "Implement LDAP connector",
    groupCode: "G5",
    descriptionAr: "متصل LDAP للمصادقة مع Active Directory و OpenLDAP",
    descriptionEn: "LDAP connector for authentication with Active Directory and OpenLDAP",
    type: "Backend",
    priority: "High",
    status: "NOT_STARTED",
    dependencies: ["G2-T02", "G3-T01"],
    acceptanceCriteriaAr: "POST /api/identity/federation/ldap/auth يتحقق من بيانات LDAP",
    implementationNotesAr: "LDAP bind + user search مع TLS encryption",
  },
  {
    id: "G5-T02",
    number: "G5-02",
    nameAr: "تنفيذ IdP SAML",
    nameEn: "Implement SAML IdP",
    groupCode: "G5",
    descriptionAr: "Identity Provider لـ SAML 2.0",
    descriptionEn: "SAML 2.0 Identity Provider",
    type: "Backend",
    priority: "High",
    status: "NOT_STARTED",
    dependencies: ["G2-T05"],
    acceptanceCriteriaAr: "Metadata endpoint و SSO/SLO endpoints نشطة",
    implementationNotesAr: "XML signature validation مع certificate rotation",
  },
  {
    id: "G5-T03",
    number: "G5-03",
    nameAr: "تنفيذ SP SAML",
    nameEn: "Implement SAML SP",
    groupCode: "G5",
    descriptionAr: "Service Provider لـ SAML 2.0",
    descriptionEn: "SAML 2.0 Service Provider",
    type: "Backend",
    priority: "Medium",
    status: "NOT_STARTED",
    dependencies: ["G5-T02"],
    acceptanceCriteriaAr: "POST /api/identity/federation/saml/callback يقبل SAML assertions",
    implementationNotesAr: "SAML response validation مع attribute mapping",
  },
  {
    id: "G5-T04",
    number: "G5-04",
    nameAr: "إنشاء صفحة إدارة الاتصالات المؤسسية",
    nameEn: "Create federation management page",
    groupCode: "G5",
    descriptionAr: "واجهة أمامية لإدارة اتصالات LDAP و SAML",
    descriptionEn: "Frontend for managing LDAP and SAML connections",
    type: "Frontend",
    priority: "Medium",
    status: "NOT_STARTED",
    dependencies: ["G5-T01", "G5-T02"],
    acceptanceCriteriaAr: "صفحة /identity/federation تسمح بتكوين واختبار الاتصالات",
    implementationNotesAr: "Connection test button مع real-time feedback",
  },
  {
    id: "G5-T05",
    number: "G5-05",
    nameAr: "تنفيذ مزامنة المستخدمين من LDAP",
    nameEn: "Implement user sync from LDAP",
    groupCode: "G5",
    descriptionAr: "مزامنة تلقائية للمستخدمين من LDAP كل 6 ساعات",
    descriptionEn: "Automatic user sync from LDAP every 6 hours",
    type: "Backend",
    priority: "Medium",
    status: "NOT_STARTED",
    dependencies: ["G5-T01"],
    acceptanceCriteriaAr: "Cron job يزامن المستخدمين مع تجنب التكرار",
    implementationNotesAr: "Delta sync مع LDAP modifyTimestamp filter",
  },

  // ── G6: Security Monitoring ────────────────────────────────────────────────
  {
    id: "G6-T01",
    number: "G6-01",
    nameAr: "تنفيذ كاشف محاولات الدخول المشبوهة",
    nameEn: "Implement suspicious login detector",
    groupCode: "G6",
    descriptionAr: "كشف محاولات الدخول غير الطبيعية (IP مختلفة، أوقات غريبة)",
    descriptionEn: "Detect abnormal login attempts (different IPs, unusual times)",
    type: "Backend",
    priority: "Critical",
    status: "NOT_STARTED",
    dependencies: ["G4-T02"],
    acceptanceCriteriaAr: "تنبيه فوري عند اكتشاف محاولة دخول مشبوهة",
    implementationNotesAr: "ML-based anomaly detection مع configurable thresholds",
  },
  {
    id: "G6-T02",
    number: "G6-02",
    nameAr: "تنفيذ Rate Limiter للأمان",
    nameEn: "Implement security rate limiter",
    groupCode: "G6",
    descriptionAr: "تحديد معدل الطلبات لمنع هجمات Brute Force",
    descriptionEn: "Rate limiting to prevent Brute Force attacks",
    type: "Security",
    priority: "Critical",
    status: "NOT_STARTED",
    dependencies: ["G0-T03"],
    acceptanceCriteriaAr: "بعد 5 محاولات فاشلة، يتم قفل الحساب لمدة 15 دقيقة",
    implementationNotesAr: "Redis-based rate limiter مع exponential backoff",
  },
  {
    id: "G6-T03",
    number: "G6-03",
    nameAr: "تنفيذ لوحة معلومات الأمان",
    nameEn: "Implement security dashboard",
    groupCode: "G6",
    descriptionAr: "لوحة معلومات تعرض أحداث الأمان والتنبيهات",
    descriptionEn: "Dashboard displaying security events and alerts",
    type: "Frontend",
    priority: "High",
    status: "NOT_STARTED",
    dependencies: ["G6-T01", "G6-T02"],
    acceptanceCriteriaAr: "صفحة /identity/security تعرض إحصائيات الأمان والتنبيهات النشطة",
    implementationNotesAr: "Real-time updates مع WebSocket",
  },
  {
    id: "G6-T04",
    number: "G6-04",
    nameAr: "تنفيذ نظام التنبيهات",
    nameEn: "Implement alert notification system",
    groupCode: "G6",
    descriptionAr: "إرسال تنبيهات عبر البريد الإلكتروني و SMS عند أحداث أمنية",
    descriptionEn: "Send alerts via email and SMS for security events",
    type: "Backend",
    priority: "High",
    status: "NOT_STARTED",
    dependencies: ["G6-T01"],
    acceptanceCriteriaAr: "تنبيه فوري عبر email + SMS عند محاولة دخول مشبوهة",
    implementationNotesAr: "Nodemailer + Twilio مع throttling",
  },
  {
    id: "G6-T05",
    number: "G6-05",
    nameAr: "تنفيذ تقارير الأمان الشهرية",
    nameEn: "Implement monthly security reports",
    groupCode: "G6",
    descriptionAr: "تقارير شهرية شاملة للأحداث الأمنية",
    descriptionEn: "Comprehensive monthly security event reports",
    type: "Report",
    priority: "Medium",
    status: "NOT_STARTED",
    dependencies: ["G6-T03"],
    acceptanceCriteriaAr: "تقرير شهري PDF يحتوي إحصائيات وتوصيات",
    implementationNotesAr: "Cron job مع PDF generation و email distribution",
  },
];
