/**
 * Inventory Execution Data
 * ------------------------
 * Business data for Inventory execution groups and tasks.
 *
 * IMPORTANT: This file contains ONLY business data.
 * All execution logic (types, calculators, validators, constants)
 * MUST be imported from the shared framework: @/lib/execution
 */

import type {
  GroupStatus,
  TaskType,
  TaskPriority,
  TaskStatus,
} from "../../lib/execution";

// ── Inventory-Specific Task Type ──────────────────────────────────────────

/**
 * Inventory Task — Business data for an Inventory task.
 *
 * NOTE: This is NOT an ExecutionTask. The InventoryExecutionProvider
 * converts this to ExecutionTask when providing data to the framework.
 */
export interface InventoryTask {
  id: string;
  number: string;
  nameAr: string;
  nameEn: string;
  groupCode: string;
  descriptionAr: string;
  descriptionEn: string;
  type: TaskType;
  priority: TaskPriority;
  status: TaskStatus;
  dependencies: string[];
  acceptanceCriteriaAr: string;
  implementationNotesAr: string;
}

// ── Inventory Execution Groups ────────────────────────────────────────────

/**
 * Inventory Execution Groups — Business data for group definitions.
 *
 * NOTE: This is NOT an ExecutionGroup[]. The InventoryExecutionProvider
 * converts this to ExecutionGroup[] when providing data to the framework.
 */
export const INVENTORY_GROUP_DATA = [
  {
    code: "G0",
    titleAr: "الأساسيات — سلسلة الأصناف والمواقع",
    titleEn: "Foundation — Item Master & Locations",
    purposeAr: "تأسيس جدول الأصناف الأساسي، تعريف المواقع والمستودعات، وربط النظام ببيانات ERP.",
    purposeEn: "Establish core item master table, define locations and warehouses, and link to ERP data.",
    status: "NOT_STARTED" as GroupStatus,
    dependencies: [],
    canParallelizeWith: [],
    stageReport: null,
  },
  {
    code: "G1",
    titleAr: "الميزات الأساسية — تتبع المخزون والتعديلات",
    titleEn: "Core Features — Stock Tracking & Adjustments",
    purposeAr: "تنفيذ تتبع المخزون اللحظي، تعديلات المخزون، و規制 الانتقالي للمخزون.",
    purposeEn: "Implement real-time stock tracking, inventory adjustments, and transitional stock normalization.",
    status: "NOT_STARTED" as GroupStatus,
    dependencies: ["G0"],
    canParallelizeWith: ["G2"],
    stageReport: null,
  },
  {
    code: "G2",
    titleAr: "إدارة المستودعات — مواقع الباين والإدخال",
    titleEn: "Warehouse Management — Bin Locations & Putaway",
    purposeAr: "تنفيذ مواقع الباين، قواعد الإدخال التلقائي، وخصائص المستودع.",
    purposeEn: "Implement bin locations, automated putaway rules, and warehouse properties.",
    status: "NOT_STARTED" as GroupStatus,
    dependencies: ["G0"],
    canParallelizeWith: ["G1"],
    stageReport: null,
  },
  {
    code: "G3",
    titleAr: "الاستلام والشحن",
    titleEn: "Receiving & Shipping",
    purposeAr: "تنفيذ عمليات الاستلام من الموردين، الشحن للعملاء، وإيصالات التحويل.",
    purposeEn: "Implement supplier receiving, customer shipping, and transfer receipts.",
    status: "NOT_STARTED" as GroupStatus,
    dependencies: ["G1"],
    canParallelizeWith: [],
    stageReport: null,
  },
  {
    code: "G4",
    titleAr: "الجرد الدوري والتدقيق",
    titleEn: "Cycle Counting & Auditing",
    purposeAr: "تنفيذ الجرد الدوري، جرد الفروقات، وسجل التدقيق الكامل.",
    purposeEn: "Implement cycle counting, variance counting, and full audit trail.",
    status: "NOT_STARTED" as GroupStatus,
    dependencies: ["G1", "G3"],
    canParallelizeWith: [],
    stageReport: null,
  },
  {
    code: "G5",
    titleAr: "التحليلات والتحسين",
    titleEn: "Analytics & Optimization",
    purposeAr: "تنفيذ لوحات التحليل، تنبيهات إعادة الطلب، وتحسين إعادة التخزين.",
    purposeEn: "Implement analytics dashboards, reorder alerts, and restocking optimization.",
    status: "NOT_STARTED" as GroupStatus,
    dependencies: ["G1", "G3", "G4"],
    canParallelizeWith: [],
    stageReport: null,
  },
];

// ── Inventory Tasks ───────────────────────────────────────────────────────

export const INVENTORY_TASKS: InventoryTask[] = [
  // ── G0: Foundation — Item Master & Locations ──────────────────────────────
  {
    id: "G0-T01", number: "G0-01",
    nameAr: "إنشاء جدول الأصناف الأساسي (item_master)",
    nameEn: "Create item master table (item_master)",
    groupCode: "G0",
    descriptionAr: "جدول الأصناف الأساسي مع كود الصنف، الوصف بالعربية والإنجليزية، الوحدة الأساسية، التصنيف، والحالة.",
    descriptionEn: "Core item table with SKU, Arabic/English description, base unit, category, and status.",
    type: "Database", priority: "Critical", status: "NOT_STARTED",
    dependencies: [],
    acceptanceCriteriaAr: "جدول item_master موجود مع tenant_id UUID NOT NULL، 12 فهرسًا، وقيود التحقق",
    implementationNotesAr: "Flyway migration: V20260801_1__create_item_master.sql",
  },
  {
    id: "G0-T02", number: "G0-02",
    nameAr: "إنشاء جدول المستودعات (warehouses)",
    nameEn: "Create warehouses table",
    groupCode: "G0",
    descriptionAr: "جدول المستودعات مع الكود والاسم والعنوان والمنطقة الجغرافية والقدرة التخزينية.",
    descriptionEn: "Warehouse table with code, name, address, geographic region, and storage capacity.",
    type: "Database", priority: "Critical", status: "NOT_STARTED",
    dependencies: [],
    acceptanceCriteriaAr: "جدول warehouses موجود مع عزل المستأجرين وقيود UNIQUE على الكود",
    implementationNotesAr: "Flyway migration: V20260801_2__create_warehouses.sql",
  },
  {
    id: "G0-T03", number: "G0-03",
    nameAr: "إنشاء جدول المواقع (locations)",
    nameEn: "Create locations table",
    groupCode: "G0",
    descriptionAr: "جدول المواقع مع الرمز والاسم والنوع (مستودع/منطقة/باين) والعلاقات الهرمية.",
    descriptionEn: "Locations table with code, name, type (warehouse/zone/bin), and hierarchical relationships.",
    type: "Database", priority: "Critical", status: "NOT_STARTED",
    dependencies: ["G0-T02"],
    acceptanceCriteriaAr: "جدول locations مع parent_id self-referencing FK و3 أنماط موقع",
    implementationNotesAr: "Flyway migration: V20260801_3__create_locations.sql",
  },
  {
    id: "G0-T04", number: "G0-04",
    nameAr: "إنشاء جدول وحدات القياس (uom)",
    nameEn: "Create units of measurement table",
    groupCode: "G0",
    descriptionAr: "جدول وحدات القياس مع التحويلات بين الوحدات (كجم/غرام/قطعة/كرتون).",
    descriptionEn: "UOM table with conversion factors between units (kg/g/pcs/carton).",
    type: "Database", priority: "High", status: "NOT_STARTED",
    dependencies: ["G0-T01"],
    acceptanceCriteriaAr: "جدول uom مع جدول uom_conversions للتحويلات",
    implementationNotesAr: "Flyway migration: V20260801_4__create_uom.sql",
  },
  {
    id: "G0-T05", number: "G0-05",
    nameAr: "إنشاء صفحة /inventory الرئيسية",
    nameEn: "Create /inventory main page",
    groupCode: "G0",
    descriptionAr: "إنشاء مسار /inventory مع التخطيط المستقل وشريط التنقل الداخلي.",
    descriptionEn: "Create /inventory route with independent layout and internal navigation bar.",
    type: "Frontend", priority: "Critical", status: "NOT_STARTED",
    dependencies: [],
    acceptanceCriteriaAr: "مسار /inventory يعمل مع تخطيط مستقل يحتوي 6 تبويبات",
    implementationNotesAr: "apps/web/app/inventory/layout.tsx",
  },
  {
    id: "G0-T06", number: "G0-06",
    nameAr: "إنشاء صفحة إدارة الأصناف",
    nameEn: "Create item management page",
    groupCode: "G0",
    descriptionAr: "صفحة عرض وبحث وإضافة وتعديل الأصناف مع جدول بيانات تفاعلي.",
    descriptionEn: "Page for viewing, searching, adding, and editing items with interactive data table.",
    type: "Frontend", priority: "Critical", status: "NOT_STARTED",
    dependencies: ["G0-T05"],
    acceptanceCriteriaAr: "صفحة الأصناف تعرض جدول بيانات مع بحث وتصفية وإضافة/تعديل/حذف",
    implementationNotesAr: "apps/web/app/inventory/items/page.tsx",
  },
  {
    id: "G0-T07", number: "G0-07",
    nameAr: "إنشاء صفحة إدارة المستودعات والمواقع",
    nameEn: "Create warehouse & location management page",
    groupCode: "G0",
    descriptionAr: "صفحة إدارة المستودعات والمواقع مع عرض شجري للمواقع.",
    descriptionEn: "Warehouse and location management page with tree view for locations.",
    type: "Frontend", priority: "High", status: "NOT_STARTED",
    dependencies: ["G0-T05"],
    acceptanceCriteriaAr: "صفحة المستودعات تعرض شجرة المواقع مع إضافة/تعديل",
    implementationNotesAr: "apps/web/app/inventory/locations/page.tsx",
  },
  {
    id: "G0-T08", number: "G0-08",
    nameAr: "إنشاء API endpoints للأصناف والمواقع",
    nameEn: "Create API endpoints for items & locations",
    groupCode: "G0",
    descriptionAr: "REST endpoints: CRUD للأصناف، CRUD للمواقع، بحث، وتصفح بالـ cursor.",
    descriptionEn: "REST endpoints: items CRUD, locations CRUD, search, cursor-based pagination.",
    type: "API", priority: "Critical", status: "NOT_STARTED",
    dependencies: ["G0-T01", "G0-T02", "G0-T03"],
    acceptanceCriteriaAr: "12 endpoints على الأقل مع keyset pagination وعزل المستأجرين",
    implementationNotesAr: "apps/api/src/inventory/ modules",
  },
  {
    id: "G0-T09", number: "G0-09",
    nameAr: "كتابة اختبارات Jest لـ API",
    nameEn: "Write Jest tests for API",
    groupCode: "G0",
    descriptionAr: "اختبارات التكامل لجميع endpoints مع Testcontainers وPostgreSQL.",
    descriptionEn: "Integration tests for all endpoints with Testcontainers and PostgreSQL.",
    type: "Test", priority: "Critical", status: "NOT_STARTED",
    dependencies: ["G0-T08"],
    acceptanceCriteriaAr: "جميع الاختبارات تمر على PostgreSQL 16 مع عزل المستأجرين",
    implementationNotesAr: "Testcontainers-based integration tests",
  },

  // ── G1: Core Features — Stock Tracking & Adjustments ──────────────────────
  {
    id: "G1-T01", number: "G1-01",
    nameAr: "إنشاء جدول أرصدة المخزون (stock_balances)",
    nameEn: "Create stock balances table",
    groupCode: "G1",
    descriptionAr: "جدول أرصدة المخزون مع الصنف والموقع والكمية المحجوزة والمتاحة.",
    descriptionEn: "Stock balances table with item, location, quantity on hand, reserved, and available.",
    type: "Database", priority: "Critical", status: "NOT_STARTED",
    dependencies: ["G0-T01", "G0-T03"],
    acceptanceCriteriaAr: "جدول stock_balances مع UNIQUE(item_id, location_id) وقيود كمية",
    implementationNotesAr: "Flyway migration: V20260802_1__create_stock_balances.sql",
  },
  {
    id: "G1-T02", number: "G1-02",
    nameAr: "إنشاء جدول حركات المخزون (stock_movements)",
    nameEn: "Create stock movements table",
    groupCode: "G1",
    descriptionAr: "سجل كل حركة مخزون (وارد/صادر/تحويل/تعديل) مع المرجع والكمية والتاريخ.",
    descriptionEn: "Record of every stock movement (in/out/transfer/adjustment) with reference, quantity, and timestamp.",
    type: "Database", priority: "Critical", status: "NOT_STARTED",
    dependencies: ["G1-T01"],
    acceptanceCriteriaAr: "جدول stock_movements مع فهرس على التاريخ ونوع الحركة",
    implementationNotesAr: "Flyway migration: V20260802_2__create_stock_movements.sql",
  },
  {
    id: "G1-T03", number: "G1-03",
    nameAr: "تنفيذ محرك تحديث الأرصدة (stock engine)",
    nameEn: "Implement stock balance update engine",
    groupCode: "G1",
    descriptionAr: "محرك لتحديث أرصدة المخزون تلقائيًا عند كل حركة مع ضمان عدم السماح بالسالب.",
    descriptionEn: "Engine to update stock balances automatically on every movement with negative-stock prevention.",
    type: "Backend", priority: "Critical", status: "NOT_STARTED",
    dependencies: ["G1-T01", "G1-T02"],
    acceptanceCriteriaAr: "المحرك يمنع الأرصدة السالبة ويحافظ على سلامة البيانات",
    implementationNotesAr: "Transaction-safe balance update with row-level locking",
  },
  {
    id: "G1-T04", number: "G1-04",
    nameAr: "تنفيذ تعديلات المخزون",
    nameEn: "Implement inventory adjustments",
    groupCode: "G1",
    descriptionAr: "نماذج تعديل المخزون مع سبب التعديل والموافقة وسجل التعديل.",
    descriptionEn: "Inventory adjustment forms with reason, approval workflow, and adjustment log.",
    type: "Frontend", priority: "High", status: "NOT_STARTED",
    dependencies: ["G1-T03"],
    acceptanceCriteriaAr: "نموذج تعديل يطلب سببًا ويوثق التعديل في سجل الحركات",
    implementationNotesAr: "apps/web/app/inventory/adjustments/page.tsx",
  },
  {
    id: "G1-T05", number: "G1-05",
    nameAr: "تنفيذ حجوزات المخزون",
    nameEn: "Implement stock reservations",
    groupCode: "G1",
    descriptionAr: "نظام حجز المخزون للطلبات مع تحرير الحجز تلقائيًا عند الشحن.",
    descriptionEn: "Stock reservation system for orders with automatic release on shipment.",
    type: "Backend", priority: "High", status: "NOT_STARTED",
    dependencies: ["G1-T03"],
    acceptanceCriteriaAr: "الحجز يقلل المخزون المتاح ويزيد المحجوز، التحرير يعيد الحساب",
    implementationNotesAr: "Reservation API with optimistic concurrency control",
  },
  {
    id: "G1-T06", number: "G1-06",
    nameAr: "إنشاء صفحة ملخص المخزون",
    nameEn: "Create stock summary page",
    groupCode: "G1",
    descriptionAr: "صفحة عرض ملخص المخزون لكل صنف مع تصفية حسب المستودع والتصنيف.",
    descriptionEn: "Stock summary page showing per-item totals with warehouse and category filters.",
    type: "Frontend", priority: "High", status: "NOT_STARTED",
    dependencies: ["G1-T03"],
    acceptanceCriteriaAr: "الصفحة تعرض جدول ملخص مع إجماليات وألوان تحذيرية",
    implementationNotesAr: "apps/web/app/inventory/stock/page.tsx",
  },
  {
    id: "G1-T07", number: "G1-07",
    nameAr: "كتابة اختبارات التكامل للمخزون",
    nameEn: "Write stock integration tests",
    groupCode: "G1",
    descriptionAr: "اختبارات شاملة لمحرك الأرصدة والتعديلات والحجوزات.",
    descriptionEn: "Comprehensive tests for balance engine, adjustments, and reservations.",
    type: "Test", priority: "Critical", status: "NOT_STARTED",
    dependencies: ["G1-T03"],
    acceptanceCriteriaAr: "جميع الاختبارات تمر مع سيناريوهات متعددة للمستخدمين",
    implementationNotesAr: "Testcontainers tests with concurrent access scenarios",
  },

  // ── G2: Warehouse Management — Bin Locations & Putaway ───────────────────
  {
    id: "G2-T01", number: "G2-01",
    nameAr: "إنشاء جدول مواقع الباين (bin_locations)",
    nameEn: "Create bin locations table",
    groupCode: "G2",
    descriptionAr: "جدول تفصيلي لمواقع الباين مع الرمز والمعلمات الفيزيائية والحالة.",
    descriptionEn: "Detailed bin locations table with code, physical attributes, and status.",
    type: "Database", priority: "Critical", status: "NOT_STARTED",
    dependencies: ["G0-T03"],
    acceptanceCriteriaAr: "جدول bin_locations مع ربط بالموقع الأصل وقيود الحالة",
    implementationNotesAr: "Flyway migration: V20260803_1__create_bin_locations.sql",
  },
  {
    id: "G2-T02", number: "G2-02",
    nameAr: "تنفيذ قواعد الإدخال التلقائي (putaway rules)",
    nameEn: "Implement automated putaway rules",
    groupCode: "G2",
    descriptionAr: "قواعد ذكية لتحديد موقع الإدخال بناءً على الوزن والحجم والتصنيف.",
    descriptionEn: "Smart rules for determining putaway location based on weight, size, and category.",
    type: "Backend", priority: "High", status: "NOT_STARTED",
    dependencies: ["G2-T01"],
    acceptanceCriteriaAr: "النظام يقترح موقعًا تلقائيًا بناءً على خصائص الصنف",
    implementationNotesAr: "Rule engine with configurable priority scoring",
  },
  {
    id: "G2-T03", number: "G2-03",
    nameAr: "تنفيذ تفريغ المخزون (stock clearing)",
    nameEn: "Implement stock clearing between bins",
    groupCode: "G2",
    descriptionAr: "نقل المخزون بين مواقع الباين مع تحديث الأرصدة تلقائيًا.",
    descriptionEn: "Transfer stock between bin locations with automatic balance updates.",
    type: "Backend", priority: "High", status: "NOT_STARTED",
    dependencies: ["G1-T03", "G2-T01"],
    acceptanceCriteriaAr: "النقل ينشئ حركتين (صادر+وارد) ويحدث الأرصدة في معاملة واحدة",
    implementationNotesAr: "Atomic transfer with dual-movement recording",
  },
  {
    id: "G2-T04", number: "G2-04",
    nameAr: "إنشاء صفحة خريطة المستودع",
    nameEn: "Create warehouse map page",
    groupCode: "G2",
    descriptionAr: "عرض بصري لمواقع الباين مع حالة كل موقع (فارغ/ممتلئ/محجوز).",
    descriptionEn: "Visual display of bin locations with status indicators (empty/full/reserved).",
    type: "Frontend", priority: "Medium", status: "NOT_STARTED",
    dependencies: ["G2-T01"],
    acceptanceCriteriaAr: "خريطة تفاعلية تعرض مواقع الباين بألوان حسب الحالة",
    implementationNotesAr: "apps/web/app/inventory/warehouse-map/page.tsx",
  },
  {
    id: "G2-T05", number: "G2-05",
    nameAr: "تنفيذ سياسات الامتثال للمستودع",
    nameEn: "Implement warehouse compliance policies",
    groupCode: "G2",
    descriptionAr: "قواعد الامتثال مثل: حظر خلط التواريخ، حد الأوزان، مسارات الأمان.",
    descriptionEn: "Compliance rules such as date-segregation, weight limits, safety aisles.",
    type: "Backend", priority: "Medium", status: "NOT_STARTED",
    dependencies: ["G2-T01"],
    acceptanceCriteriaAr: "النظام يمنع انتهاك سياسات الامتثال ويسجل المحاولات",
    implementationNotesAr: "Policy engine with violation logging",
  },
  {
    id: "G2-T06", number: "G2-06",
    nameAr: "كتابة اختبارات إدارة المستودعات",
    nameEn: "Write warehouse management tests",
    groupCode: "G2",
    descriptionAr: "اختبارات لـ putaway ونقل الباين وسياسات الامتثال.",
    descriptionEn: "Tests for putaway, bin transfers, and compliance policies.",
    type: "Test", priority: "High", status: "NOT_STARTED",
    dependencies: ["G2-T02", "G2-T03"],
    acceptanceCriteriaAr: "جميع الاختبارات تمر مع سيناريوهات امتثال متعددة",
    implementationNotesAr: "Integration tests with compliance policy scenarios",
  },

  // ── G3: Receiving & Shipping ──────────────────────────────────────────────
  {
    id: "G3-T01", number: "G3-01",
    nameAr: "إنشاء جدول طلبات الاستلام (receive_orders)",
    nameEn: "Create receive orders table",
    groupCode: "G3",
    descriptionAr: "جدول طلبات الاستلام من الموردين مع المرجع والمواد الكمية المتوقعة.",
    descriptionEn: "Supplier receive orders table with reference, line items, expected quantities.",
    type: "Database", priority: "Critical", status: "NOT_STARTED",
    dependencies: ["G1-T01"],
    acceptanceCriteriaAr: "جدول receive_orders مع receive_order_items وحالة الاستلام",
    implementationNotesAr: "Flyway migration: V20260804_1__create_receive_orders.sql",
  },
  {
    id: "G3-T02", number: "G3-02",
    nameAr: "تنفيذ عملية الاستلام",
    nameEn: "Implement receiving process",
    groupCode: "G3",
    descriptionAr: "عملية استلام المواد مع التحقق من الكمية وجودة التفتيش وتسجيل الفروقات.",
    descriptionEn: "Material receiving process with quantity verification, quality inspection, and variance logging.",
    type: "Backend", priority: "Critical", status: "NOT_STARTED",
    dependencies: ["G3-T01", "G1-T03"],
    acceptanceCriteriaAr: "الاستلام ينشئ حركة وارد ويحدّث الأرصدة ويسجل فروقات الجودة",
    implementationNotesAr: "Receiving workflow with quality gate",
  },
  {
    id: "G3-T03", number: "G3-03",
    nameAr: "تنفيذ عملية الشحن",
    nameEn: "Implement shipping process",
    groupCode: "G3",
    descriptionAr: "عملية شحن المواد للعملاء مع توليد أرقام التتبع وتأكيد التسليم.",
    descriptionEn: "Customer shipping process with tracking number generation and delivery confirmation.",
    type: "Backend", priority: "Critical", status: "NOT_STARTED",
    dependencies: ["G1-T05", "G1-T03"],
    acceptanceCriteriaAr: "الشحن يحرر الحجز وينشئ حركة صادر ويولد رقم تتبع",
    implementationNotesAr: "Shipping workflow with carrier integration hooks",
  },
  {
    id: "G3-T04", number: "G3-04",
    nameAr: "تنفيذ طلبات التحويل بين المستودعات",
    nameEn: "Implement inter-warehouse transfer orders",
    groupCode: "G3",
    descriptionAr: "طلب تحويل مخزون من مستودع إلى آخر مع تتبع الحالات.",
    descriptionEn: "Stock transfer request between warehouses with status tracking.",
    type: "Backend", priority: "High", status: "NOT_STARTED",
    dependencies: ["G3-T01"],
    acceptanceCriteriaAr: "التحويل ينشئ طلب استلام في المستودع المقصود",
    implementationNotesAr: "Transfer order with dual-receipt workflow",
  },
  {
    id: "G3-T05", number: "G3-05",
    nameAr: "إنشاء صفحة طلبات الاستلام والشحن",
    nameEn: "Create receiving & shipping page",
    groupCode: "G3",
    descriptionAr: "صفحة إدارة طلبات الاستلام والشحن مع قوائم بيانات تفاعلية.",
    descriptionEn: "Receiving & shipping management page with interactive lists.",
    type: "Frontend", priority: "High", status: "NOT_STARTED",
    dependencies: ["G3-T02"],
    acceptanceCriteriaAr: "صفحة تعرض طلبات الاستلام والشحن مع تحديث الحالة",
    implementationNotesAr: "apps/web/app/inventory/receiving/page.tsx",
  },
  {
    id: "G3-T06", number: "G3-06",
    nameAr: "كتابة اختبارات الاستلام والشحن",
    nameEn: "Write receiving & shipping tests",
    groupCode: "G3",
    descriptionAr: "اختبارات لعملية الاستلام والشحن والتحويل بين المستودعات.",
    descriptionEn: "Tests for receiving, shipping, and inter-warehouse transfers.",
    type: "Test", priority: "High", status: "NOT_STARTED",
    dependencies: ["G3-T02", "G3-T03"],
    acceptanceCriteriaAr: "جميع الاختبارات تمر مع سيناريوهات فروقات الكمية",
    implementationNotesAr: "Integration tests with variance scenarios",
  },

  // ── G4: Cycle Counting & Auditing ────────────────────────────────────────
  {
    id: "G4-T01", number: "G4-01",
    nameAr: "إنشاء جدول جرد الدورات (cycle_counts)",
    nameEn: "Create cycle counts table",
    groupCode: "G4",
    descriptionAr: "جدول جرد الدورات مع المخزون المستهدف والجدولة والمسؤول.",
    descriptionEn: "Cycle counts table with target items, scheduling, and assigned counter.",
    type: "Database", priority: "Critical", status: "NOT_STARTED",
    dependencies: ["G1-T01"],
    acceptanceCriteriaAr: "جدول cycle_counts مع cycle_count_items وحالة الجرد",
    implementationNotesAr: "Flyway migration: V20260805_1__create_cycle_counts.sql",
  },
  {
    id: "G4-T02", number: "G4-02",
    nameAr: "تنفيذ عملية الجرد الدوري",
    nameEn: "Implement cycle counting process",
    groupCode: "G4",
    descriptionAr: "عملية جرد عناصر دورية مع تسجيل العد الفعلي وحساب الفروقات.",
    descriptionEn: "Periodic counting process with actual count recording and variance calculation.",
    type: "Backend", priority: "Critical", status: "NOT_STARTED",
    dependencies: ["G4-T01", "G1-T03"],
    acceptanceCriteriaAr: "الجرد يحسب الفروقات ويقترح تعديلات تلقائية",
    implementationNotesAr: "Cycle count engine with automatic adjustment proposals",
  },
  {
    id: "G4-T03", number: "G4-03",
    nameAr: "تنفيذ جرد الفروقات",
    nameEn: "Implement variance counting",
    groupCode: "G4",
    descriptionAr: "جرد مكثف للعناصر ذات الفروقات الكبيرة مع تحليل الأسباب.",
    descriptionEn: "Intensive counting for high-variance items with root cause analysis.",
    type: "Backend", priority: "High", status: "NOT_STARTED",
    dependencies: ["G4-T02"],
    acceptanceCriteriaAr: "النظام يحدد العناصر ذات الفروقات الكبيرة ويعيدها للجرد",
    implementationNotesAr: "Variance threshold engine with re-count triggers",
  },
  {
    id: "G4-T04", number: "G4-04",
    nameAr: "إنشاء صفحة تقارير الجرد",
    nameEn: "Create cycle count reports page",
    groupCode: "G4",
    descriptionAr: "صفحة عرض تقارير الجرد مع إحصائيات الفروقات والاتجاهات.",
    descriptionEn: "Cycle count reports page with variance statistics and trends.",
    type: "Frontend", priority: "High", status: "NOT_STARTED",
    dependencies: ["G4-T02"],
    acceptanceCriteriaAr: "الصفحة تعرض إحصائيات الفروقات ورسوم بيانية",
    implementationNotesAr: "apps/web/app/inventory/cycle-count/page.tsx",
  },
  {
    id: "G4-T05", number: "G4-05",
    nameAr: "تنفيذ سجل التدقيق الكامل (audit trail)",
    nameEn: "Implement full audit trail",
    groupCode: "G4",
    descriptionAr: "تسجيل كل عملية مخزون مع المستخدم والوقت والقيمة القديمة والجديدة.",
    descriptionEn: "Log every inventory operation with user, timestamp, old and new values.",
    type: "Backend", priority: "Critical", status: "NOT_STARTED",
    dependencies: ["G1-T02"],
    acceptanceCriteriaAr: "كل حركة مخزون لها سجل تدقيق كامل لا يمكن حذفه",
    implementationNotesAr: "Immutable audit log with append-only table",
  },
  {
    id: "G4-T06", number: "G4-06",
    nameAr: "كتابة اختبارات الجرد والتدقيق",
    nameEn: "Write cycle counting & audit tests",
    groupCode: "G4",
    descriptionAr: "اختبارات لعملية الجرد وحساب الفروقات وسجل التدقيق.",
    descriptionEn: "Tests for counting process, variance calculation, and audit trail.",
    type: "Test", priority: "High", status: "NOT_STARTED",
    dependencies: ["G4-T02", "G4-T05"],
    acceptanceCriteriaAr: "جميع الاختبارات تمر مع تحقق سلامة سجل التدقيق",
    implementationNotesAr: "Tests with audit trail integrity verification",
  },

  // ── G5: Analytics & Optimization ──────────────────────────────────────────
  {
    id: "G5-T01", number: "G5-01",
    nameAr: "إنشاء لوحات تحليل المخزون",
    nameEn: "Create inventory analytics dashboards",
    groupCode: "G5",
    descriptionAr: "لوحات تفاعلية لتحليل دوران المخزون وقيمة المخزون وتنمية التكلفة.",
    descriptionEn: "Interactive dashboards for inventory turnover, value analysis, and carrying cost.",
    type: "Frontend", priority: "High", status: "NOT_STARTED",
    dependencies: ["G1-T01", "G1-T03"],
    acceptanceCriteriaAr: "لوحات تعرض KPIs رئيسية مع رسوم بيانية تفاعلية",
    implementationNotesAr: "apps/web/app/inventory/analytics/page.tsx",
  },
  {
    id: "G5-T02", number: "G5-02",
    nameAr: "تنفيذ تنبيهات إعادة الطلب",
    nameEn: "Implement reorder alerts",
    groupCode: "G5",
    descriptionAr: "نظام تنبيهات تلقائي عندما ينخفض المخزون عن الحد الأدنى.",
    descriptionEn: "Automatic alert system when stock falls below minimum threshold.",
    type: "Backend", priority: "High", status: "NOT_STARTED",
    dependencies: ["G1-T01", "G1-T03"],
    acceptanceCriteriaAr: "النظام يرسل تنبيهًا عندما ينخفض المخزون المتاح عن الحد الأدنى",
    implementationNotesAr: "Threshold-based alert engine with configurable thresholds",
  },
  {
    id: "G5-T03", number: "G5-03",
    nameAr: "تنفيذ تحليل دوران المخزون",
    nameEn: "Implement inventory turnover analysis",
    groupCode: "G5",
    descriptionAr: "حساب معدل دوران المخزون وتحليلABC للعناصر.",
    descriptionEn: "Inventory turnover ratio calculation and ABC analysis for items.",
    type: "Backend", priority: "Medium", status: "NOT_STARTED",
    dependencies: ["G1-T03"],
    acceptanceCriteriaAr: "التحليل يصنف العناصر A/B/C ويحسب معدلات الدوران",
    implementationNotesAr: "ABC classification with configurable thresholds",
  },
  {
    id: "G5-T04", number: "G5-04",
    nameAr: "تنفيذ تحسين إعادة التخزين",
    nameEn: "Implement restocking optimization",
    groupCode: "G5",
    descriptionAr: "خوارزميات لحساب كمية إعادة الطلب المثلى بناءً على الاستهلاك التاريخي.",
    descriptionEn: "Algorithms for calculating optimal reorder quantity based on historical consumption.",
    type: "AI", priority: "Medium", status: "NOT_STARTED",
    dependencies: ["G5-T02"],
    acceptanceCriteriaAr: "النظام يقترح كمية إعادة تخزين مثلى لكل صنف",
    implementationNotesAr: "EOQ model with demand forecasting",
  },
  {
    id: "G5-T05", number: "G5-05",
    nameAr: "إنشاء تقرير تقييم المخزون",
    nameEn: "Create inventory valuation report",
    groupCode: "G5",
    descriptionAr: "تقرير تقييم المخزون بطرق FIFO/WAC مع تحليل هوامش الربح.",
    descriptionEn: "Inventory valuation report using FIFO/WAC methods with margin analysis.",
    type: "Report", priority: "High", status: "NOT_STARTED",
    dependencies: ["G1-T03"],
    acceptanceCriteriaAr: "التقرير يدعم FIFO وWAC مع تصدير PDF/Excel",
    implementationNotesAr: "Valuation engine with dual-method support",
  },
  {
    id: "G5-T06", number: "G5-06",
    nameAr: "إنشاء تقرير مرحلة G5 (الأخير)",
    nameEn: "Create G5 stage report (final)",
    groupCode: "G5",
    descriptionAr: "تقرير مرحلة G5 النهائي مع ملخص شامل للموديول.",
    descriptionEn: "Final G5 stage report with comprehensive module summary.",
    type: "Report", priority: "Critical", status: "NOT_STARTED",
    dependencies: ["G5-T01", "G5-T02", "G5-T03", "G5-T04", "G5-T05"],
    acceptanceCriteriaAr: "تقرير شامل يغطي جميع المجموعات والمهمات",
    implementationNotesAr: "docs/inventory/stage-reports/INVENTORY-G5-STAGE-REPORT.md",
  },
];
